### ISSUE TITLE
Gradle Build

### ISSUE THREAD

**Issue by Serializator** [libraryaddict/LibsDisguises#100]
When I try to import _LibsDisguises_ as a Gradle module in IntelliJ it tells me that it can't get:
http://server.o2gaming.com/downloads/spigot.jar
Is there a solution to this? Because it seems to be a problem on the side of the download linked above.

**Comment by NavidK0** [comment]
Yeah, the jar is spigot-1.9.jar, I just haven't pushed an update with the changes yet. The jar is on the link though, just change it from spigot.jar to spigot-1.9.jar

**Comment by NavidK0** [comment]
Fixed with https://github.com/libraryaddict/LibsDisguises/commit/2cf48f79164536c30643bb854ac78f6b10575ec4
