### ISSUE TITLE
MythicMobs

### ISSUE THREAD

**Issue by tteeee** [libraryaddict/LibsDisguises#102]
MythicMobs lastest build.

> [23:03:45 INFO]: java.lang.reflect.InvocationTargetException
> [23:03:45 INFO]:        at sun.reflect.GeneratedMethodAccessor437.invoke(Unknown Source)
> [23:03:45 INFO]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [23:03:45 INFO]:        at java.lang.reflect.Method.invoke(Method.java:498)
> [23:03:45 INFO]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:760)
> [23:03:45 INFO]:        at me.libraryaddict.disguise.disguisetypes.Disguise.startDisguise(Disguise.java:753)
> [23:03:45 INFO]:        at me.libraryaddict.disguise.DisguiseAPI.disguiseEntity(DisguiseAPI.java:162)
> [23:03:45 INFO]:        at me.libraryaddict.disguise.DisguiseAPI.disguiseToAll(DisguiseAPI.java:233)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Compatibility.LibsDisguisesSupport.setDisguise(LibsDisguisesSupport.java:604)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Skills.Mechanics.DisguiseSkill.cast(DisguiseSkill.java:23)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Skills.SkillMechanic.executeNoTargetSkill(SkillMechanic.java:362)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Skills.SkillMechanic.executeSkills(SkillMechanic.java:302)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Skills.SkillMechanic.execute(SkillMechanic.java:160)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Skills.Skill.ExecuteTimerSkills(Skill.java:574)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Skills.Skill.RunTimerSkills(Skill.java:544)
> [23:03:45 INFO]:        at net.elseland.xikage.MythicMobs.Clock.MythicMobsAsyncClock.run(MythicMobsAsyncClock.java:23)
> [23:03:45 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
> [23:03:45 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> [23:03:45 INFO]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [23:03:45 INFO]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [23:03:45 INFO]:        at java.lang.Thread.run(Thread.java:745)
> [23:03:45 INFO]: Caused by: java.lang.IllegalStateException: Asynchronous player tracker clear!
> [23:03:45 INFO]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
> [23:03:45 INFO]:        at net.minecraft.server.v1_8_R3.EntityTrackerEntry.clear(EntityTrackerEntry.java:544)
> [23:03:45 INFO]:        ... 20 more

**Comment by NavidK0** [comment]
LibsDisguises for 1.8 is not being updated.
