### ISSUE TITLE
ghost

### ISSUE THREAD

**Issue by anemul** [libraryaddict/LibsDisguises#108]
I have a problem with disguising as shulker , I can see my normal self as a ghost in the disguise and can not move . Other disguises I can see myself walking and running like a ghost but with the disguise following closely . There are no errors in server console . Everything is up to date including the latest protocollib . I am using 1.9 . Not sure if other players can seem e like this or not . I have not checked that yet .

**Comment by NavidK0** [comment]
Disable it through the config option:

#Stop shulker disguises from moving, they're weird. This option only effects PLAYERS that are disguised, other entities disguised as shulkers will NOT be effected!
StopShulkerDisguisesFromMoving: true
