### ISSUE TITLE
Shulker Disguise not working

### ISSUE THREAD

**Issue by PgBiel** [libraryaddict/LibsDisguises#110]
When I do shulker disguise, it says "An internal error occurred while attempting to perform this command". (This also happened at the previous version, 9.0)
`21.03 10:32:53 [Server] INFO ... 23 more
21.03 10:32:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:27) ~[?:?]
21.03 10:32:53 [Server] INFO at me.libraryaddict.disguise.commands.BaseDisguiseCommand.parseDisguise(BaseDisguiseCommand.java:498) ~[?:?]
21.03 10:32:53 [Server] INFO at me.libraryaddict.disguise.commands.BaseDisguiseCommand.getDisguiseWatcherMethods(BaseDisguiseCommand.java:94) ~[?:?]
21.03 10:32:53 [Server] INFO at java.lang.Class.getMethods(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO Caused by: java.lang.ClassNotFoundException: java.util.Optional
21.03 10:32:53 [Server] INFO ... 23 more
21.03 10:32:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:27) ~[?:?]
21.03 10:32:53 [Server] INFO at me.libraryaddict.disguise.commands.BaseDisguiseCommand.parseDisguise(BaseDisguiseCommand.java:498) ~[?:?]
21.03 10:32:53 [Server] INFO at me.libraryaddict.disguise.commands.BaseDisguiseCommand.getDisguiseWatcherMethods(BaseDisguiseCommand.java:94) ~[?:?]
21.03 10:32:53 [Server] INFO at java.lang.Class.getMethods(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.7.0_72]
21.03 10:32:53 [Server] INFO Caused by: java.lang.NoClassDefFoundError: java/util/Optional
21.03 10:32:53 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
21.03 10:32:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at it.mri.mycommand.commands.CmdCustomCommands.onCommand(CmdCustomCommands.java:101) [MyCommand.jar:?]
21.03 10:32:53 [Server] INFO at it.mri.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:222) [MyCommand.jar:?]
21.03 10:32:53 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.chat(CraftPlayer.java:238) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.chat(PlayerConnection.java:1266) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-66f95e6-4cd46b2]
21.03 10:32:53 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'dis' in plugin LibsDisguises v9.0.1
21.03 10:32:53 [Server] ERROR null`
Using: git-Spigot-66f95e6-4cd46b2 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
LibsDisguises v9.0.1.

**Comment by NavidK0** [comment]
[http://i.imgur.com/A36o0WO.png](url)

[http://i.imgur.com/MoT6vr2.png](url)


It works for me, it should look like the image above. There might be a conflicting plugin perhaps?

**Comment by NavidK0** [comment]
Oh... I know why this is. Are you using Java 7 instead of Java 8?

**Comment by NavidK0** [comment]
Deleted earlier comment, I have a fix for this.

**Comment by NavidK0** [comment]
Fixed with https://github.com/libraryaddict/LibsDisguises/commit/763024d27aab619caf7662e95760099d712b7f58
