### ISSUE TITLE
End Crystal kicks whoever renders the disguised entity/player

### ISSUE THREAD

**Issue by PgBiel** [libraryaddict/LibsDisguises#113]
Yup.
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(22) + length(1) exceeds writerIndex(22): UnpooledHeapByteBuf(ridx: 22, widx: 22, cap: 22)`

**Comment by NavidK0** [comment]
Should be fixed now with https://github.com/libraryaddict/LibsDisguises/commits/master, just grab a dev build, I'm not at home with my usual computer.

**Comment by PgBiel** [comment]
Okay thanks :smile: :+1:
