### ISSUE TITLE
End Crystal toggle base (Suggestion)

### ISSUE THREAD

**Issue by PgBiel** [libraryaddict/LibsDisguises#114]
So, on 1.9 they added a NBT tag to End Crystal that lets you toggle their base, and I'd like to suggest this feature. :wink:

**Comment by NavidK0** [comment]
I've added API for this with https://github.com/libraryaddict/LibsDisguises/commit/976d00dcc282fbc7a4d6b08db0dddadc55cb47da
however, it doesn't seem to update for some reason or another.
