### ISSUE TITLE
1.9 Issues with player disguises

### ISSUE THREAD

**Issue by andrewchi12345** [libraryaddict/LibsDisguises#115]
watcher.setItemStack(EquipmentSlot, ItemStack) does not work, along with set armor and set skin from a game profile

**Comment by NavidK0** [comment]
https://github.com/libraryaddict/LibsDisguises/commit/976d00dcc282fbc7a4d6b08db0dddadc55cb47da
might've fixed this, can you check it out?

**Comment by andrewchi12345** [comment]
Still does not work.
`
		for (EquipmentSlot slot : EquipmentSlot.values()) {
			watcher.setItemStack(slot, new ItemStack(Material.AIR, 1));
		}
`

**Comment by libraryaddict** [comment]
Confirm still a bug

**Comment by pascoej** [comment]
@libraryaddict This is a bug again :(

**Comment by libraryaddict** [comment]
Fixed in next build
