### ISSUE TITLE
Error with wolf disguise

### ISSUE THREAD

**Issue by Rockslide** [libraryaddict/LibsDisguises#116]
http://pastebin.com/Yf1muKQm

CastleSiege code line referenced in error:
http://pastebin.com/TMjtTVK2

Libs Build 32, Protocollib 3.7.0, latest Spigot

**Comment by NavidK0** [comment]
Should be fixed with https://github.com/libraryaddict/LibsDisguises/commit/976d00dcc282fbc7a4d6b08db0dddadc55cb47da

**Comment by Rockslide** [comment]
Please reopen, it still occurs!
