### ISSUE TITLE
MythicMobs

### ISSUE THREAD

**Issue by Scratch741** [libraryaddict/LibsDisguises#118]
Hello! I'm having problem when MythicMob horse is disguised (for my case: undead_horse). It kicks me out of the game when horse is summoned.

Spigot 1.9 (R0.1), MythicMobs 2.3.0, LibsDisguise 9.0.2., ProtocolLib 4.0.0

Here is the error: 

> http://sinister.wz.cz/fr.jpg

**Comment by libraryaddict** [comment]
Confirm still a bug

**Comment by Scratch741** [comment]
Sorry! Have not noticed your message. Gonna test it today.
