### ISSUE TITLE
ConcurrentModificationException w/ MythicMobs

### ISSUE THREAD

**Issue by Cryptite** [libraryaddict/LibsDisguises#119]
In order to control the name of the player disguise when manually spawning a MythicMob, I am manually setting the disguise after spawning one. This seems to somewhat quickly (within about 30 mob spawns or so, but not always) cause a [ConcurrentModificationException ](https://dl.dropboxusercontent.com/u/1586068/crash-2016-04-04_10.54.46-server.txt)which crashes the server entirely.

The disguise code I'm using is:

```
private Entity spawnGuard(Generator g, Location l) {
        try {
            Entity guard = mmAPI.getMobAPI().spawnMythicMob("TownGuard", l);
            guard.setCustomName(ChatColor.YELLOW + g.name + " Guard");
            setGuardArmor(g, (LivingEntity) guard);

            me.libraryaddict.disguise.disguisetypes.Disguise disguise = new me.libraryaddict.disguise.disguisetypes.PlayerDisguise(ChatColor.YELLOW + g.name + " Guard", "Bballplay");
            me.libraryaddict.disguise.DisguiseAPI.disguiseEntity(guard, disguise);
            return guard;
        } catch (net.elseland.xikage.MythicMobs.API.Exceptions.InvalidMobTypeException e1) {
            e1.printStackTrace();
        }

        return null;
    }
```

**Comment by libraryaddict** [comment]
Confirm still a bug

**Comment by Cryptite** [comment]
I still have CME crashes (when MM is on) even without this bit of code running. The crashes do still seem to be related to MM spawning mobs with Disguises.

**Comment by libraryaddict** [comment]
Confirm still a bug
