### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by tuckerandlexus** [libraryaddict/LibsDisguises#120]
Hi there, for some reason I keep getting this ClassCastException that kicks me off my server and I think I have narrowed it down to either Libs Disguises or Protocollib? I am using Ultimated Hide N Seek spigot and when I run the plugin without Libs and Prot it works except the disguise part. When I add those two back in and start the game I get kicked and receive this message in my console: http://pastebin.com/4ib6HRk0

I am using CraftBukkit version git-Spigot-ccb6016-f92e01b (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT), ProtocolLib Version (MC: 1.9.2), LibsDisguises v9.0.3, Ultimate_Hide_N_Seek v1.5.9

**Comment by HeroCC** [comment]
Same issue here, using BlockHunt plugin.

**Comment by HeroCC** [comment]
Fixed! I updated protocollib to this build and the error went away http://ci.dmulloy2.net/job/ProtocolLib/271/
