### ISSUE TITLE
Severe Chunk/Entity loads

### ISSUE THREAD

**Issue by TNTUP** [libraryaddict/LibsDisguises#121]
Hi, I came to my study since yesterday when I started unloading some plugins, I've unloaded so far 8 plugins, but now today I tried unloading one by one on my list and I unloaded Libs Disguises and my chunk/entity count fixed my problem since I've upgraded to 1.9.2. 

There's something in Libs's code that keeps entity or chunks loaded so it kills the TPS (Running on Paper atm) the issue persists on Spigot aswell. Removing it fixed my severe entity/chunk issue.

https://github.com/PaperMC/Paper/issues/138 - See here for information

There's no stacktraces or whatever, so saying it here if you can find somethign which causes this problem on my serveur, possibly on others servers<

Notice when I unloaded it from plugman, the entity count decreased drastically in this timings: http://timings.aikar.co/v2/?id=ba21652fb68842a18acae434ece6a7c6 so there's something acting wrong with entities or chunks

**Comment by TNTUP** [comment]
Nevermind, Paper fixed an issue with mob spawning... closing

**Comment by NizarZa123** [comment]
how you fixed it

**Comment by libraryaddict** [comment]
@NizarZa123 why not ping @TNTUP

**Comment by NizarZa123** [comment]
@libraryaddict How i can fix chunk problem when i disguise it removed chunk and everything turn to white... any idea.. screen: http://prntscr.com/ead9ah

**Comment by NizarZa123** [comment]
i'm using spigot 1.8.8
