### ISSUE TITLE
Maven repo unresponsive

### ISSUE THREAD

**Issue by Eluinhost** [libraryaddict/LibsDisguises#123]
Trying to build a plugin that was built against the artifact from http://psmc.ca/repo/ but it keeps failing due to connection timeout

~~In the same vein, my plugin will be used on 1.8 server too, but there doesn't appear to be any public downloads anywhere. Is there somewhere to download these builds still or is it ok to provide a 1.8 download alongside the plugin JAR?~~ I've implemented the subset of functionality I needed myself via ProtocolLib so don't need this any more but others may still require your full plugin

**Comment by libraryaddict** [comment]
Confirm still a problem

**Comment by JBYoshi** [comment]
My guess: The [build log](http://ci.md-5.net/job/LibsDisguises/20/console) makes me think the Maven goals are set to `install`, not `deploy`.

**Comment by JBYoshi** [comment]
Also, it seems that the [repository was changed](https://github.com/libraryaddict/LibsDisguises/commit/2e14df134cd8fe421af28ae8fa9ec72549329bbe) to http://repo.md-5.net/content/groups/public/ some time ago. It has some more recent versions, but not all (it has `7.2.4-SNAPSHOT` through `8.2.6-SNAPSHOT`, latest is `9.0.4-SNAPSHOT`).

**Comment by melair** [comment]
Following this trail myself this morning, repo.md-5.net does not have recent builds @JBYoshi seems on point, adding the maven deploy target should hopefully resolve it.

**Comment by JBYoshi** [comment]
Should be fixed now, but will require a URL change. See my above comment.
