### ISSUE TITLE
Libs disguises and SkillApi

### ISSUE THREAD

**Issue by publicg4** [libraryaddict/LibsDisguises#125]
Disguises applied to mobs with set duration (e.g. 2sec)using SkillApi disguise mechanism do not expire. When applied to players, the mechanism works fine. The SkillApi author directed me to your issue tracker. I am using your build #8 spigot 1.9 and skillapi 3.84 and protocollib build #273

**Comment by libraryaddict** [comment]
My disguises don't have an expire feature.
