### ISSUE TITLE
Not supported plugin Colored Tags

### ISSUE THREAD

**Issue by mat41997** [libraryaddict/LibsDisguises#128]
the white name in the tag on tab
![1](https://cloud.githubusercontent.com/assets/5884000/15122066/a0678228-161d-11e6-8f1d-537ffdcfd147.png)

plugin Colored Tags
http://dev.bukkit.org/bukkit-plugins/colored-tags/

**Comment by libraryaddict** [comment]
Honestly I know I didn't write the code for those nametags, so this bug is likely to stay for a while.

**Comment by mat41997** [comment]
ok, i fix it : )

thx for all
