### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) - StackOverflowError

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#133]
@libraryaddict 
LibsDisguise dev 27

http://paste.ubuntu.com/16385725/

**Comment by mat41997** [comment]
i have this same error on spigot
http://hastebin.com/pogisivuva.avrasm

**Comment by JBYoshi** [comment]
Should be fixed in #134.

**Comment by mibby** [comment]
It also seems this error may have duplicated the loaded entities in certain chunks for item frames. As-in corrupting it (i.e. item frames popping off a wall. Tping away and back, they are still there and pop off again. Continuously duping until the item frames are gone. Using NBTEditor, it detected over 5,000 item frames in the area in the specific chunk location.

@JBYoshi You may want to look into how it reads the chunks just in case. Something definitely broke in Libsdisguise, causing entity duplication.

**Comment by JBYoshi** [comment]
That's exactly what I did. LibsDisguises was loading the chunks before they finished loading; I stopped that. Tested and should work. Here's a download if you want it: https://github.com/JBYoshi/LibsDisguises/releases/tag/fix-sounds-1

**Comment by mibby** [comment]
Maybe @libraryaddict should rewrite that portion of the code to not load chunks before they finished loading, to avoid recursive entity duplication. :( Had to spend 6 hours scanning my world with RegionFixer (https://github.com/Fenixin/Minecraft-Region-Fixer) to delete all entities in chunks that had more than 300 entities in them. Not everyone may be aware of the problem if they tried loading the broken Libsdisguise versions.

**Comment by JBYoshi** [comment]
@mibby Unfortunately, that isn't possible. To properly disguise entity sounds, it has to know which entity is playing the sound. Unfortunately, the sound packet doesn't include the entity, just the location, so LibsDisguises has to figure out which entity it is, and to do that it in the fastest manner it needs to find all the entities in the specific chunk.

**Comment by mibby** [comment]
@JBYoshi :( Well the dangerous recursive chunk loading problem still happens. 
http://paste.ubuntu.com/16437528/

On dev 28.

**Comment by libraryaddict** [comment]
Please update
