### ISSUE TITLE
HUGE error and map notworking any more because of it -_-

### ISSUE THREAD

**Issue by AlexNova1555** [libraryaddict/LibsDisguises#135]
so today i have updated the plugin to version 9.0.5
so i have multiworlds and when i was tp far from the spawn the plugin crash with a huge error
with 8297 lines here is the log
i could not paste it anywhere because the size error was big so i have a download here
http://www.filedropper.com/latest1
im using spigot 1.9.2
ProtocolLib 4.0.0 Snapshot b275
Libs 9.0.5

**Comment by libraryaddict** [comment]
Please update
