### ISSUE TITLE
Undisguising resets nametag color.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#142]
LibsDisguise dev 36

Undisguising from a disguise resets your nametag scoreboard.
- Player A has a red nametag above his head.
- Player A disguises as a pig. 
- Hovering over the pig displays Player A's name in red.
- Player A undisguises.
- Player A no longer has a red nametag above his head.
- Player A relogs, red nametag reappears.

**Comment by mibby** [comment]
@libraryaddict Any chances on getting this bug fixed? :)

**Comment by libraryaddict** [comment]
Yeah, I'll look at it later this week

**Comment by libraryaddict** [comment]
Yeah it looks like its caused by switching scoreboard teams, and it doesn't restore teams.
Basically its not really something I intend to fix atm.

**Comment by mibby** [comment]
All good. As long as it will eventually be looked into. :) Is there any reason as to why the scoreboard team is being swapped in the first place with nametags enabled? I'd assume it wouldn't touch scoreboards unless you wanted to hide the display name of a player when he disguises.

**Comment by libraryaddict** [comment]
You know pushing can't be disabled by anything but scoreboards right, so go figure that I have to set the option somewhere. And I may get a little whining if I set the option on their team.. Meh. I'll make an option that does that.

**Comment by mibby** [comment]
Disabled pushing as in if you disguised as a specific player name? I don't see any setting about pushing / collision for entity disguises (since I figured entity bound box is forced client side). I already disable player collision via a PaperSpigot setting, so having it be toggleable in LibsDisguise would probably be ideal if it is forced now to avoid nametag colors being wiped on undisguise. :)

**Comment by libraryaddict** [comment]
Test latest version, reopen this or comment if you can't reopen if the fix breaks.

New option in the config.

**Comment by mibby** [comment]
@libraryaddict Nametags are still being reset when undisguising.

```
# How should the plugin handle self disguises scoreboards?
# MODIFY - Modifies the player's existing scoreboard if possible, otherwise assigns them to a new scoreboard team
# IGNORE - Doesn't touch scoreboards at all, effectively means that if you didn't disable pushing in their scoreboard team they will be pushed around
# CREATE - Assigns them to a new team which copies the attributes of their previous scoreboard team. This means they keep nametag color and other options.
SelfDisguisesScoreboard: IGNORE
```

**Comment by mibby** [comment]
Any update to this? :(

**Comment by mibby** [comment]
Bump.

**Comment by mibby** [comment]
Bump. :(

**Comment by mibby** [comment]
Bump. 🍆

**Comment by mibby** [comment]
Please fix this issue. Seeing players without their scoreboard nametag after they undisguise is bad. :(

**Comment by libraryaddict** [comment]
Test latest build

**Comment by mibby** [comment]
Confirmed fixed. Thanks! You may want to update the default config setting though since MODIFY is no longer valid. It is MODIFY_SCOREBOARD.
