### ISSUE TITLE
(Feature Request) Preventing disguises in worldguard regions.

### ISSUE THREAD

**Issue by BiGUNMAN** [libraryaddict/LibsDisguises#147]
I have a simple feature request, the ability to prevent disguises in certain worldguard regions. If a player enters with a disguise then its removed.

**Comment by groovybluedog** [comment]
YES.
YES.
YES.
+1.

**Comment by libraryaddict** [comment]
Not adding

**Comment by groovybluedog** [comment]
Care to explain more than just "not adding"?

**Comment by libraryaddict** [comment]
I don't care to hook into other plugins, and I don't see it as my responsibility.

WorldGuard should be covering this usecase.

**Comment by groovybluedog** [comment]
Are you feeling okay? You seem pretty salty...

**Comment by partydev** [comment]
Have you had a change of heart?

**Comment by libraryaddict** [comment]
Na

**Comment by partydev** [comment]
> 
> 
> Na

Why, exactly? Why would this be WorldGuard's responsibility?
