### ISSUE TITLE
IllegalStateException: Optional.get() cannot be called on an absent value

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#149]
LibsDisguise dev 44
Paper dev 792 (MC 1.10)
ProtocolLib dev 293
http://paste.ubuntu.com/17686932/

**Comment by kashike** [comment]
Should be fixed with https://github.com/libraryaddict/LibsDisguises/commit/182c6a325944357e4ef60877da90dbbaa8c04158

**Comment by mibby** [comment]
Haven't seen it since updating, so I'll assume it is confirmed fixed. :)
