### ISSUE TITLE
Use /d instructions, leading to the game ran

### ISSUE THREAD

**Issue by yyeerai** [libraryaddict/LibsDisguises#152]
Description: Ticking entity

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
    at sa.ct(SourceFile:1965)
    at sa.cv(SourceFile:1973)
    at sa.m(SourceFile:1560)
    at sb.m(SourceFile:277)
    at vu.m(SourceFile:110)
    at aht.a(SourceFile:1517)
    at aht.g(SourceFile:1495)
    at aht.k(SourceFile:1385)
    at bcd.t(SourceFile:1648)
    at bcd.av(SourceFile:969)
    at bcd.a(SourceFile:399)
    at net.minecraft.client.main.Main.main(SourceFile:124)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at sa.ct(SourceFile:1965)
    at sa.cv(SourceFile:1973)
    at sa.m(SourceFile:1560)
    at sb.m(SourceFile:277)
    at vu.m(SourceFile:110)
    at aht.a(SourceFile:1517)
    at aht.g(SourceFile:1495)

-- Entity being ticked --
Details:
    Entity Type: Bat (vu)
    Entity ID: -10
    Entity Name: 蝙蝠
    Entity's Exact location: 235.47, 74.62, 366.26
    Entity's Block location: World: (235,74,366), Chunk: (at 11,4,14 in 14,22; contains blocks 224,0,352 to 239,255,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.00, -0.08, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at aht.k(SourceFile:1385)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [bmr['lapin_boy'/206, l='MpServer', x=235.47, y=73.00, z=366.26]]
    Chunk stats: MultiplayerChunkCache: 442, 442
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (140,64,256), Chunk: (at 12,4,0 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 374891 game time, 217806 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 18 total; [wk['马'/67, l='MpServer', x=248.00, y=71.00, z=350.10], wk['马'/68, l='MpServer', x=248.42, y=69.00, z=379.87], vu['蝙蝠'/-10, l='MpServer', x=235.47, y=74.62, z=366.26], yw['骷髅'/75, l='MpServer', x=269.50, y=74.00, z=326.50], wk['马'/207, l='MpServer', x=273.97, y=70.00, z=366.42], bmr['lapin_boy'/206, l='MpServer', x=235.47, y=73.00, z=366.26], yy['蜘蛛'/211, l='MpServer', x=276.50, y=35.00, z=375.50], yi['爬行者'/339, l='MpServer', x=282.50, y=45.00, z=325.50], yw['骷髅'/212, l='MpServer', x=274.23, y=70.00, z=378.20], we['羊'/53, l='MpServer', x=202.62, y=71.00, z=359.67], yw['骷髅'/213, l='MpServer', x=282.50, y=30.00, z=320.50], yw['骷髅'/54, l='MpServer', x=200.27, y=71.00, z=352.23], wk['马'/214, l='MpServer', x=272.34, y=68.00, z=392.82], wj['狼'/217, l='MpServer', x=251.90, y=67.00, z=400.66], za['僵尸'/221, l='MpServer', x=221.50, y=22.00, z=411.50], yy['蜘蛛'/62, l='MpServer', x=222.50, y=70.00, z=324.50], yw['骷髅'/222, l='MpServer', x=213.50, y=32.00, z=404.50], vx['鸡'/63, l='MpServer', x=222.27, y=72.00, z=349.10]]
    Retry entities: 0 total; []
    Server brand: Spigot
    Server type: Non-integrated multiplayer server
Stacktrace:
    at bks.a(SourceFile:365)
    at bcd.b(SourceFile:2521)
    at bcd.a(SourceFile:408)
    at net.minecraft.client.main.Main.main(SourceFile:124)

**Comment by libraryaddict** [comment]
Old report, reopen if still a bug
