### ISSUE TITLE
Won't work (crash log provided)

### ISSUE THREAD

**Issue by columb** [libraryaddict/LibsDisguises#153]
LibsDisguises v9.0.9
ProtocolLib v4.1.0-SNAPSHOT-b309
CraftBukkit version git-Spigot-e000104-4cb3258 (MC: 1.9.2) (Implementing API version      ││
││1.9.2-R0.1-SNAPSHOT)
Error log: http://pastebin.com/ASBaKgYM

**Comment by libraryaddict** [comment]
No support for outdated versions
