### ISSUE TITLE
Better ViewSelfDisguises Behavior

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#155]
@libraryaddict Would it be possible to rework how the ViewSelfDisguises functionality works? DisguiseCraft did it significantly better by manipulating your view height and making you actually look through the face of the mob. But with LibsDisguise, your camera angle does not change depending on what you disguised as, your view is obstructed by being inside the mob, and the mob lags behind you as you move around / make movement adjustments. You aren't truly one with the disguise like DisguiseCraft. DC simulated you actually becoming the mob. :(

I believe this is the source if it'll help figure out how they do it.
https://git.hexadigital.net/disguisecraft-team/disguisecraft/tree/master

(Teleportation packet instead of the smaller relative motion packets that the Vanilla MineCraft server uses, PlayerMoveEvent in order to track disguises, etc.)
https://git.hexadigital.net/disguisecraft-team/disguisecraft/blob/master/ModelConfig.txt

**Comment by libraryaddict** [comment]
I don't see self disguises in DisguiseCraft, perhaps a video?

**Comment by libraryaddict** [comment]
Closed due to lack of response.

**Comment by mibby** [comment]
Sorry, I did not see that you had responded. I'll have to downgrade to an old craftbukkit version that DisguiseCraft last supported and take a video of what the perspective changes looked like.

**Comment by mibby** [comment]
@libraryaddict Going through old tickets, apologies for the late update. Downgrading to an older version of DisguiseCraft does not actually seem to support self disguise viewing. I do distinctly remember using a disguise plugin that did change the view point and model of the player to that of the actual mob, but do not remember the name of it. It changed the model and height so if you disguised as a baby chicken, your view point was that near the ground and you could walk through 1x1 blocks.

I'll keep looking and record a video example if I can actually find or recall what it was, but I'm afraid it may have been way back during the hmod alpha minecraft server days or something that may have relied on spoutcraft.

**Comment by libraryaddict** [comment]
That sounds like a mod.

**Comment by mibby** [comment]
I don't recall ever using any client mods, but it may have been a server mod that had additional hooks for the spoutcraft client when that was a thing. If it isn't possible to adjust bound box height and view height position in vanilla using packet manipulation, then I wouldn't worry about it.
