### ISSUE TITLE
Disguise not following when riding entity

### ISSUE THREAD

**Issue by Phreag** [libraryaddict/LibsDisguises#160]
I use this Plugin via API in my morph & magic plugin.
Also i have the Plugin MyPet insatlled on my server which allows riding animals.
If a player is disguised and starts riding a pet, the disguise is shown correctly to other players.
to himself it looks like the mob stays somewhere.
It also happens when riding a vanilla horse, disguise is correct to other players and not visible for the player himself.

Is it possible to fix this?

Also is it possible to complete vanish the player for themseves?

**Comment by xikage** [comment]
Also experiencing this issue.

Any entity disguised as a player will no longer stay on its vehicle and will instead stay suspended in the air where the disguise was applied as the vehicle moves around. This problem was introduced with 1.10

**Comment by libraryaddict** [comment]
Cannot reproduce
