### ISSUE TITLE
Java Errors?!

### ISSUE THREAD

**Issue by SonyUSA** [libraryaddict/LibsDisguises#173]
Hi! Just tried the plugin today. It -seem- to be working, but I can see my armor and weapons that I'm holding as well as the mob I'm supposed to be. Here is the errors:

http://pastebin.com/RYctds8J

**Comment by electronicboy** [comment]
https://github.com/dmulloy2/ProtocolLib/commit/7b61796506907a7be331ccd37ae54ef4c144bd26

**Comment by SonyUSA** [comment]
Thanks!
