### ISSUE TITLE
LlamaWatcher doesn't set Llama color or Carpet color

### ISSUE THREAD

**Issue by eccentricdevotion** [libraryaddict/LibsDisguises#179]
Using the code:

```
MobDisguise mobDisguise = new MobDisguise(DisguiseType.LLAMA);
LlamaWatcher llamaWatcher = mobDisguise.getWatcher();
llamaWatcher.setColor(Llama.Color.BROWN);
llamaWatcher.setCarpet(AnimalColor.GREEN);
DisguiseAPI.disguiseToAll(player, mobDisguise);
```

And using the command: `/d Llama setColor BROWN setCarpet GREEN`

Always gives me a GREY / PINK Llama disguise:

![llama_disguise](https://cloud.githubusercontent.com/assets/1841924/21175203/10b48c5e-c246-11e6-95ef-52b855b8b6e8.png)

CraftBukkit version git-Spigot-f950f8e-655d840 (MC: 1.11)
LibsDisguises v9.2.2 build 71

**Comment by libraryaddict** [comment]
Fixed

**Comment by eccentricdevotion** [comment]
Thank you
