### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kurimatzu** [libraryaddict/LibsDisguises#183]
Is it possible to disguise in an entity through NMS?

Example:

class MyEntity extends EntityZombie {
....
}

DisguiseAPI.disguiseToAll(entity, MyEntity.class);

You can?

Would be very good, you could create your own artificial intelligence, control sounds, etc.

**Comment by libraryaddict** [comment]
I don't get it. My plugin doesn't create custom creatures, it just lets you disguise.
