### ISSUE TITLE
Entity Disguises

### ISSUE THREAD

**Issue by DragonsAscent** [libraryaddict/LibsDisguises#184]
Upon using the "DisguiseEntity" feature in 1.11.2 in the released build on spigot, the entities just fall thought the ground and take damage until they die. This happens with every mob I've tried but doesnt happen with humans strangely enough. 

Steps to repo:
- Run the /disguisentity command then click a nearby entity
- Watch them fall through the floor and into the void.

At one point I managed to get this error [http://pastebin.com/Sq8Dkb7t](url) (Upon hitting them as they fell)

(I do have Protocollib (newest))

**Comment by libraryaddict** [comment]
Tested by disguising a sheep as a zombie, cannot replicate
