### ISSUE TITLE
Particle Effects with ViewSelfDisguise

### ISSUE THREAD

**Issue by xX1bumblebee1Xx** [libraryaddict/LibsDisguises#185]
Spigot: 1.11.2
LibsDisguises: 9.2.4
Protocollib: 4.2.1

My plugin Morph uses the LibsDisguises API to disguise player and provided abilities for the mobs. The problem is that when ViewSelfDisguises is enabled in protocollib potion effects do not get sent to the client. Example: Morphed as a bat is suppose to give night vision. The potion particles are shown and the server recognises the potion effect on the user but the client does not ignores it.

Particles that I have tested that don't work are: Nightvision, jump boost, and waterbreating
Is this something that can be fixed?

Video: http://sendvid.com/u8pvfqis (First part is what is happening, second part is what is suppose to happen. Start of part 2 is when I reload LibsDisguises)

**Comment by libraryaddict** [comment]
What code are you using?

**Comment by xX1bumblebee1Xx** [comment]
http://pastebin.com/403dc8SA The ones with //TODO over them don't work.

**Comment by libraryaddict** [comment]
Are you 100% that code is being applied, do debug. Such as System.out.println("Yes its being applied") next to where your bug is

**Comment by xX1bumblebee1Xx** [comment]
Yep I've done that, Someone else also helped me. All code does get ran, As you can see in the video for the bat there is particles, just no actual client side change.

**Comment by xX1bumblebee1Xx** [comment]
Any update on this?

**Comment by libraryaddict** [comment]
Oh forgot my reply didn't save.

I believe I know what the issue is, however a nice fix hasn't occurred to me yet. Btw, easy fix is to disable self disguises.

But I don't think this will be touched for weeks at least.

**Comment by xX1bumblebee1Xx** [comment]
Alright, Thanks anyway!

**Comment by libraryaddict** [comment]
Fixed
