### ISSUE TITLE
PlayerDisguise skin sometimes not appearing for the client (Again)

### ISSUE THREAD

**Issue by Arektor** [libraryaddict/LibsDisguises#188]
"Reopening" issue #151 as I couldn't reopen it properly (or I'm blind - which is probably the case :/ )

 
So, the issue is the same, using latest LibsDisguises build, latest ProtocolLib build, and latest Spigot build for 1.11.2.
However, it looks like it has been half fixed. Let me explain:

If I understood it right (which is probably not the case), the applied fix was to spawn the fake player first in front of the player, then teleport it to its legit location - which is working in most of the cases.
Now, what are the non-working cases?

1. If the player move its head right when the entity is spawned: The client will not render the skin, as it is no longer on screen when spawned - or just for a few moments but not enough to render it. This case happends a few times, but is not a major issue.
2. If the player has latency. This case happends alot more than the first one, and therefore is way more impacting. If the entity is spawned but teleported to its legit location right after, the skin will not have time to load because of player's latency (head moved and so).

  
I don't know if this can be fixed or not, but I hope it can.

**Comment by libraryaddict** [comment]
Lets see.

One idea is to constantly teleport the disguise every tick in front of the players eyes until X ticks pass

Another is to have a config option to lengthen the time until disguise is revealed

Another is to refuse to show the disguise until the player disguise has been sent, a keep alive packet sent and received while player disguise has remained in sight.

Another you can do already is to turn on the config option to keep all names in tab

Constantly teleporting the entity would be messy to implement, but doable. But it won't be guaranteed to work. Just higher chances.

Config option to lengthen the time would also work, but its not a clean implementation and is just avoiding a problem.

The last which is using a keep alive packet, while it would work. Its also using a method which isn't that clean, would add some slight overhead. For a 1/20 bug. It would be doing some math to ensure its in sight, a packet listener for a very common packet and its just a headache for me.

**Comment by ImranDoet** [comment]
Still occurs..

**Comment by jaylawl** [comment]
This has been an issue for MythicMobs users for years. I'm glad to have just discored this of you @libraryaddict : "Another you can do already is to turn on the config option to keep all names in tab". Which totally makes player disguises 100 % reliable for me. Although at the obvious price of messing up the tablist.
