### ISSUE TITLE
setArrowsSticking does not set any arrows sticking out of you.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#196]
Using LibsDisguise dev 95.

**Comment by libraryaddict** [comment]
Tested with what version of Minecraft using what command

**Comment by mibby** [comment]
Paper dev 1060 (Spigot 1.11.2)

```
/dis <mob> setArrowsSticking 50
```

It seems that arrowsSticking does not function for mobs but does on a player disguise. Can mobs not have arrows sticking out of them?

**Comment by libraryaddict** [comment]
Correct, it works on players only. Problem is, its an option for most entities.
