### ISSUE TITLE
Armor set disappear when disguise!

### ISSUE THREAD

**Issue by mrho225** [libraryaddict/LibsDisguises#198]
As the title, when players disguised as entities like zombie, pigman and so on... their armor will disappear. Thanks

**Comment by libraryaddict** [comment]
Please record a video or gif showing this

**Comment by mrho225** [comment]
Here is the gif file for the issue: [https://giphy.com/gifs/3ohzdRCCwkMdKQtaZW](url)

**Comment by libraryaddict** [comment]
Turn off RemoveArmor in your config

**Comment by mrho225** [comment]
I know about RemoveArmor option but after undisguised the armor should be return back. However, in this case or in the gif after undisguised, the armor set is gone and no return.
