### ISSUE TITLE
disguise and worlds

### ISSUE THREAD

**Issue by dwa1275** [libraryaddict/LibsDisguises#199]
I'm using multiverse core and I can desgise as anything in the default worlds but not in my creative or game world, not sure how to fix this

**Comment by libraryaddict** [comment]
Fix your permissions is my best guess given the information you have provided

**Comment by dwa1275** [comment]
even as op I cant use disguise in any other world

**Comment by libraryaddict** [comment]
Then given your lack of information, I cannot help you.

You fail to mention why you can't do it. What's stopping you.

**Comment by dwa1275** [comment]
that was just it, there was not a lot of info, I found the issue though, I found the issue now.
