### ISSUE TITLE
Re: Armor set disappear when disguise!

### ISSUE THREAD

**Issue by mrho225** [libraryaddict/LibsDisguises#200]
`Turn off RemoveArmor in your config`
I know about RemoveArmor option but after undisguised the armor should be return back. However, in this case or in the gif after undisguised, the armor set is gone and no return.

Here is the gif file for the issue: https://giphy.com/gifs/3ohzdRCCwkMdKQtaZW

**Comment by libraryaddict** [comment]
Stop clicking the armor slots when in creative, its telling the server that you removed the armor and set it to air.

**Comment by mrho225** [comment]
Not clicking at all. Just hover the mouse over armor slot so you can see they are gone.

**Comment by libraryaddict** [comment]
In the gif you show me, I can see the armor disappearing as you click on the slots.

**Comment by mrho225** [comment]
My steps were 
1. Put armor on
2. Hover the mouse over armor slots to show armor there
3. Disguise as Pigzombie
4. Hover armor slots again to show its disappeared 
5. Undisguise
6. Hover again to show you even after undisguised no armor is returned
No clicking at all.
Even just wear armor disguise then undisguise the armor wont be returned too.
Only happen in creative. In survival the armor is returned after undisguised

**Comment by libraryaddict** [comment]
Can you try replicate using a vanilla client
And without doing anything but disguise, undisguise.

**Comment by mrho225** [comment]
Here is the gif with vanilla client: [https://giphy.com/gifs/3ohzdIYKVPwaGsy2kM](https://giphy.com/gifs/3ohzdIYKVPwaGsy2kM)

The first time is find but the armor is disappeared at the second time.
I tested about 10 times with vanilla client and client with optifine, the bug happened randomly ,not always

**Comment by libraryaddict** [comment]
Ah, I see.

This may not be a problem I can fix though.

**Comment by mrho225** [comment]
Oh. A bit unsafe if it happen randomly. But anyway its alright!

**Comment by libraryaddict** [comment]
Cannot be fixed
