### ISSUE TITLE
DisguiseAPI lag

### ISSUE THREAD

**Issue by MClausz** [libraryaddict/LibsDisguises#202]
I'm making an infection minigame using your API, please take a look at these method:
http://pastebin.com/BPrTvWEV
But when there are a lot of players (25+ players in the same arena), the server freezes everytime a player get infected. The player disappear, server freeze for a while, and then reappear as a zombie. And because the player disappear before the lag occur, so technically the lag is caused by disguising the player. I tried to put them into an async thread but it throws an exception.
So do you have any recommention?

**Comment by libraryaddict** [comment]
Comment out the disguise code and see if the lag still happens.

updateAndHideNameTags sounds pretty dodgy.

**Comment by MClausz** [comment]
updateAndHideNameTags runs asynchronously and is thread safe
http://pastebin.com/gC9vMfWz

**Comment by libraryaddict** [comment]
Then the only other thing I can really suggest is to try something like https://github.com/sk89q/WarmRoast

**Comment by MClausz** [comment]
It looks like lag is caused by my code, the part after the infect method. Sorry for my mistake.
