### ISSUE TITLE
Build #104: works fine. Build #105: disguising as a player always shows as a steve/alex skin

### ISSUE THREAD

**Issue by malonnnn** [libraryaddict/LibsDisguises#203]
Issue
Build #104 works fine
Build #105: disguising as player does not work, shows steve/alex skin.

Environment
Ubuntu 14.04.5 x64

Java
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by libraryaddict** [comment]
Try latest build

**Comment by malonnnn** [comment]
Just tried the latest build, still no joy.

Build 104 still works

**Comment by libraryaddict** [comment]
Do you have contact mojang in your settings
Does skins work for non-disguises
Does 'Notch' skin work?

**Comment by malonnnn** [comment]
Thank you.

/disguise player Notch
does work in 106. It did not in 105.
My apologies for not testing that

/disguiseplayer libraryaddict player Herobrine setskin
{"id":"fdsaasdf","name":"malon","properties":[{"signature":"asdffdsa"}]}

does not work

**Comment by libraryaddict** [comment]
Confirmed fixed

**Comment by malonnnn** [comment]
Confirmed fixed!

Thank you!
