### ISSUE TITLE
setHideHeldItemFromSelf bugging

### ISSUE THREAD

**Issue by KnightConnie** [libraryaddict/LibsDisguises#204]
Hi!

When I put on a disguise and set setHideHeldItemFromSelf to true, it acts as if the item is not in my hand at all.
ex. Cutting down trees with 'invisible' iron axe, but goes as slow as an empty hand yet still acts as though it is being used (durability goes down)

Can you fix this? Thanks!

**Comment by libraryaddict** [comment]
Client sided bug, speed is set by the client not the server.

**Comment by KnightConnie** [comment]
But eating doesn't work, either.

**Comment by libraryaddict** [comment]
Still a client-sided thing.

You remove the held item from his hand and he's going to think he's holding nothing.
So therefore he will not think he's holding food, a bow, an axe or even a enderpearl.

If those items still work, the client won't expect it.
