### ISSUE TITLE
Make Lib'Disguises 8.6.7 better compatibile with Protocollib 4.2.0 for 1.8.x clients

### ISSUE THREAD

**Issue by xion87** [libraryaddict/LibsDisguises#205]
Hi, i would like a update of this version to make it compatible with latest protocollib for 1.8.8 (4.2.0), because if using it and using viewself disguise, all chunk around will disapear, i will but the premium version if you do it :)
Thank you

**Comment by Matocolotoe** [comment]
Just explain why it won't be added ? ...

**Comment by libraryaddict** [comment]
I forgot the original reasoning, but it was likely along the lines of "Not worth it in time invested"

Especially now.

**Comment by xion87** [comment]
@Matocolotoe  you can just use [IDisguise](https://www.spigotmc.org/resources/idisguise.5509/) since it still support 1.8

**Comment by Matocolotoe** [comment]
@xion87 Self morph view is not supported in this plugin
@libraryaddict "Not worth it ?" Explain me why so many servers use 1.8 and use cosmetic plugins on their server then

**Comment by xion87** [comment]
I think author added It recenly go to check it

**Comment by libraryaddict** [comment]
@Matocolotoe I don't play on 1.8, I don't think more than a few at most will be convinced to purchase premium for it and the time taken will not be small.

This plugin is open source and anyone can go back through the code and look at what has changed, can modify their own version and add the new features.

I'm rather busy nowadays, and I do value my free time.
