### ISSUE TITLE
Player names turn white in tab

### ISSUE THREAD

**Issue by FrankHeijden** [libraryaddict/LibsDisguises#206]
Heya,
when people disguise their name in tab turns white. I have installed the latest dev. version of lib's disguises, '#108' and I have ProtocolLib version 4.2.1-SNAPSHOT-b347 installed. I don't get any errors through the console. 

-Frank

**Comment by libraryaddict** [comment]
Hello, please confirm you are using the latest version of Lib's Disguises.

**Comment by FrankHeijden** [comment]
yes I am.

**Comment by FrankHeijden** [comment]
The name turns white when I am using the tags like 'setViewSelfDisguise' etc. When just using /d <disguise> the name stays normal.

**Comment by libraryaddict** [comment]
Can you confirm that players had a colored nametag prior to disguising, and can you give me your version of Lib's Disguises.

**Comment by FrankHeijden** [comment]
Yes they do have a colored name tag before the disguise, and I am using 'v9.3.0-SNAPSHOT #108'

**Comment by libraryaddict** [comment]
What command are you using, and what do you have for SelfDisguisesScoreboard in your config

**Comment by FrankHeijden** [comment]
'SelfDisguisesScoreboard: MODIFY_SCOREBOARD'
and the white name appears when I am using '/disguise bat setViewSelfDisguise'. It appears btw on every disguise with the option 'setViewSelfDisguise'.

**Comment by libraryaddict** [comment]
Can you give me your console log, I'm unable to replicate

**Comment by FrankHeijden** [comment]
Im only getting this: 
26.03 15:32:26 [Server] INFO FrankHeijden issued server command: /d bat setViewSelfDisguise

**Comment by libraryaddict** [comment]
Can you test the latest version

**Comment by FrankHeijden** [comment]
The name is still white with the latest version

**Comment by libraryaddict** [comment]
https://www.dropbox.com/s/it3sr8zbjwi3mep/LibsDisguises.jar?dl=0

I added debug

**Comment by FrankHeijden** [comment]
26.03 17:33:16 [Server] INFO Player is now in LD Pushing with prefix of '' (0)
26.03 17:33:16 [Server] INFO Player was previously in null
26.03 17:33:16 [Server] INFO FrankHeijden issued server command: /d bat setViewSelfDisguise

I get this

**Comment by libraryaddict** [comment]
Your player was never in a team. So where did your colored prefix come from?

**Comment by FrankHeijden** [comment]
I use zpermissions for prefixes in groups.

**Comment by libraryaddict** [comment]
I don't know how zpermissions does it, but this doesn't appear to be a Lib's Disguises bug.
Your problem lies in the interaction between the two plugins. Its very likely that they are using a protocol hack

**Comment by FrankHeijden** [comment]
Which permission plugins are compatible with libsdisguises? Im looking at LordPermissions atm, but i dont know if that one works.

**Comment by libraryaddict** [comment]
Its not that permission plugins are incompatible, its that they were using a weird way to set your nametag color.
You could try looking into another plugin for colored nametags while possibly keeping your old perms plugin

**Comment by FrankHeijden** [comment]
Oh for colored nametags am I using AnimatedNames from MaximvdW

**Comment by libraryaddict** [comment]
https://mvdwsoftware.freshdesk.com/support/home

Try asking about support, say the author of Lib's Disguises says that Lib's Disguises can't find a scoreboard team to modify so its creating its own.

**Comment by FrankHeijden** [comment]
Lol, 2 weeks response time
