### ISSUE TITLE
setskin not working

### ISSUE THREAD

**Issue by PhanaticD** [libraryaddict/LibsDisguises#207]
using build 113 using for example /d p Dinnerbone setskin PhanaticD I just appear as an alex or steve

**Comment by malonnnn** [comment]
I can confirm this

/disguise player <playername> is broken. 
setskin snapshots work fine, but the actual command seems broken.

LibsDisguises config.yml
`ContactMojangServers: true`

server.properties
`online-mode=true`

LibsDisguises:
Build #113

ProtocolLib:
Build #354

[http://i.imgur.com/x23wE60.png](url)

**Comment by FrankHeijden** [comment]
Same ^^

**Comment by libraryaddict** [comment]
Fixed

**Comment by FrankHeijden** [comment]
No, when i use /d bat setviewselfdisguise - I get kicked. with a lot of errors in console

kick message:
![schermafbeelding 2017-04-26 om 15 48 35](https://cloud.githubusercontent.com/assets/22407829/25437793/dbe1dff8-2a97-11e7-9fa3-8b0c31b8c1b9.png)

error in console:
https://pastebin.com/MtYQsTzm

**Comment by FrankHeijden** [comment]
and other players cant join ^

**Comment by libraryaddict** [comment]
Stop breaking things

**Comment by FrankHeijden** [comment]
XD btw, this error:
https://pastebin.com/TEYxcNcE

**Comment by libraryaddict** [comment]
Fixed

**Comment by malonnnn** [comment]
@libraryaddict 

You don't get enough thanks, so thank you again for your effort, it can't be overstated.

**Comment by FrankHeijden** [comment]
haha yep, such a great dev 👍
