### ISSUE TITLE
List of crashable disguises + ones that cause extreme lag

### ISSUE THREAD

**Issue by Metisuneatn** [libraryaddict/LibsDisguises#208]
Hey there! This on the latest version ofc, 1.11.2. Here is what we have found so far, I have tried to provide as much info as possible.

-With slime and magma cube you can set size from 1-127. Players cannot handle this number going past 50. They get such bad lag they cannot move. There is no way to limit this in the config.
-Setradius actually is an issue, you can become a giant 100 block cloud.
-Area effect cloud (and any particle above 49) crashes everyone around the player
-The elder guardian particle shows up on everyone... like everyone... if one person uses it. Like globally... doesnt even matter what world you are in

So far thats what we have found

**Comment by libraryaddict** [comment]
Slime fixed
SetRadius on AreaEffectCloud fixed
Elder guardian particle? What is that?
