### ISSUE TITLE
How to save mobdisguise ?

### ISSUE THREAD

**Issue by Max633** [libraryaddict/LibsDisguises#209]
Hii

I have disguise a rabbit, but he's it undisguise after a time....
My commands use : /disguiseentity villager baby

How to save an disguise please ?

Thank you

**Comment by libraryaddict** [comment]
There should be a config option for that

**Comment by Max633** [comment]
ok

# A option to choose how many seconds a DisguiseEntity command is valid for people to right click a entity to disguise it before expiring
DisguiseEntityExpire: 10

How to infinite ?

**Comment by Max633** [comment]
Where?

**Comment by libraryaddict** [comment]
KeepDisguises:
    EntityDespawn: false
    PlayerDeath: false
    PlayerLogout: false

**Comment by libraryaddict** [comment]
You want EntityDespawn. Its a memory leak though

**Comment by Max633** [comment]
Ok thank you.

You do not have a solution to optimize the memory leak though ?
