### ISSUE TITLE
/d player - and - 2nd name under nametag

### ISSUE THREAD

**Issue by FrankHeijden** [libraryaddict/LibsDisguises#210]
Heya,

could you please fix /d player? the skin does not load up at my server. I only get the default Alex or Steve skin.

Also, could you maybe add support for the 2nd line nametag when having the 'ShowNamesAboveDisguises' option in the config set to true? would be amazing :D Im currently using AnimatedNames for the 2nd line, displaying a health bar. 

Would love to see this in the next update,
Frank

**Comment by libraryaddict** [comment]
Please confim the 2nd thingy fixed

**Comment by libraryaddict** [comment]
Closed as there was no response

**Comment by FrankHeijden** [comment]
Oh im so sorry! Opened the email, but forgot to answer it later.

The 2nd thing does work, but only for /d player. Maybe add this feature also for when you're disguised as an animal/other living entity?

**Comment by libraryaddict** [comment]
You've tried the latest version?

**Comment by FrankHeijden** [comment]
Yep. version 116

**Comment by libraryaddict** [comment]
Ah, sorry but I've been an idiot.
I believe the second line above/below a player's name is for players only.
So unless I introduce a fake entity, this isn't doable.

**Comment by FrankHeijden** [comment]
Okay, thanks anyway! :D
