### ISSUE TITLE
Client crash in latest version

### ISSUE THREAD

**Issue by TNG-China** [libraryaddict/LibsDisguises#212]
When I disguises, My client will be crash and throw this error:
![qq 20170508212248](https://cloud.githubusercontent.com/assets/21065884/25808140/bddb0518-343b-11e7-9499-3dc0c76b9359.png)

I used Lib's Disguises: v.9.3.0-SNAPSHOT
Client: vanilla 1.11.2.

**Comment by libraryaddict** [comment]
Which disguise

**Comment by TNG-China** [comment]
@libraryaddict Lib's Disguises: v.9.3.0-SNAPSHOT

**Comment by TNG-China** [comment]
And use /d disguise any entity will crash.

**Comment by libraryaddict** [comment]
Can you try this
https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar
And tell me if the problem keeps happening.
Also you are not running a modded server, and you are not seeing any errors in console from Lib's DIsguises.

**Comment by TNG-China** [comment]
@libraryaddict 
I tried, The problem still exists. I running paperspigot 1.11.2 and no error in console from Lib's DIsguises.

**Comment by TNG-China** [comment]
@libraryaddict I tested each plugin with LibsDisguises in my server, I found reason is the GlowAPI(https://www.spigotmc.org/resources/api-glowapi-1-9-1-10.19422/), When use this plugin with LibsDisguises will make client crash. I don't know which plugin has bug.

**Comment by libraryaddict** [comment]
Its clearly the interactions between plugins that is causing the bug. Its not helped by GlowAPI refusing to use ProtocolLib.

How GlowAPI made this error happen, I'm not sure. But this isn't Lib's Disguises bug.
