### ISSUE TITLE
Players continue to be pushed when /dvs

### ISSUE THREAD

**Issue by insanesquirle** [libraryaddict/LibsDisguises#214]
I have set SelfDisguisesScoreboard: MODIFY_SCOREBOARD

Still does this when disabling the name above you when you're disguised.

The only thing I can think of is that I use Spigotboard instead of Scoreboardstats.  Could this be causing the issue?

**Comment by libraryaddict** [comment]
Does it work fine when you remove Spigotboard?

**Comment by insanesquirle** [comment]
Sorry to take so long to get back to you.  Spigotboard has been removed and the problem continues.

**Comment by libraryaddict** [comment]
Oh wait, are you saying /dvs is broken when they're already disguised?
Or that its broken all the time.

**Comment by insanesquirle** [comment]
At any point in time, if the player is viewing them self, they are pushed.  All the time.

**Comment by libraryaddict** [comment]
Closed as this isn't reproducible. If someone can reproduce it reliably, feel free to open a new issue.
