### ISSUE TITLE
LibsDisguises and HolographicDisplays conflicting and causing lag

### ISSUE THREAD

**Issue by xLoGiiKzZo** [libraryaddict/LibsDisguises#215]
Server version: PaperSpigot 1.11.2
LibsDisguises version: 9.3.0
HolographicDisplays version: 2.2.5

A week ago I updated my server from 1.8 to 1.11. Since then, LibsDisguises and HolographicDisplays have been conflicting and lagging my server. If I disable one of them, the lag is gone. But when both are enabled, the server starts to lag.

Here are some stacktraces from lag spikes: https://pastebin.com/raw/F1Ry58Je

**Comment by libraryaddict** [comment]
It looks like the author is using some weird way to do some of his stuff. I'd bring this up to him.

**Comment by xLoGiiKzZo** [comment]
Any possibility you could implement a fix for this? The HD developer won't. At least not for the next year or 2.
