### ISSUE TITLE
Server.broadcastMessage() accumulates lots of lag after a day or so of running, I think it's iterating over "fake players" - unsure if it's caused by libsdisguises, looking for advice

### ISSUE THREAD

**Issue by malonnnn** [libraryaddict/LibsDisguises#216]
It all started with this
http://forum.enginehub.org/threads/lag-from-broadcast.16958/

Long story short, I get lag when doing broadcastMessage() after my server has been running for a while. I think it's being caused by 1 of 2 plugins: LibsDisguises or Citizens2. Do you know of a way I can check what might be causing the broadcast lag for libsdisguises?

Thank you

**Comment by libraryaddict** [comment]
I don't believe I actually touch their perms or chat. So I doubt this is caused by Lib's Disguises

**Comment by malonnnn** [comment]
@libraryaddict 

Okay, perfect, that's all I needed to know, thank you
