### ISSUE TITLE
LibsDisguises sends bed chunks with skylights for end / nether

### ISSUE THREAD

**Issue by MylesIsCool** [libraryaddict/LibsDisguises#220]
This has been an issue with people using ViaVersion and we've put a workaround to ignore the extra bytes in ViaVersion but it's probably best to get this resolved at the source.

The spawn chunk is created with a normal world:
https://github.com/libraryaddict/LibsDisguises/blob/master/src/me/libraryaddict/disguise/utilities/DisguiseUtilities.java#L796

This is then sent when the user is possibly in the nether/end (Nether/End does not have skylights):
https://github.com/libraryaddict/LibsDisguises/blob/master/src/me/libraryaddict/disguise/utilities/DisguiseUtilities.java#L457

https://github.com/libraryaddict/LibsDisguises/blob/90de701eb52acc9ab56cce97eb0fe13b96360c03/src/me/libraryaddict/disguise/DisguiseListener.java#L285

(Wiki.vg source http://wiki.vg/Protocol#Chunk_Data)

The solution would either be to not send this in non-overworld or to have a spawnChunk for nether/end.

If you don't have time to implement this I can look into it myself, it doesn't affect clients at this point in time as vanilla ignores it though it might be worth fixing.

**Comment by libraryaddict** [comment]
I don't think I need the light stuff at all, so I removed that part.
