### ISSUE TITLE
Error LibsDisguises 9.4.0

### ISSUE THREAD

**Issue by FrankHeijden** [libraryaddict/LibsDisguises#221]
Heya,

got this error when enabling the plugin.
https://pastebin.com/5ibWtDTW

using latest 1.11.2 spigot build and latest 1.11.X build of protocollib.

**Comment by libraryaddict** [comment]
Isn't this a problem with plugman..

Does this error happen when starting up the server? Because /reload is not supported.

**Comment by FrankHeijden** [comment]
I see. Plugman was causing the issue. Sorry!
