### ISSUE TITLE
1.12 not working / loading.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#222]
Build - 122
https://pastebin.com/raw/2QBhejUk

Not starting on Spigot 1.12 - Build 1297

**Comment by libraryaddict** [comment]
Are you using spigot? I can't replicate.

**Comment by andrewkm** [comment]
Yes, Spigot Build 1297.

**Comment by andrewkm** [comment]
Tested again, this time just Spigot Build 1297 and your plugin on Build 122
Entire startup log:

https://pastebin.com/raw/4JrgH8ce

Definitely broken.

**Comment by libraryaddict** [comment]
Um. Are you using the dev build of ProtocolLib

**Comment by andrewkm** [comment]
#### [ProtocolLib](http://ci.shadowvolt.com/job/ProtocolLib/)
- 4.3.0-Dev-#371

**Comment by libraryaddict** [comment]
Try the latest dev build.

**Comment by andrewkm** [comment]
Libsdisguise Build 123

Just the plugin: https://pastebin.com/raw/Pm2ByBqW
With my entire setup: https://pastebin.com/raw/QwXyj8Tq

Still no good.

**Comment by libraryaddict** [comment]
Hmm, I'm starting to wonder if its your build of spigot now. You're getting an error at EntityFishingHook:38 however at that line its just "this.ah = true;"

**Comment by andrewkm** [comment]
Running build tools again from scratch to test once more.

**Comment by andrewkm** [comment]
Using:

{
	"name": "1297",
	"description": "Jenkins build 1297",
	"refs": {
		"BuildData": "ebd264edb506ff3e72e92dd16b1b68c46905972c",
		"Bukkit": "7b5ab33d620b1d19e00152b4a0d64c160712c3b7",
		"CraftBukkit": "bb4ae3b3b8a36a90a6ac29746c5b6cb1351fc772",
		"Spigot": "ede465d4b574dc539984f807d2d8b37a78da1858"
	},
	"toolsVersion": 47
}

Testing after build.

**Comment by andrewkm** [comment]
Spigot build log:
https://gist.githubusercontent.com/andrewkm/24f667e70b82370a1b61dc77a8a53085/raw/c1fda5cb28bd70692b0aa319460ed5a270ac0910/gistfile1.txt

Startup log with LibsDisguise Build 123:
https://pastebin.com/raw/vZy4GT3Y

Broken.

**Comment by libraryaddict** [comment]
org.bukkit.plugin.UnknownDependencyException: ProtocolLib

**Comment by andrewkm** [comment]
100% default spigot now too:
https://pastebin.com/raw/GC9xnBxb

Two other confirmed via Skype, same issue.

**Comment by andrewkm** [comment]
Oh one second. Didn't add protocollib, thanks good catch, trying again.

**Comment by andrewkm** [comment]
Added protocollib:

Same issue:

https://gist.githubusercontent.com/andrewkm/7828d4152e283c9df6d0a9409143145f/raw/6f2aee457e9df97fb726dc7398a8d37220d486af/gistfile1.txt

**Comment by andrewkm** [comment]
Okay, now with protocollib + libsdisguise on default spigot it works fine, confirmed with others via skype as well.

https://gist.github.com/andrewkm/8bcd3494b6e26e026d5131ca5fff3f7b

Now testing on my setup though...

**Comment by andrewkm** [comment]
Ok so on total default spigot it works:
https://gist.github.com/andrewkm/8bcd3494b6e26e026d5131ca5fff3f7b

On my setup with JUST procotollib and libsdisguise it's still broken:
https://gist.github.com/andrewkm/5f796fb647ca1ec73145afa873667b74

I'm starting to think it's something in my world file... ???

**Comment by libraryaddict** [comment]
I sent you messages on spigotmc

**Comment by andrewkm** [comment]
Found the cause. Pmed on Spigot.

**Comment by libraryaddict** [comment]
Looks like my decompiler has a problem with the line numbers.

Also, do me a favor and see if you can join your server without my plugin, and with a fresh install with just that spigot.yml.

**Comment by libraryaddict** [comment]
Closed as its not a Lib's Disguises bug
