### ISSUE TITLE
WorldGuard region compatibility to disable disguises.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#226]
Would it be possible to implement WorldGuard support or a hook so you can list regions where disguising is not allowed? As in if a player entered a specified region disguised, they get undisguised?

**Comment by libraryaddict** [comment]
Not adding support for other plugins, bugfixes, improvements and so on. Sure. Outright api hooks into other plugins? No thanks.
Either the plugin hooks into mine, or it doesn't.

**Comment by mibby** [comment]
Well I don't think WorldGuard will add specific hooks to LibsDisguise, so that is a bit unfortunate. I know quite a few pet plugins that hook into worldguard to disable pets that enter regions, just wanted a way to disable disguises as well. If it isn't something that is going to be implemented, bit unfortunate but understandable I suppose.
