### ISSUE TITLE
disguises are getting blown when that shouldn't happen

### ISSUE THREAD

**Issue by chillerkraft** [libraryaddict/LibsDisguises#227]
here's how my config entries look. lmk anything else you need
```
# This prevents disguised players from being targeted by monsters.
# This doesn't prevent their targeting you if already targeting when disguised
# They will just ignore you unless provoked.
MonstersIgnoreDisguises: true

# Sigh. People are going to want this.
# So lets make your disguise blown if you are attacked..
# Works only for disguised players when attacked by a entity (arrow, monster. etc)
# This will blow all disguises he has on him
BlowDisguises: false
BlownDisguiseMessage: '&cYour disguise was blown!'
```

**Comment by chillerkraft** [comment]
made it look better in edit

**Comment by libraryaddict** [comment]
Can I have an example

**Comment by chillerkraft** [comment]
when i attack a mob, it says your disguise has been blown and removes my disguise

**Comment by libraryaddict** [comment]
Ah my bad, looks like I badly explained it in the config. I'll add another option

**Comment by libraryaddict** [comment]
Download the latest dev build to have this, you may need to regenerate your config

**Comment by chillerkraft** [comment]
this still isn't working
```
# This prevents disguised players from being targeted by monsters.
# This doesn't prevent their targeting you if already targeting when disguised
# They will just ignore you unless provoked.
MonstersIgnoreDisguises: true

# This works only for players, disguised monsters and the like will not be undisguised
# Should the player's disguises be removed if he attacks something?
BlowDisguisesWhenAttacking: false
# Should the player's disguises be removed if he's attacked by something?
BlowDisguisesWhenAttacked: false
```
when a player attacks a mob, it removes the players disguise

**Comment by libraryaddict** [comment]
Are you 100% that there are no plugins conflicting? And that you're using the latest development build at https://ci.md-5.net/job/LibsDisguises/

**Comment by chillerkraft** [comment]
i will test it on a test server with just libsdisguises. yes, using the latest dev build with the fix you made (130)

**Comment by chillerkraft** [comment]
yes there's a conflicting plugin
Plugins (52): ChatColor2, AntiCreeper, ErrorSink, PlaceholderAPI, WorldResourcepacks, ConsoleSpamFix, AdvancedLogger, AntiFire, Note, AsyncWorldEditInjector, LuckPerms, dynmap, OpenInv, ChatControl, CrackShot, WorldBorder, SmartSignEditor, ProtocolLib, Multiverse-Core, LibsDisguises, AdvancedPortals, MVdWPlaceholderAPI, NoFireworkDamage, AsyncWorldEdit, mcMMO, Vault, ChatItem, WowSuchCleaner, WorldEdit, Essentials, CompatNoCheatPlus, mcMMOAction, McMMOExtras, NoCheatPlus, DragonSlayer, OnTime, TreeAssist, WorldGuard, EssentialsGeoIP, EssentialsSpawn, TitleManager, RandomCoords, InventoryFull, ConditionalPerms, MobHunting, CrackShotPlus, Residence, CraftBook, ChestShop, AuthMe, LockettePro, ChestShopNotifier

**Comment by libraryaddict** [comment]
I don't know what plugin would be causing that. I don't look at what plugins use my plugin, and how.

My best guess is to ask if copying the config from the test server to your other server fixes the problem. If it does, great! If it doesn't, well. Try posting in spigot forums asking which plugin?

Cheers, and good luck.

**Comment by chillerkraft** [comment]
yea copying the config didnt work. ill try adding plugins to the test server until it breaks

**Comment by chillerkraft** [comment]
thankyou for your time
