### ISSUE TITLE
Rabbit does not have a type/variant

### ISSUE THREAD

**Issue by PugaBear** [libraryaddict/LibsDisguises#228]
![image](https://user-images.githubusercontent.com/12417961/27269513-36fcd0dc-547d-11e7-85e9-9c65a4841e54.png)

![image](https://user-images.githubusercontent.com/12417961/27269491-fcef34de-547c-11e7-851e-8af0dfe1a35d.png)

**Comment by libraryaddict** [comment]
Fixed
