### ISSUE TITLE
/disguise suggests names with underscores but doesn't accept them

### ISSUE THREAD

**Issue by Pokechu22** [libraryaddict/LibsDisguises#232]
Hello!  I've been looking though this plugin to fix some issues unrelated to this one, and I just noticed a minor bug, present in the most recent version of the source (788bbf4) and probably in the latest release too: the `/disguise` command suggests disguise names with underscores, but requires a non-underscore variant to type it.

To reproduce:

1. Type `/disguise `.
2. Type `Wither`
3. Press <kbd>Tab</kbd> twice to select `Wither_Skeleton`
4. Run the command.  You will receive a message that "Error! The disguise Wither_Skeleton doesn't exist!"
5. Run `/disguise WitherSkeleton` instead, and note that it is successful.

This could be fixed either by trimming underscores, or by fixing the list that tab completion uses.

**Comment by libraryaddict** [comment]
Fixed
