### ISSUE TITLE
setItemStack() not working on FlagWatcher on Dev 9.4.0

### ISSUE THREAD

**Issue by herbert3211** [libraryaddict/LibsDisguises#233]
Hi, I'm using the latest dev build, and I can't change the equipment of the flagwatcher.
`{
                        ItemStack i = new ItemStack(Material.LEATHER_CHESTPLATE);
                        LeatherArmorMeta m = (LeatherArmorMeta) i.getItemMeta();
                        m.setColor(Color.WHITE);
                        i.setItemMeta(m);
                        fw.setItemStack(EquipmentSlot.CHEST, i);
                    }`
However, this is the result:
![image](https://user-images.githubusercontent.com/29687997/27515426-0ed73a5e-59a3-11e7-9651-cde0d58fa906.png)
I'm using 1.12.
Thanks.

**Comment by libraryaddict** [comment]
Can you please verify that your code is actually being called, I can't replicate.

If fw.setBurning(true) doesn't work, then your code is obviously not going to work.
I did change EquipmentSlot in the snapshot builds, however after testing myself I can still set the chestplate just fine.

**Comment by libraryaddict** [comment]
If you are sure that you are calling that code. Can you please tell me which build of Lib's Disguises you are compiling from?

**Comment by herbert3211** [comment]
![image](https://user-images.githubusercontent.com/29687997/27539032-17f8bde6-5a7b-11e7-8b5f-e4cffba3a2a1.png)
Burn does work, and I'm using 9.4.0 snapshot.

Also, when I used LibsDisguise for 1.8 back then, it worked.
Here's the whole code, if needed: https://pastebin.com/9YRvmkeu

**Comment by libraryaddict** [comment]
Same issue as #235 but #235 is explained better.
