### ISSUE TITLE
Empty Packet error BungeeCord

### ISSUE THREAD

**Issue by FrankHeijden** [libraryaddict/LibsDisguises#240]
Heya,

Libs Disguises is causing an error on my server with BungeeCord; I tested a plugin because it was not working and i detected when clicking in the GUI of the plugin (ProdigyGadget DIAMOND) would you get kicked from the server with this error in the bungeecord console:

`05.07 18:16:59 [Server] INFO io.netty.handler.codec.CorruptedFrameException: Empty Packet!
05.07 18:16:59 [Server] INFO at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:36)
05.07 18:16:59 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
05.07 18:16:59 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
05.07 18:16:59 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
05.07 18:16:59 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
05.07 18:16:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
05.07 18:16:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
05.07 18:16:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
05.07 18:16:59 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
05.07 18:16:59 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
05.07 18:16:59 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
05.07 18:16:59 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
05.07 18:16:59 [Server] INFO at java.lang.Thread.run(Thread.java:748)`

I hope this is fixable, as i really want to use the 3D menu of this plugin 👍 

Thanks in advance,
Frank

**Comment by libraryaddict** [comment]
How is this lib disguises related or issue

**Comment by FrankHeijden** [comment]
Ehm the author said i must contact the dev of the plugin which gives the error :x

**Comment by libraryaddict** [comment]
Libs disguises does not have a gui
