### ISSUE TITLE
Disguising permanently deletes equipped armor.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#241]
LibsDisguise dev 144

```
# For self disguises, they need to have the armor and the held item removed
# Else they see floating armor, floating held items.
# This turns the items invisible in the disguised players inventory. It does not actually remove them!
# Be warned that in creative this can actually delete the item from the inventory due to a weird bug
RemoveArmor: true
RemoveHeldItem: false
```

When players disguise while having equipped armor on, it permanently deletes the armor pieces when they undisguise. Tested with an equipped named elytra and colored leather named boots. Player disguised as a squid.

**Comment by libraryaddict** [comment]
Did they disguise in creative mode?
Does the bug happen in survival

**Comment by mibby** [comment]
Person tested in both creative and survival. Happened to lose armor in both gamemodes.

**Comment by libraryaddict** [comment]
Please attach video.
I cannot reproduce.
Additionally, does the armor appear if you rejoin the server?

**Comment by libraryaddict** [comment]
Closed due to lack of response

**Comment by mibby** [comment]
Did you even test or are you just saying that? It is reproducible 100% of the time for me.

LibsDisguise dev 152
ProtocolLib dev 378
Spigot 1.12

https://www.dropbox.com/s/v3fhnyet7zjpns8/2017-07-10%2015-58-59.mkv?dl=0

* Equipped a named elytra.
* Disguised as a pig.
* Undisguised.
* Elytra is deleted.


> Additionally, does the armor appear if you rejoin the server?

No it does not.

**Comment by PugaBear** [comment]
I recall hearing about this happening in creative. Will attempt to look at it later

**Comment by libraryaddict** [comment]
@mibby can you reproduce this issue in Survival Mode. Creative is a known problem.

**Comment by mibby** [comment]
I do not seem to be able to reproduce this in survival, however I do have multiple players claim they have lost armor when disguising in survival. I personally can only reproduce this in creative.
