### ISSUE TITLE
Changing the icon in tab when disguised as a player (low priority)

### ISSUE THREAD

**Issue by malonnnn** [libraryaddict/LibsDisguises#242]
Current system:
Disguising as Notch, pressing tab, and it displays [Malon's Head] Notch

Would like:
Disguising as Notch, pressing tab, and it displays [Notch's Head] Notch

This feature request is low priority, whenever you have time is fine

**Comment by libraryaddict** [comment]
http://i.imgur.com/uCzrpZF.png

Can't reproduce
