### ISSUE TITLE
Incompatibility with ProdigyGadget Diamond

### ISSUE THREAD

**Issue by FrankHeijden** [libraryaddict/LibsDisguises#245]
Heya,

Im having an issue with Libs disguises, when ever I put libs disguises on my test server it wont open the 3D menu of ProdigyGadget anymore. This is only on a bungeecord instance, and wont appear on just a spigot server. I tested it on the latest bungeecord build (#1250) and on the latest spigot 1.12.
the spigot server has only 3 plugins installed: Protocollib (latest dev build), Lib's Disguises (latest dev build) and ProfigyGadget Diamond (latest release, no dev builds)

When the player opens the menu of ProdigyGadget and clicks on an item; this error pops up in the console:
https://hastebin.com/anobugavab.lua

I reported this to the owner of ProdigyGadget and he told me this:
"tell to library addict that he should see that code: https://hastebin.com/momoyifeho.cs"

Hope this helps, really annoying bug

**Comment by libraryaddict** [comment]
Can you test on latest the latest dev build

**Comment by FrankHeijden** [comment]
didnt work for me.

**Comment by libraryaddict** [comment]
Hey again.

I wasn't able to replicate this on my server. Are you able to create a new fresh server and see if you can replicate the problem?

And if so, the steps you took to replicate this.

**Comment by libraryaddict** [comment]
Hello. I've just tested with minimum requirement with all latest plugin, and found issue persists. This is how to replicate issue.
1. bungeecord #1252 ( maybe this is bungeecord issue ) make sure it is bungeecord connected.
- dev server ( where prodigy gadget is put in ) , spigot 1.11.2
- lobby server ( obvious I think ) , spigot 1.11.2
bungeecord has viaversion 1.2 and viabackward 2.1.1
2. put protocolLib 4.3.0 , libdisguise #170 , prodigyGadget 2.49.1 , which are all latest I could find in 2017 August 7th in dev server.
3. start server, and get into dev server
4. open menu via /pg open. 3d selector will be shown.
5. click any of them
6. you'll be redirected to lobby server with red message "The server you were previously on went down, you have been connected to a fallback server"
7. of course dev server is running fine.

**Comment by libraryaddict** [comment]
However I was able to replicate this bug while Lib's Disguises was not in the server, strangely it seems that Lib's Disguises makes the bug more replicable.

**Comment by FrankHeijden** [comment]
Its very weird, because all my servers are running 1.12.1 right now. Ill test again on a testserver in a few minutes.

**Comment by libraryaddict** [comment]
Sorry those steps was not meant for you.

**Comment by FrankHeijden** [comment]
no problem, this is what i did to reproduce the problem:

Downloaded latest bungeecord build (atm this one): https://ci.md-5.net/job/BungeeCord/1253/
Downloaded latest spigot build (atm this one): http://yivesmirror.com/grab/spigot/spigot-1.12.1-R0.1-SNAPSHOT-b1390.jar
Downloaded protocollib 4.3.0 release: http://ci.dmulloy2.net/job/ProtocolLib/373/
Downloaded libs disguises (latest atm this one): https://ci.md-5.net/job/LibsDisguises/170/
Downloaded latest prodigygadget v2.49.1

I setup bungeecord, changed in config.yml 'ip_forward: true' linked it to my spigot server (in my case 'localhost:25580') and gave myself the admin rank (replaced md_5 by me, FrankHeijden)

I have setup the spigot server, set 'EULA=true' and set in server.properties 'online-mode=false'. I dumped Protocollib and prodigygadget into the plugins folder and restarted the server.

When i join right now, i can perfectly use prodigygadget (after i OPped myself) without any kicks.

-----

I stopped the spigot server, dropped libsdisguises into the plugins folder of spigot and started the server again.

When i join right now and use the gadget menu and click on an item there, i will get kicked with this error client-side: [![Screenshot from Gyazo](https://gyazo.com/76423db777fc1f89ecabbaa3b3e613bb/raw)](https://gyazo.com/76423db777fc1f89ecabbaa3b3e613bb)
Spigot side, theres just a message: https://hastebin.com/dinuquhohu.md

bungeecord, it gets interesting: https://hastebin.com/nojuwinawe.lua

**Comment by libraryaddict** [comment]
Closed as it has been fixed on their end.
