### ISSUE TITLE
Disguising makes names in tab go white

### ISSUE THREAD

**Issue by YepImRobbie** [libraryaddict/LibsDisguises#247]
http://i.imgur.com/acdQGxo.png

All of the users with white names had disguised. Why is Libs screwing with tab names?

Thanks.

**Comment by libraryaddict** [comment]
Check your config option, what did you set SelfDisguisesScoreboard to

**Comment by YepImRobbie** [comment]
http://i.imgur.com/9Uxbz1H.png That setting is not in my config. :(
