### ISSUE TITLE
Self disguises always spawn facing south.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#249]
When you disguise as an entity, it always spawns facing south until you move to update it. Would it be possible to spawn the entity facing the same direction you are facing when you disguise?

**Comment by libraryaddict** [comment]
Try the latest build

**Comment by mibby** [comment]
Looking north and disguising as a pig, the pig now looks in the direction north but the body is angled east/west depending on what angle you are facing north. Same goes for skeletons. The body readjusts to the facing direction after a moment, but it is something to note. The commit does fix the mob facing the direction you disguise though.

**Comment by libraryaddict** [comment]
Try latest build

**Comment by mibby** [comment]
Seems to be working now, thanks.
