### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by mikroskeem** [libraryaddict/LibsDisguises#250]
I am not sure what is causing this, running clean Paper installation and unconfigured LibsDisguises

Stack trace: https://paste.wut.ee/evenumuquy

_[Also if you need full server log](https://paste.wut.ee/ehozowakic)_

**Comment by libraryaddict** [comment]
Does this occur everytime you shut down Paper?

**Comment by mikroskeem** [comment]
It seems to happen when disguises are going to be saved. Something in disguise serializer causes recursion, I was too sleepy yesterday and couldn't figure out what was the exact cause of it.

**Comment by mikroskeem** [comment]
I found out that this happens when I disguise Citizens NPC

**Comment by libraryaddict** [comment]
I'm 90% that my latest build doesn't fix it, but you mind trying it?

Alternatively, is it possible for you to try replicate this using spigot.

**Comment by mikroskeem** [comment]
Issue is still present

**Comment by libraryaddict** [comment]
Are you able to try replicate this using spigot?

**Comment by mikroskeem** [comment]
Yes.

**Comment by libraryaddict** [comment]
Well I can't replicate this issue on my side, nor can I actually determine what's causing it.

However, I was saving disguises even if it wasn't enabled in the config. So if you didn't enable it, then you will no longer suffer this issue.

Going to leave this issue open as its not fixed.
