### ISSUE TITLE
Several Errors.

### ISSUE THREAD

**Issue by Scorpionvssub** [libraryaddict/LibsDisguises#253]
Players that use the disguises at times end up stuck in a no pushing mode that the disguises tent to have.
Like i was a wolf i couldn't push entitiys as myuself i could a member used it couldnt push as a human(non disguised) after being disguised as a polar bear.

Some disguises push the player aswell for some reason making them walk off with no reason

**Comment by libraryaddict** [comment]
Is this using the dev builds?

**Comment by libraryaddict** [comment]
Closed due to lack of response

**Comment by Scorpionvssub** [comment]
sorry didnt see the notice, im using the premium spigot version

**Comment by Scorpionvssub** [comment]
When i turn in something like a wolf or anything i noticed it turns a setting to false for pushing(found out that can be turned off) and figured it out the plugin does this after extensive testing.
I just turned into a wolf and it happend, couldn''t push.

Now i know how the pushing comes to be, the disguise you are is ofcourse an entity but if the player is able to push he gets pushed by the entity he is therefor never stopping to move

**Comment by libraryaddict** [comment]
Try the dev builds and tell me if the problem persists

**Comment by Scorpionvssub** [comment]
Downloaded this build(not sure if its accually your LATEST dev build number 170 https://ci.md-5.net/job/LibsDisguises/lastBuild/ but happens with this 1 aswell

What i do to test:

1. I push any animal to see if i can push(Yes i can)
2. I turn into any disguise this case a wolf(/d wolf) not standing in anything..
3. I walk into the animal i pushed just before i switched to a disguise.(I walk through it)
4. I walk out of the animal and undis myself
5. I walk back to check on that same animal if i can push them and find i cant push

**Comment by libraryaddict** [comment]
Ah, I see. I misunderstood your problem.

In your disguise config, change MODIFY_SCOREBOARD to CREATE_SCOREBOARD
