### ISSUE TITLE
/disguisehelp causing spam.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#254]
Libsdisguise B166
Spigot B1373
ProtocolLib B373

If you need more information about my environment please let me know.

Image: 

![image](https://user-images.githubusercontent.com/1013725/28971279-5fb6285c-78f9-11e7-9f7f-0c79d91964aa.png)

Bug: https://www.ecocitycraft.com/forum/threads/spam-via-disguisehelp.168388/

**Comment by libraryaddict** [comment]
Fixed
