### ISSUE TITLE
Teleport possibly deletes player object, causes big issues.

### ISSUE THREAD

**Issue by Cryptite** [libraryaddict/LibsDisguises#259]
Suffice it to say many things go awry when this happens, and I'm not entirely sure what causes it.

All the same, this is the stack trace: https://hastebin.com/eqijahoqam.vbs

**Comment by libraryaddict** [comment]
at com.n9works.bukkit.TheArtifact.teleportAsync(TheArtifact.java:4535) ~[?:?]

**Comment by Cryptite** [comment]
Admittedly that method is _called_ teleportAsync, but I had reverted the code within back to a vanilla teleport, so that's not the issue:

`    public void teleportAsync(Player player, Location to, Consumer<Player> done) {
        if (player == null) return;

        player.teleport(to);

        if (done != null)
            done.accept(player);

//        to.getWorld().getChunkAtAsync(to, (c) -> {
//            if (player != null) {
//                player.teleport(to);
//                if (done != null) {
//                    done.accept(player);
//                }
//            }
//        });
    }`

**Comment by Cryptite** [comment]
Also updated the OP with a bigger stack trace (or rather, both)

**Comment by libraryaddict** [comment]
It sounds like a ProtocolLib issue as well.
