### ISSUE TITLE
Enderdragon disguise motion is too fast.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#26]
@libraryaddict 

When disguising as an enderdragon, the head bobbing and wing flapping occur at accelerated speeds. The dragon almost looks as if it is spazzing out, as it is moving at hyper speed, 3x faster than normal.

Is there any way to slow down the enderdragon animations to be closer towards the vanilla enderdragon movement?

LibsDisguise dev 246.

**Comment by NavidK0** [comment]
Animations are client side and relative to client speed, not really fixable without slowing down the entity.
