### ISSUE TITLE
Feature Suggestion - Action bar notification showing you that you are still disguised.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#260]
@libraryaddict Would it be possible to have a sub-bar action bar notification for when you are disguised, constantly showing the text 'You are disguised' so players know they are still disguised when ViewSelfDisguises is disabled? As viewing an entity within you sucks visually for players on most disguises. 

Having a constant text/color configurable notification above the hot-bar when disguised would be nice to have.

**Comment by CitrusFruit** [comment]
Agreed, would come in handy.

**Comment by mibby** [comment]
@libraryaddict Is this something that could ever be reconsidered? If even a premium feature instead?
