### ISSUE TITLE
Crashing the server on startup on java 9 on spigot

### ISSUE THREAD

**Issue by Justsnoopy30** [libraryaddict/LibsDisguises#262]
Every time on java 9 on spigot when the server starts up and enables libsdisguises, it crashes.

**Comment by libraryaddict** [comment]
Hi, can you leave an error log?

**Comment by Justsnoopy30** [comment]
Ok.

**Comment by Justsnoopy30** [comment]
Oh nevermind, it seems to be working now, I redownloaded it and it worked. Must of been a bad download.
