### ISSUE TITLE
View disguise not working

### ISSUE THREAD

**Issue by Fargus5** [libraryaddict/LibsDisguises#263]
Dear

When you will fix the viewing of yourself disguise working? 
In 1.12 it don't work

**Comment by libraryaddict** [comment]
Did you try running it with a fresh config and no other plugins?

**Comment by Fargus5** [comment]
Let me check.
I have completely unistalled my actually libsdisguises and I installed the latest build #173 (7 oct. 2017)
I believe that config automatically update with new version as any other plugin.
Let me try this new one and I will let you know this evening

**Comment by Fargus5** [comment]
Hi, I checked
I can confirm that self view disguise doesn't work.
Actually when u are disguise... after some time the mob will freeze and u can move away letiting the disguise stay freezed.

Try it yourself

**Comment by libraryaddict** [comment]
I cannot reproduce.

What disguise are you using.
What are you doing ingame.
How long does it take?

**Comment by Fargus5** [comment]
Are u serius? I see that in all the servers this problem appears and noone told u?

**Comment by libraryaddict** [comment]
You are the second reporter, but the first reporter as I could not reproduce I assumed it was a local issue to him.

If I can't reproduce the issue, then as far as I'm concerned its not a real issue.

What spigot are you using.
Are you using the latest builds of ProtocolLib and Lib's Disguises
Are you staying still
What disguise are you using
Does the issue happen in a newly generated world
How long does it take

Does the issue happen if

You download Lib's Disguises and ProtocolLib
Create a new server using a newly generated Spigot.jar from BuildTools
Then join and disguise as a sheep while only looking around.

Does the issue happen then?

**Comment by Fargus5** [comment]
I made a video, let me give it to u
Yes the issue happen in many servers.

**Comment by Fargus5** [comment]
https://www.mediafire.com/file/u0mc1tq41tf6gk1/2017-12-03%2021-16-40.mp4

**Comment by libraryaddict** [comment]
Yes, I see you have an issue in that video.

However this doesn't help me replicate the problem.

**Comment by libraryaddict** [comment]
@Fargus5 if you want to help me debug this further, then until I can reproduce it I can only work with what I'm given.

If you're willing, this will be spammy but try `packet add play server`

For advanced but spammier logs, `packet add play server true`

Then you just send me the logs from where the mob stopped moving.

From there I'd probably narrow it down further, but still spammy. Unless I can reproduce it, I don't have a lot of options.

The key here is to get the exact time the mob stops moving in the debug.

**Comment by Fargus5** [comment]
Listen... with all respect I'm reporting to you a bug... I'm not a developer and I'm using libsdisguise without viewig my self disguised as everyone, because this problem is reproduced in many servers.
I don't have any errors on console, I cannot give u more than a video.

I'm one of the buyers of libsdisguise, but since always I never used this plugin viewing myself disguise because this feature has never worked.

I spoken with my developer, he suggested to me to report this to you, But he and me, we cannot explain why there is this problem.

If you want I can invite you to join my server and give to you access to the console, but I cannot help you more than a video.

You are the developer that has made this api, and I find not normal that u are not able to replicate the problem and also that u have only 2 users that reported it to you.

In MC Italia community I can absolutely confirm to you that at least 90% of the owners use libsdisguise with the view self disguise disabled.

If you cannot do anything, we will continue to use this like this, I wanted just to report it to your attention.

Thanks for your work
