### ISSUE TITLE
Villager professions not working correctly

### ISSUE THREAD

**Issue by AlHollandiyah** [libraryaddict/LibsDisguises#264]
The villager professions are currently not working correctly for me. I will place a list here of what I set and what I actually get. The list is taken from /disguisehelp villagerprofession:

TYPING => GETTING
Normal => Farmer
Farmer => Librarian
Librarian => Priest
Priest => Blacksmith
Blacksmith => Butcher
Butcher => Nitwit
Nitwit => Farmer
Husk => Farmer

I am using Protocol Lib v4.3.0 and Libs Disguises v9.5.0 on Spigot 1.12.2. If you need any other info to help find this bug please let me know!

**Comment by libraryaddict** [comment]
Fixed
