### ISSUE TITLE
Disguised Horses cannot be controlled.

### ISSUE THREAD

**Issue by Chiaro-Amos** [libraryaddict/LibsDisguises#265]
I've noticed that if a horse is disguised into another mob, it can still be mounted but takes on the properties of its disguise. If changed to a sheep, cow, etc, it cannot be controlled, even if the horse was tamed and saddled before being disguised. 

Is there a configuration option or some other way that I can fix this? Or can it be implemented so horses can still be controlled while disguised?

**Comment by libraryaddict** [comment]
Sorry but this is a Mojang thing, while a non-horse is being ridden it doesn't send the steering packets.
