### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by Mufundu** [libraryaddict/LibsDisguises#267]
I am running Libs Disguises on a 1.12.2 server and using Uperms to give player permissions to disguises.  When I give them libsdiguises.disguise.chicken (fore xample), I get an error that says they do not have permission to perform this command. When I give them the permission libdsdisguises.* they can use the permission just fine (as well as every permission in the plugin) is there another permission node that they need in order to just use the disguise permission.  I am sure I am just missing something here.  Thanks for your help.

Purchased the plugin under the username Guy420710. Thanks

**Comment by libraryaddict** [comment]
It sounds like you didn't spell the permissions correctly

**Comment by Mufundu** [comment]
Alright, I went and double checked the spelling and it seems correct.  I added the libsdisguises.seecmd.disguise and libsdisguises.seecmd.undisguise.  This allowed the users to have the disguises when I added libsdisguises.disguise.*  However when I used a single permission node like libsdisguises.disguise.chicken  they were unable to use the disguise. Any thoughts on what might be causing the issue?

**Comment by libraryaddict** [comment]
Is it possible for you to test if the problem persists with another permissions plugin?

**Comment by Mufundu** [comment]
We have identified the problem. It is being blocked by no cheat plus. Are you aware of any issues with that plugin?

**Comment by Mufundu** [comment]
We deleted NoCheatPlus and the problem persists. All of our servers use Uperms and we don't have a way to use another plugin like PermissionsEX. Have you ever worked with or tested this plugin against Uperms?
Again, the libsdisguises.disguise.* gives all players all of the disguises, but libsdisguises.disguise.chicken will not give any players the chicken disguise.  Thanks again for your help

**Comment by libraryaddict** [comment]
I can't really help with permissions problems if its caused by a permissions plugin sorry.

It would be caused by the way I handle permissions, but the way I handle permissions is almost required due to the way I handle disguises and options.
