### ISSUE TITLE
Tab list bug

### ISSUE THREAD

**Issue by Commodore64x** [libraryaddict/LibsDisguises#269]
I've noticed that if you do /d {disguise} setHidePlayer, your essentials nickname including colors is then set as your display name in tab. Considering setHidePlayer is meant to hide you from tab is this intentional or a bug?

**Comment by Commodore64x** [comment]
@libraryaddict Would you know anything about this?

**Comment by libraryaddict** [comment]
You know, I'm not too sure why I use the displayname..

Does the bug disappear if you don't use a nickname?

**Comment by ItzRaiin94** [comment]
We had an influx of players doing  /d {disguise} setHidePlayer then /u so, it doesn't go back to normal afterwards.

**Comment by libraryaddict** [comment]
Is this still an issue?
