### ISSUE TITLE
Profession for zombie still doesn't work

### ISSUE THREAD

**Issue by Feerko** [libraryaddict/LibsDisguises#270]
https://github.com/libraryaddict/LibsDisguises/issues/266

I compiled your plugin from last commit and still doesn't work.
<img width="647" alt="zrzut ekranu 2017-12-22 o 16 34 13" src="https://user-images.githubusercontent.com/16988054/34303520-04cec6a0-e736-11e7-8898-1e7293759286.png">

**Comment by libraryaddict** [comment]
Fixed with latest commit
