### ISSUE TITLE
Zombie Profession

### ISSUE THREAD

**Issue by Feerko** [libraryaddict/LibsDisguises#271]
Hello, there is still issue with zombie profession.

when i type: /dhelp ZombieProfession i get this:
<img width="432" alt="zrzut ekranu 2017-12-23 o 11 16 52" src="https://user-images.githubusercontent.com/16988054/34318897-e260eb0a-e7d2-11e7-8aa5-36a46fb48092.png">

i just want set players to this type of zombies:
<img width="717" alt="zrzut ekranu 2017-12-23 o 11 16 11" src="https://user-images.githubusercontent.com/16988054/34318898-ebd8c040-e7d2-11e7-8207-ce2e67a43986.png">

**Comment by libraryaddict** [comment]
My apologies, I believed there was no difference

**Comment by libraryaddict** [comment]
Should be resolved now.
