### ISSUE TITLE
Tab list bug

### ISSUE THREAD

**Issue by Cobwebster** [libraryaddict/LibsDisguises#273]
Upon having these selected, latest verison, 1.12.2

HideDisguisedPlayersFromTab: true
ShowPlayerDisguisesInTab: true

if you /d p anyname and then /u d, it doesn't put you back on tab.
tab becomes this tiny line,
https://gyazo.com/00d74fefab44eef79362b01477f5221f
  
no errors.

**Comment by libraryaddict** [comment]
Is this still an issue in the latest builds?
