### ISSUE TITLE
Breaks health boost status effect

### ISSUE THREAD

**Issue by mfnalex** [libraryaddict/LibsDisguises#275]
Health boost potion status effects deal damage instead of boosting the health when this plugin is enabled.

**Comment by libraryaddict** [comment]
I don't know what you mean, health splash potion worked as expected.
Golden apple worked as expected.

**Comment by mfnalex** [comment]
Try /effect health_boost

**Comment by libraryaddict** [comment]
I don't understand.

I used /effect health_boost, it gave me two extra hearts which began to regenerate.
The effect expired and those extra hearts disappeared.
