### ISSUE TITLE
UNDEAD_HORSE needs to be updated to ZOMBIE_HORSE?

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#276]
@libraryaddict Should UNDEAD_HORSE be changed to ZOMBIE_HORSE here? https://github.com/libraryaddict/LibsDisguises/blob/5a2f64bca403beb176b6f6d2468a2234a2600753/src/me/libraryaddict/disguise/utilities/DisguiseSound.java#L127

Since the permission to use the disguise is ZOMBIE_HORSE, not UNDEAD_HORSE.

**Comment by libraryaddict** [comment]
You're right, however I'm leaving it as is because it
