### ISSUE TITLE
Player tablist bug

### ISSUE THREAD

**Issue by libraryaddict** [libraryaddict/LibsDisguises#278]
Player tablist bug as described here

https://www.spigotmc.org/threads/libs-disguises-paid.197401/page-23#post-2837270

Appears to be the tablist is sent out of order when undisgusing, and not removed when appropriate.

**Comment by libraryaddict** [comment]
That should be a fundamental problem with the way the two plugins work. You'll need to disable the tab stuff in Lib's Disguises.

**Comment by xion87** [comment]
which options i have to disable in settings.yml?

**Comment by xion87** [comment]
Also i think the bug is introduced with 9.5.2, i gonna try to run 9.5.1 and see if it happen again

**Comment by libraryaddict** [comment]
Just to clarify actually, xion. Is the bug that the names are ordered wrong, or duplicate names?

**Comment by xion87** [comment]
no duplicate names/wrong, just the custom text on top and footer will gone

**Comment by xion87** [comment]
Nvm after some deep test i joticed the issue come from the latest titlemanager, sorry  don't consider my issue. But i got a small issue on hub where people using disguise will lose the prefix tag, there is  a way for disable that feature on libdisguise?

**Comment by libraryaddict** [comment]
Your config probably has a scoreboard option set, CREATE_SCOREBOARD is likely what you want.

**Comment by xion87** [comment]
I don't have that configuration on libsdisguise

**Comment by xion87** [comment]
I just noticed now my config was pretty outdated, and the plugin never update with new values, i make it regen and now is working :)
