### ISSUE TITLE
Zombie not disguised

### ISSUE THREAD

**Issue by ImranDoet** [libraryaddict/LibsDisguises#281]
Hello,

I'm using LibsDisguise for a minigame I'm working on, to disguise a zombie as a NPC so the 'NPC' still has pathfinders. The first time I tested it, where I spawned both entities on one chunk, it worked perfectly. But when I began putting in the map that the builders made, it started bugging out. The NPC's wouldn't spawn somehow. I thought this was because of the chunk loaded. So I added a line that loads the chunk. Now it works! Kinda.. the issue is that if I go away, the entity disappears, which is total normal behaviour, but when I come back into a close proximity, the entity doesn't reappear, nothing. Like the entity never was there. The weird part is that there are **no** stacktraces.

I don't know what's causing this bug but I hope you can help me.

**Comment by libraryaddict** [comment]
Firstly, are you sure that this is a Libs Disguises bug?

Entities do despawn.

Secondly, the premium version of Libs Disguises supports disguises saving, which is what chunks unloading would require I believe.

But I think it's the first one.

**Comment by ImranDoet** [comment]
Hm, I'll try removing the disguise part at all.

**Comment by ImranDoet** [comment]
Yes. I gave the Zombie no skin and it still was there when I took distance and then came into a clome proximity

**Comment by libraryaddict** [comment]
Can you try using /undisguiseradius 50 on the area the zombie should be?

It should undisguise everything, including the zombie if it's still alive.

Frankly I don't believe this is a bug caused by Lib's Disguises, but until we can prove it...

**Comment by ImranDoet** [comment]
Ok, I'll give the zombie it's disguise back and then test that

**Comment by ImranDoet** [comment]
What. Mind blown. It works now. So weird. The zombie was there btw.

**Comment by ImranDoet** [comment]
I really thought this was LibsDisguises because I literally tried EVERYTHING.
