### ISSUE TITLE
"Cannot interact with self!" kick when interacting while disguised 

### ISSUE THREAD

**Issue by DracarysPro** [libraryaddict/LibsDisguises#282]
Using PaperSpigot 1.12.2 (Build 1350)
Using LibsDisguises 9.5.1
Using ProtocolSupport (Build 209)
Tested with a 1.12.2 client (premium)

Players get kicked when interacting with stuff. Tested with sheep disguise, trying to interact with chests.
kick message: "Cannot interact with self!"

**Comment by libraryaddict** [comment]
Do you have any other plugins on?

Otherwise this is an issue with ProtocolSupport
