### ISSUE TITLE
Multiple properties cannot be set at once

### ISSUE THREAD

**Issue by mrcoffee1026** [libraryaddict/LibsDisguises#283]
example:
/disguise horse setColor brown setStyle white_dots setHorseArmor 418
as provided in documentation example results in:
You do not have permission to use the option setcolor

/disguise Ocelot setType BLACK_CAT setTamed TRUE setSitting TRUE
You do not have permission to use the option settamed

Basically anything more than one option results in the second thing saying there is no permission for it even though permission has been provided for each option.  It becomes even more ridiculous when you change the order of things or only specify any of the options I supposedly don't have permissions to use... and those options will be applied with no error.  Go back to putting it in a single command with multiple settings, it says I don't again.
- libsdisguises.disguise.*.setarrowssticking
- libsdisguises.disguise.*.setbaby
- libsdisguises.disguise.*.setburning
- libsdisguises.disguise.*.setcolor
- libsdisguises.disguise.*.setcustomname
- libsdisguises.disguise.*.setcustomnamevisible
- libsdisguises.disguise.*.setflyingwithelytra
- libsdisguises.disguise.*.setglowing
- libsdisguises.disguise.*.setsneaking
- libsdisguises.disguise.*.setsprinting
- libsdisguises.disguise.*.settype
- libsdisguises.disguise.*.settamed
- libsdisguises.disguise.*.setsitting
- libsdisguises.disguise.*.setarrowssticking
- libsdisguises.disguise.*.setanimalcolor
- libsdisguises.disguise.*.sethorsecolor
- libsdisguises.disguise.*.setprofession
Like all of these, for instance.

**Comment by libraryaddict** [comment]
libsdisguises.disguise.pig.setinvisible = Can only access set invisible
libsdisguises.disguise.pig.-setinvisible = Can access all options but setinvisible
libsdisguises.disguise.pig.-setinvisible.-setbaby = Can access all options but setinvisible and setbaby

You are only giving them one permission.

https://www.spigotmc.org/wiki/lib-s-disguises-setting-up-permissions/#permissions-ordering-and-negation

**Comment by mrcoffee1026** [comment]
If that were why this was not working, then according to the documentation, this should resolve any problem: 
- libsdisguises.disguise.*.-setinvisible.-setHidePlayer.-setNoGravity.-setHealth
would allow all options except for setinvisible, sethidelayer, setNoGravity, and setHealth, for every disguise.
"You do not have permission to use the option settamed"

**Comment by libraryaddict** [comment]
Which perms plugin are you using?

**Comment by mrcoffee1026** [comment]
luckperms.  Also tried adding this perm to the mix to cover all bases:
- libsdisguises.disguise.*.setarrowssticking.setbaby.setburning.setcolor.setcustomname.setcustomnamevisible.setflyingwithelytra.setglowing.setsneaking.setsprinting.settype.settamed.setsitting.setanimalcolor.sethorsecolor.setprofession

same error

**Comment by libraryaddict** [comment]
I've just tested it, after 2 weeks. And it's working perfectly as expected.

It's an issue with your permissions.

![image](https://user-images.githubusercontent.com/1419679/38448252-1b7dde58-3a57-11e8-8152-5c2116540b39.png)
![image](https://user-images.githubusercontent.com/1419679/38448257-211537bc-3a57-11e8-9df0-8ff617176990.png)

**Comment by mrcoffee1026** [comment]
Well not via your instructions it did not.  I had to add the permissions for each disguise like this:

libsdisguises.disguise.enderman.setai.setaggressive.setburning.setbaby.setcustomname.setcustomnamevisible.setflyingwithelytra.setglowing.setiteminmainhand.setiteminoffhand.setmainhand.setpotionparticlesambient.setrightclicking.setsneaking.setsprinting.setviewselfdisguise

Wildcards had no effect at all.  I'm not sure what permissions plugin your documentation references, but that's not how it works.
