### ISSUE TITLE
Setting skin from game profile

### ISSUE THREAD

**Issue by Pugabyte** [libraryaddict/LibsDisguises#286]
First of all, thank you for writing and updating this plugin. I made sure to purchase a copy when you made it a premium resource it. Well worth it.

I'm trying to set a playerdisguise's skin to one loaded from a "game profile". If I understand correctly, a game profile is the entire string output of [mojang's profile api](https://sessionserver.mojang.com/session/minecraft/profile/86d7e0e2c95e4f228f99a6e83b398307), right? 

I'm calling `disguise.setSkin(profile);`, no errors are being thrown in console, but the skin is set to alex/steve, instead of the skin from that profile. 

Any help is greatly appreciated.

**Comment by libraryaddict** [comment]
Inside disguises.yml is the line

# To get the skin signiture, you can find it on mojang's servers. Such as https://sessionserver.mojang.com/session/minecraft/profile/<uuid>?unsigned=false
# Just remember to remove the slashes from the UUID, remember the UUID is the unique code given to a player, just google for a tool to see someone's UUID
# Example: https://sessionserver.mojang.com/session/minecraft/profile/a149f81bf7844f8987c554afdd4db533?unsigned=false
