### ISSUE TITLE
Suggestion/Question setbaby permission

### ISSUE THREAD

**Issue by Flexxxxx** [libraryaddict/LibsDisguises#287]
Add a permission like libsdisguises.setbaby which allows players to use the set baby function on mobs that support it and if they have that adult mob permission unlocked.

Beneficial as there would be less permissions to set up if you took the route of libsdisguises.disguise.pig.setbaby for each applicable mob.

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/wiki/lib-s-disguises-setting-up-permissions/

Use wildcards and negation.
