### ISSUE TITLE
Disguises not working properly in other worlds

### ISSUE THREAD

**Issue by NeoFalcon1605** [libraryaddict/LibsDisguises#289]
When I try disguising as anything in any world but the normal overworld, nether and end the plugin won't recognise I'm disguised and moving and looking around become buggy and is fixed when going to a world it works normally in.

**Comment by NeoFalcon1605** [comment]
I can't really remove the other plugins, I did test it in worlds made by multiverse and a genesis rune from runecraft which creates a world though.

**Comment by libraryaddict** [comment]
Hmm

Can't test right now but I'm pretty confident I won't be able to reproduce.

Can you list the plugins used, their version including libs disguises,
version of minecraft and spigot as well as how many players, worlds were
used.

Also include configs if applicable. You can send this in a message on
spigotmc.

Just to clarify something, is this a case where self disguise breaks, or
disguises breaks when looking at other disguised entities.

How many players are online? Does it happen immediately after disguising.
Does it matter how long the server has been running?

I may have seen a similar bug but they were unable to provide me with a way
to replicate. Easiest way is a copy of the server and steps to reproduce.

Obviously, not something people want to do.

Again, if you want to send me this it would probably be best to send on
spigotmc.

**Comment by NeoFalcon1605** [comment]
If view self disguise is on then moving and looking around become buggy, but if it isn't the the plugin just doesn't recognise that I'm disguised as in when I try /undisguise it says I'm not disguised.  The configs for libs disguises I'm pretty sure haven't been touched and it's on the v9.5.1 Snapshot.  It also seems to be regardless of how many players are online and how long the server has been running.  Multiverse is on I think 2.5.0 and I would guess it would have something to do with it.  I tried in all the normally generated worlds, 1 generated by multiverse and 1 generated by runecraft.  The server was using Spigot on 1.12.1.  For trying to replicate it I would guess multiverse version 2.5.0, spigot for minecraft 1.12.1 and I'm not entirely sure about the libs disguises version since I don't know if there's multiple snapshots or not

**Comment by NeoFalcon1605** [comment]
I found out the cause of the problem.  Apparently it was ultra cosmetics breaking disguises in worlds it's disabled in
