### ISSUE TITLE
[Suggestion] setEnchanted option for Dropped_Item disguises

### ISSUE THREAD

**Issue by Flexxxxx** [libraryaddict/LibsDisguises#291]
Simply as the title states. This would be an awesome perk in making custom disguises! (unless I'm stupid and there is already a way to do this)

**Comment by libraryaddict** [comment]
Enchanted* but

**Comment by BlueSoapTurtle** [comment]
Hey, I noticed this only works for when the item is equipped by an entity, ex
/d player libraryaddict setArmor GOLD_BOOTS,GOLD_LEGGINGS,GOLD_CHESTPLATE,GOLD_HELMET
makes all their armor enchanted

**Comment by libraryaddict** [comment]
Just want to confirm @BlueSoapTurtle you're claiming that items are enchanted despite your not setting any enchanted related arguments?

**Comment by BlueSoapTurtle** [comment]
Yes, all equipment are being set to enchanted, think its cause in the commit you did, you don't check for the enchanted boolean before adding the unsafe enchantment.
