### ISSUE TITLE
Problems with version 9.5.2

### ISSUE THREAD

**Issue by OmgItsNik** [libraryaddict/LibsDisguises#293]
Hello I've recently updated to the newest version that's available in the spigot page, to confirm that I am a user that has purchased LibsDisguises my spigot username is xDizasterCYx. So I get this error in startup:
https://pastebin.com/3N52qZaN

And I get this on join:
https://pastebin.com/2VYjwzXp

My Spigot version is 1.12.2.

**Comment by libraryaddict** [comment]
Is this still an issue?

**Comment by OmgItsNik** [comment]
Yes.

**Comment by libraryaddict** [comment]
Can you use the latest download of Lib's Disguises from the plugin page
https://www.spigotmc.org/resources/libs-disguises.32453/

Use this build of ProtocolLib
http://ci.dmulloy2.net/job/ProtocolLib/403/

Resist using /reload
