### ISSUE TITLE
1.13 Error

### ISSUE THREAD

**Issue by mercurialmusic** [libraryaddict/LibsDisguises#294]
You may be working on this already, but just pasting in case it's useful. This is the error I'm getting in a 1.13 test server. The plugin still kinda loads but doesn't seem to have any function: https://pastebin.com/fQak288A

**Comment by Games4k** [comment]
It doesn't work for me too :D

**Comment by libraryaddict** [comment]
This project currently does not support 1.13

I'm waiting on a bug involving Optional.empty() at dmulloy2/ProtocolLib#498 before I can continue working on updating this to 1.13
