### ISSUE TITLE
README.md is.. confusing?

### ISSUE THREAD

**Issue by Miclebrick** [libraryaddict/LibsDisguises#298]
the README.md just says "One of the worst disguise plugins to hit the market, not only is the programming completely full of bugs, the author doesn't seem to care about the lack of up-to-date documentation." .... I assume it was referring to DisguiseCraft, not this plugin??

**Comment by libraryaddict** [comment]
It's more of a joke README

**Comment by libraryaddict** [comment]
I've updated the repo's description and the README.

Although it was a joke description, it didn't read very well. As such I've updated it to better professional standards.
