### ISSUE TITLE
Disguising as a player causes player stuck constantly moving

### ISSUE THREAD

**Issue by SecretlyJealous** [libraryaddict/LibsDisguises#299]
Hi,

For some reason, whenever I disguise as a different player and move in any direction it makes me constantly move in whatever direction I last walked in. I've linked a gif to show what I mean. I have ViewSelfDisguises set to true if that helps.

Config: https://pastebin.com/LBNFw7W9
Version: 9.5.2
ProtocolLib v4.4.0-SNAPSHOT-b396

Example: [https://media.giphy.com/media/Yji5d8vC7AC1NU9LMa/giphy.gif](https://media.giphy.com/media/Yji5d8vC7AC1NU9LMa/giphy.gif)

**Comment by libraryaddict** [comment]
Can you regenerate your config, new scoreboard options should appear.

**Comment by SecretlyJealous** [comment]
The issue seems to disappear with a default config however, when I disable something in the config like 

# Don't like players able to set themselves invisible when using the disguise commands? Toggle this to true and no one can use setInvisible! Plugins can still use this however.
DisableInvisibility: true

The issue still occurs :(
I think that modifying anything in the config file seems to cause this which is weird but I've only tested with the DisableInvisibility option being changed from its default value.

**Comment by libraryaddict** [comment]
Regenerating the default config should allow you to see more config options that may be previously hidden.

There should be a config option for scoreboard that appears now. You may have another plugin using the scoreboard.

**Comment by libraryaddict** [comment]
I'd say try the options with the custom scoreboard turned off. If it does fix the issue then it's obviously a conflict with the two.

As for it working until you modify the config, is there nothing weird showing in console?

**Comment by SecretlyJealous** [comment]
Don't see anything in the console, as for the custom scoreboard stuff I'll investigate this further and get back to you in a day or so.

**Comment by TheIntelloBox** [comment]
Same problem

**Comment by TheIntelloBox** [comment]
How to fix it @libraryaddict ?

**Comment by xOrlxndo** [comment]
@SecretlyJealous @libraryaddict What version of spigot are ya'll on? Not sure if this conflicts, but it can be a leading cause.

**Comment by TheIntelloBox** [comment]
@libraryaddict I just enabled self-disguises view in config.yml and if a player does /d p name, he constantly moves, even if you don't touch to your keyboard or your mouse.

**Comment by libraryaddict** [comment]
@TheIntelloBox can you try with other plugins disabled?
And can you provide your startup log.

The two common causes for this is a conflicting scoreboard plugin, or incorrect configuration. The last cause is an unreported error.

**Comment by libraryaddict** [comment]
@TheIntelloBox @SecretlyJealous if you're using 1.13, please update to the latest dev build.

https://ci.md-5.net/job/LibsDisguises/

Improved config handling and better support for self disguises, and a warning for possible conflicts.

**Comment by libraryaddict** [comment]
Is this still an issue

**Comment by SecretlyJealous** [comment]
Still an issue, when I update my servers to 1.13 I'll let you know if it is still an issue.
