### ISSUE TITLE
Everything invisible when disguised

### ISSUE THREAD

**Issue by MrMaty** [libraryaddict/LibsDisguises#300]
When you disguise and start moving, everything turns transparent.
Without disguise: https://i.imgur.com/FGrzCb2.jpg
With disguise: https://i.imgur.com/8t3krdB.png

Server/plugin info: https://i.imgur.com/OgAjktm.png

Disguises worked fine on 1.12. Ever since we switched to 1.8, libsdisguises stopped working.
I purchased the plugin.

**Comment by libraryaddict** [comment]
1.8 is not supported, at all.

Not sure how you got 1.12 version to work on it as it should never have worked.

**Comment by MrMaty** [comment]
https://i.imgur.com/FMzUCE0.png I tried this version for 1.8.

And we weere using this version for our 1.12.2:
https://i.imgur.com/IplPohT.png
Which works fine.

**Comment by libraryaddict** [comment]
Ah I misunderstood then.

It's still not supported, but can you try https://www.spigotmc.org/resources/libs-disguises.81/download?version=69816

It appears that this should work better.

**Comment by MrMaty** [comment]
Same thing happens with that version. I'm quite sure I used to run libsdisguises on 1.8 some time ago, what happened to those builds?

**Comment by libraryaddict** [comment]
Perhaps something changed? Such as using an experimental build of via version on an old version of minecraft.
