### ISSUE TITLE
Dev build can't login

### ISSUE THREAD

**Issue by danbzns** [libraryaddict/LibsDisguises#302]
Hey, I tried latest dev build (with premium) on 1.13 server and I cant login anymore.

Error:
`[16:40:21 INFO]: fergydanny logged in with entity id 283 at ([world]-71.04868099287938, 70.0, -34.502499962339556)
[16:40:21 INFO]: fergydanny lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex(6157) + length(4) exceeds writerIndex(6157): UnpooledHeapByteBuf(ridx: 6157, widx: 6157, cap: 6157/6157)
`
Happens to anyone that tries to join while the plugin is loaded.

LibsDisguises version:  9.6.0-SNAPSHOT
Protocollib version:  4.4.0-SNAPSHOT-b415
Server version: This server is running Paper version git-Paper-173 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by libraryaddict** [comment]
This may be a paper issue, can you try with normal spigot. And is that all the error?

**Comment by danbzns** [comment]
Heres a startup error: https://pastebin.com/FWUuvjLg I'll see if I can test with spigot

**Comment by FrankHeijden** [comment]
normal spigot same issue;
![kick](https://user-images.githubusercontent.com/22407829/44910046-f9b95980-ad21-11e8-91ab-604138558304.png)

**Comment by libraryaddict** [comment]
Just to confirm, you're using latest spigot and latest ProtocolLib?

**Comment by FrankHeijden** [comment]
Yep

**Comment by libraryaddict** [comment]
Are you using 1.13.1, or plan to upgrade to it soon?

This error is puzzling, it's both something I'm having trouble reproducing and one I feel familiar with.

**Comment by FrankHeijden** [comment]
Already using latest 1.13.1

**Comment by FrankHeijden** [comment]
Found that the issue occured with ProtocolSupport: https://paste.md-5.net/rinayebayi.coffee

**Comment by FrankHeijden** [comment]
also made an issue report on their github page; https://github.com/ProtocolSupport/ProtocolSupport/issues/885

**Comment by libraryaddict** [comment]
So you're saying the error which occurred in your earlier pastebin on Lib's Disguises enable doesn't occur anymore?

I was under the impression it still did.

**Comment by FrankHeijden** [comment]
I did not get that error; @danbzns did - I only got the kick message

**Comment by danbzns** [comment]
@libraryaddict not fixed, I just tried your latest version and nobody can join, same reason:
`[12:38:32] [Server thread/INFO]: fergydanny lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex(6157) + length(4) exceeds writerIndex(6157): UnpooledSlicedByteBuf(ridx: 6157, widx: 6157, cap: 6157/6157, unwrapped: PooledUnsafeDirectByteBuf(ridx: 6171, widx: 6171, cap: 8192))`

**Comment by libraryaddict** [comment]
Can you confirm you are not running ProtocolSupport, if that's the old minecraft version support plugin.

**Comment by danbzns** [comment]
I misinterpreted what you said, I am using protocolsupport

**Comment by FrankHeijden** [comment]
Reply of chevchik;

See libraryaddict/LibsDisguises#295

To be exact the problem is this line:
https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/java/me/libraryaddict/disguise/utilities/DisguiseUtilities.java#L869
It constructs a new chunk to send with no biomedata (while the packet itself is constructed with doLoad set to true(which requires biome data)).

**Comment by libraryaddict** [comment]
Should be resolved

**Comment by FrankHeijden** [comment]
works for me on b228 :)
Thank you for your time 👍
