### ISSUE TITLE
Libs Disguises is red on /pl (crashing now)

### ISSUE THREAD

**Issue by Castiella** [libraryaddict/LibsDisguises#304]
Hi there, ive followed what you said on your page. Put the premium download in the libs folder and then used the latest stable build in my plugins folder, yet libs is red in my /pl? i am using the most recent protocol lib.

**Comment by libraryaddict** [comment]
Can you provide a log file?

**Comment by Castiella** [comment]
[latest.log](https://github.com/libraryaddict/LibsDisguises/files/2346430/latest.log)

Heres the lastest log, thank you

**Comment by Castiella** [comment]
I updated to the build you uploaded 15 hours ago and it is fixed now, sorry to bother you.

**Comment by Castiella** [comment]
Oh, actually re-opening this because when players disguise they now crash

**Comment by Castiella** [comment]
Heres a log showing several player crashes after /d is used
[crash log.txt](https://github.com/libraryaddict/LibsDisguises/files/2346493/crash.log.txt)

**Comment by libraryaddict** [comment]
Please update ProtocolLib
