### ISSUE TITLE
Doesn't do anything 

### ISSUE THREAD

**Issue by Grederg** [libraryaddict/LibsDisguises#311]
Hello. I bought this Plugin and putted it on my 1.13 spigot server (the server hoster is called nitrado). I also installed ProtocolLib and downloaded the 1.13.1 data, then moved the original "LibsDisguise 9.5.2 .jar" file in the /plugin/LibsDisguise folder as i had to. But when I try to use it on the server, there is no reaction on any command. I can see, that the plugin works when I'm using the /plugins command (it shows me the name of the plugin in a green font), but everytime I try to use a comand, there is nothing. Not even an error message or something. it pretends like I never used the comand. There is also a plugin, that uses this plugin (MythicMobs) but the LibsDisguise functions don't work there either.

So is this because I am currently using 1.13 and the update file is for 1.13.1 or is there another reason?

Would be nice, if I get a quick respond.

**Comment by Grederg** [comment]
I managed fixing the bug on my own by using the build 213. It was propably the issue that I didn't use 1.13.1 but 1.13. But I still don't close this as there is no hint given that I should espacially use version 213.

**Comment by libraryaddict** [comment]
I'm going to close this as it's fixed, but why use 1.13 over 1.13.1?
