### ISSUE TITLE
Problem with teleports 

### ISSUE THREAD

**Issue by lunarisia** [libraryaddict/LibsDisguises#312]
Hi, I would like to talk to you about a problem we have on my server, when using the command /d wolf for example, I can see myself converted into the animal but when doing a teleport to a far away place, either a normal teleport with /tp 5000 56 1000 or a teleport made with a plugin, I miss the body of the animal. In other words, I don't see the body of the wolf or the body of my user. Could you answer me if it would be possible to solve this? I have a very big project with my server and it would be very helpful.

**Comment by libraryaddict** [comment]
Is bounding boxes in config turned on? That can present issues, it had a fix in the last week I believe.

**Comment by lunarisia** [comment]
We have the option turned in to false :( 
ModifyBoundingBox: false
And we are using last jar that you updated.

**Comment by libraryaddict** [comment]
Can you confirm it is not a plugin conflict?

That is, that when you have no other plugins, this still occurs?

**Comment by lunarisia** [comment]
We have tested it on a server with basic plugins like essentials, world edit, etc. We will check it again without any of those plugins and we will tell you the results when we can. Thank you.

**Comment by libraryaddict** [comment]
Fixed in https://github.com/libraryaddict/LibsDisguises/commit/4f06b1833f280cee997588a7e76dc50c180e1ea6
