### ISSUE TITLE
Libsdisguise unrunning

### ISSUE THREAD

**Issue by Temale62** [libraryaddict/LibsDisguises#313]
Hello

I have your plugin paid version, installed the latest version build and the plugin is still inactive on my server, it appears in red when I write /plugins 
do you have a solution?

thank you in advance
ps: I'm sorry for my english, i'm french
Temale

**Comment by libraryaddict** [comment]
You need to have the development version in your plugin folder.

And inside your LibsDisguises folder, the paid version.
