### ISSUE TITLE
Issue with libsdisguises 

### ISSUE THREAD

**Issue by lunarisia** [libraryaddict/LibsDisguises#317]
Regarding the problem discussed earlier in the other ticket I sent you (when you teleport yourself further than 64 blocks the entity don't teleport with you), which you have closed without giving me the opportunity to answer.
We have paid for this plugin just like the other users who use it in the 1.13. In the description of your plugin says so: Lib's Disguises is intended to be run only on: 1.11.2 and 1.12' (and for that reason we bought it in our case)
The normal thing would be that the plugin works perfectly for these versions and that in case it is not, could you try to also solve this problem for your customers of the 1.12.2 that have paid the plugin?
We can't upgrade the server to 1.13 right now and that doesn't mean we deserve less help.

With best wishes, Lunarisia.

**Comment by lunarisia** [comment]
Regarding the problem discussed earlier in the other ticket I sent you (when you teleport yourself further than 64 blocks the entity don't teleport with you), which you have closed without giving me the opportunity to answer. 
We have paid for this plugin just like the other users who use it in the 1.13. In the description of your plugin says so: Lib's Disguises is intended to be run only on: 1.11.2 and 1.12' (and for that reason we bought it in our case) 
The normal thing would be that the plugin works perfectly for these versions and that in case it is not, could you try to also solve this problem for your customers of the 1.12.2 that have paid the plugin?
We can't upgrade the server to 1.13 right now and that doesn't mean we deserve less help. 

With best wishes, Lunarisia.

**Comment by libraryaddict** [comment]
1. Tickets that are closed are not locked, you can still reply to them and I'll still see them

2. You know that description is nitpicking details, and it's clearly referring to the plugin on SpigotMC

3. You are literally using an old version of the plugin on the old version of Minecraft, then asking why the plugin isn't being updated for that version.

If this is still an issue to you, I can refund your payment and revoke your status on the site.

https://www.dropbox.com/s/0jfcnf3sfuugunw/LibsDisguises112Tp.jar?dl=0

**Comment by lunarisia** [comment]
Thank you very much, we will try now! :)
