### ISSUE TITLE
Incompatibility with latest ProtocolLib builds

### ISSUE THREAD

**Issue by Shadume** [libraryaddict/LibsDisguises#319]
Hi,
I've just installed LibsDisguise, and it seems to bee incompatible with the latest ProtocolLib build.
Here is the error : 
![procosmetics2](https://user-images.githubusercontent.com/45332675/48979505-30520680-f0bc-11e8-8b19-97c174005e82.png)

**Comment by libraryaddict** [comment]
Use the latest stable build, not dev build
