### ISSUE TITLE
[API]: Unable to disguise Citizens NPC

### ISSUE THREAD

**Issue by Silthus** [libraryaddict/LibsDisguises#321]
I am unable to get the LibsDisguises API to work with Citizens NPCs. No matter what I do the NPC always keeps the default skin.

The disguise data (texture and signature) is loaded from a database. The values are correct and a disguise object with the correct skin is returned. However calling `DisguiseAPI.disguiseToAll(...)` does not working (nothing happens).

This is the line where I disguise the entity (NPC): https://gist.github.com/Silthus/5308be01fe5775842ead03e38a68aca4#file-disguise-java-L92

I am using a trait that applies the disguise once the NPC is spawned: https://gist.github.com/Silthus/5308be01fe5775842ead03e38a68aca4#file-disguisetrait-java-L38

I debugged everything and the methods are all called. Even the `isDisguised` check works and does not print a warning message.

https://gist.github.com/Silthus/5308be01fe5775842ead03e38a68aca4#file-disguisetrait-java-L39

Any idea what is going on?

**Comment by Silthus** [comment]
Thanks for the quick reply! I am using build #242 from https://ci.md-5.net/job/LibsDisguises/

Here is the startup version dump for the relevant parts:

```
[07:31:51] [Server thread/INFO]: Starting minecraft server version 1.13.2
[07:31:51] [Server thread/INFO]: Loading properties
[07:31:51] [Server thread/INFO]: Default game type: SURVIVAL
[07:31:51] [Server thread/INFO]: This server is running Paper version git-Paper-474 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
...
[07:31:56] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v9.6.0-SNAPSHOT
...
[07:31:58] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.6.0-SNAPSHOT
[07:31:58] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_13_R2
[07:31:58] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v9.5.2), premium enabled!
[07:31:59] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[07:31:59] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
```

I tested the normal disguise commands /disguise Bat and /disguiseplayer Silthus Player Silthus and they work fine.

**Comment by libraryaddict** [comment]
Can you test as a random player who hasn't joined the server before. Eg "tomato"

**Comment by Silthus** [comment]
Disguising myself as another Player `tomato` worked. However trying to disguise the NPC as boat or Player `tomato` did not work.

Disgusing a sheep (non NPC) as `tomato` worked. So it seems to be a problem with the NPCs.

**Comment by Silthus** [comment]
Ok so it seems like citizens is forcefully reapplying its skin. Thats why LibsDisguises does not work.

I worked around the problem by using citizens internal API for NPC disguises.

```java
@Data
@EqualsAndHashCode(callSuper = true)
public class DisguiseTrait extends Trait {

    private Disguise disguise;
    private boolean appliedSkin = false;

    public DisguiseTrait() {
        super(RC_Traits.DISGUISE);
    }

    public void setDisguise(Disguise disguise) {
        this.disguise = disguise;
        disguise();
    }

    public Optional<Disguise> getDisguise() {
        return Optional.ofNullable(this.disguise);
    }

    @Override
    public void onSpawn() {

        disguise();
    }

    private void disguise() {

        if (getNPC() == null || !getNPC().isSpawned() || !(getNPC().getEntity() instanceof SkinnableEntity)) {
            return;
        }

        // citizens will respawn the NPC after changing its skin
        // not checking this will cause an endless loop
        if (appliedSkin) return;

        getDisguise().ifPresent(disguise -> {
            appliedSkin = true;
            SkinnableEntity skinnableEntity = (SkinnableEntity) getNPC().getEntity();
            skinnableEntity.setSkinPersistent(disguise.getSkinOwner(), disguise.getSkinSignature(), disguise.getSkinTexture());
        });
    }
}
```
