### ISSUE TITLE
Disguise name is cut off

### ISSUE THREAD

**Issue by Tinkergolem** [libraryaddict/LibsDisguises#322]
Disguises appear to have a character limit of 14 for display names. Are you able to extend the limit or let me know if there may be a alternative route to achieving the display of the full name?

**Comment by libraryaddict** [comment]
https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/java/me/libraryaddict/disguise/disguisetypes/FlagWatcher.java#L404

There is a limit of 64 characters, how are you attempting to display the name. And what name are you attempting to use?

Mojang limits all player names to 16 characters, and it looks like you might be using 2 characters for a color code.

**Comment by Tinkergolem** [comment]
Yes, I'm using a player disguise which indeed is limited by Mojang's 16 character limit. I will have to deal with the limit and alter the display name. By the way, I have seen plugins extend the limit from what has been said to be scoreboard prefixes or possibly scrolling strings. If you're able to let me know of the possibility to implement the idea, I would greatly appreciate it. Thank you for notifying me nonetheless.
