### ISSUE TITLE
Command bug

### ISSUE THREAD

**Issue by PasteK25** [libraryaddict/LibsDisguises#325]
Hello, I have an issue with my server. I just bought LibsDisguises to play on my personal 1.13 server. But when I put LibsDisguises version 9.7.1 and Protocollib version 4.4.0, all seems right, but in my server, when I type commands (I can auto complete commands with "tab" so I guess the plugin works) nothing happens, no error messages, nothing and the commands didn't work.
I already tried to change Protocollib version, change to craftbukkit, change to 1.13, 1.13.1, 1.13.2. Nothing fix the issue :(
Can you help me pls ?
Thanks for reading, I hope I'll find how to fix this because I need LibsDisguises for my server a lot ^^
Bye and thanks again :)

**Comment by PasteK25** [comment]
Oh, I forgot to specify something, the issue is happening for every commands of LibsDisguises, so I can't even use the plugin, that's embarassing :(

**Comment by libraryaddict** [comment]
Can you try the latest build, it doesn't fix anything but will provide a little more information.

Can you also provide your startup log, after using that version.

**Comment by PasteK25** [comment]
Oh, is there a new version of Protocollib (than 4.4.0) or LibsDisguises (than 9.7.1) ?
Here is the logs when I try to start my server : https://pastebin.com/fWJZv9dE
The error start at line 185

**Comment by libraryaddict** [comment]
It looks like it's caused by a weird setting on your server, yes. I'm not sure why though.

**Comment by PasteK25** [comment]
I see, do you think I can fix it ? because I can't access to the server.properties file, but I have some things that I can change
