### ISSUE TITLE
if I am far away from other players, their skin change to basic(Steve or Alex)

### ISSUE THREAD

**Issue by DevMagnolia** [libraryaddict/LibsDisguises#326]
If i change into a player and fix the skin, the skin will look changed to Alex or Steve when you move in or out of each other.

I am sorry that I am not good at English.

https://youtu.be/qJ3UpOco8vM
^^^ bug video

**Comment by DevMagnolia** [comment]
The above bug is hard to find a definite cause., There are times when it doesn't work and times when it works.

The bug that you can be sure of right now is this.: https://youtu.be/bkrpGdK-uxM
The skin changes when you come in.

**Comment by libraryaddict** [comment]
For that bug, what I think is happening there is that you took so long to join the world that it removed them from tab before you saw them properly.

I think this issue could be migrated somewhat by adding a config option to how long player tab list item lasts before being removed. Doesn't fix it, but can mean a difference.
