### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by Benjam1n0929** [libraryaddict/LibsDisguises#332]
https://gist.githubusercontent.com/libraryaddict/c4c25e0554dcf670f423b7b200153440/raw/904a976586f65e906121c832635fc4bff2902d5c/2019-01-08_15-34-04.txt

**Comment by libraryaddict** [comment]
Using the latest build of CraftBukkit and Spigot, I cannot reproduce the issue.

Unfortunately, you're using 1.13 which is unsupported. Please update to 1.13.2 as there are no releases for 1.13, and no support given for 1.13 or 1.13.1
