### ISSUE TITLE
arrows don't hit player if they hit the disguise

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#333]
Unlike melee, arrows shot at a disguise do not damage the disguised player.

You have to shoot at where the disguised player is to damage them.

https://youtu.be/tVud2uFTUPU

Arrows that hit the disguise entity should damage the player who is disguised as that entity.

Of course, the above is an example of a disguise without modified bounding boxes; [setModifyingBoundingBox](https://github.com/libraryaddict/LibsDisguises/blob/19f8b5b1e2085339dc624a9324683f629f0f6d84/src/main/java/me/libraryaddict/disguise/disguisetypes/Disguise.java#L623) (also accessible through the config) resizes the player's bounding box to that of the mob.

This only resizes though, it doesn't translate the player's (now larger/smaller) bounding box to where the mob actually is.

https://youtu.be/7_3acjSYnHI

The mob is always lagging behind the player, which means even though I still hit the mob it's missing the player's (now expanded) collision box and so the arrow doesn't damage them (I prove my point by aiming for the player on the last arrow, which is the only one that registers. You see in the bottom-left client the arrow actually goes underneath the iron golem, completely missing it).

The disguised player's collision box should be translated as well as resized.

**Comment by libraryaddict** [comment]
Please try the latest dev build

https://ci.md-5.net/job/LibsDisguises/

https://github.com/libraryaddict/LibsDisguises/commit/f883e9602866c14e4902bd063c8c455e9e45f476

**Comment by theonlygusti** [comment]
It's hard to tell but it seems better, arrows still bounce sometimes though.

I wonder if that's a problem with the vanilla server now though, because even without disguises arrows sometimes... disappear... when they should hit a falling player:

https://youtu.be/3fVkgNOb9-c

**Comment by libraryaddict** [comment]
Minecraft isn't a shining example of beautiful hitboxes.
