### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JTGgamer** [libraryaddict/LibsDisguises#334]
I am getting this error and the plugin isn't working.
https://pastebin.com/e5ETztdk

**Comment by libraryaddict** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/552

**Comment by JTGgamer** [comment]
Sorry, but that doesn't really help much. I am on the most recent version and don't have duplicate issues as well as not using the /reload command. It just stopped working. I don't know if i have a conflicting plugin but how would i find it?

**Comment by libraryaddict** [comment]
The reason I've linked that issue and closed this is because it's a ProtocolLib bug, not a Lib's Disguises bug.

**Comment by JTGgamer** [comment]
ok
