### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by anemul** [libraryaddict/LibsDisguises#341]
Followed you instructions and used the links provided for Protocollib . I am a purchaser . Here is what I'm getting :  https://pastebin.com/waWN1EHJ

**Comment by libraryaddict** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/556#issuecomment-456212127

**Comment by libraryaddict** [comment]
Can you try using Java 8 - Hotspot

**Comment by anemul** [comment]
I'm not sure what it Java 8 - Hotspot even is , although I am sure I could figure it out . However I have no control over the Java on the server I rent .

**Comment by libraryaddict** [comment]
Unfortunately this is a https://github.com/dmulloy2/ProtocolLib issue, and this is the only fix I know of.

**Comment by anemul** [comment]
oh well i guess I will just not use it then and try iDiguises . shrug , I don't know what else to do .
