### ISSUE TITLE
Player moved wrongly

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#344]
Why does the console get spammed with "Player moved wrongly!" warnings whenever a player is wearing a disguise?

**Comment by libraryaddict** [comment]
Do you have modify bounding boxes on, and are you using the latest version of the plugin?

There's a known issue with earlier versions of that setting and I don't believe it was fixed until 1.13

**Comment by theonlygusti** [comment]
@libraryaddict I have modify bounding boxes on, I am using 1.12.2.

Can you please link me the fix? I will try to incorporate it into a 1.12.2 build of the plugin (server has to be 1.12.2)

**Comment by libraryaddict** [comment]
https://github.com/libraryaddict/LibsDisguises/commit/dda362f082f83402dc08e08256d62ee29a1c5dbd

This below fix is optional and was added for a tick mismatch in positions.

https://github.com/libraryaddict/LibsDisguises/commit/f883e9602866c14e4902bd063c8c455e9e45f476

**Comment by theonlygusti** [comment]
Thank you I got it all sorted out here
