### ISSUE TITLE
Can I make "combined" disguises, entities joined together (riding etc.) ?

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#345]

**Comment by libraryaddict** [comment]
No, I did think about adding this functionality but decided to leave it out.

**Comment by theonlygusti** [comment]
@libraryaddict how can I implement it myself?

**Comment by libraryaddict** [comment]
It's not quite as simple as you think, Lib's Disguises changes what data is sent to the receiving players but you're looking at creating the data for an entity that never existed.

While some parts of Lib's Disguises could be helpful, this is largely an area that Lib's Disguises does not touch.

What you would be doing is sending a spawn packet to allow players to see it, metadata packet to display stuff like on fire, movement packets if you wanted it to move around, destroy packet to remove it. You would also be keeping track of who can currently see it, and who cannot.
