### ISSUE TITLE
cross-version bounding boxes

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#346]
I run LibsDisguises 9.5.2 on my 1.12.2 server (custom built with a couple patches, #344).

I have ViaVersion, ViaBackwards, ViaRewind, and 1.8.8 clients connect to the server, but when I try to set their hitbox by disguising them (modify hitboxes option is on) arrows and so on don't register as hits if they hit the disguise, they have to hit the invisible player.

**Comment by libraryaddict** [comment]
Hitboxes were broken up until 1.13, and I do not support older versions.

**Comment by theonlygusti** [comment]
@libraryaddict when I use LibsDisguises 8.6.7 on my 1.8.8 server I don't get this problem.

Wdym hitboxes were broken?
