### ISSUE TITLE
Morphed players are invulnerable

### ISSUE THREAD

**Issue by thomas-worm** [libraryaddict/LibsDisguises#347]
Players who are morphed don't get damage, even if ``MonstersIgnoreDisguises: false`` is configured.
We need morphed players to interact as normal player, this means:
* They should get damage from monsters
* They should hunger
* They should need air under water
* They should get fire damage
....

**Comment by thomas-worm** [comment]
We identified that this behavior is shown, when also GadgetsMenu is installed on the server.
So we opened also an issue there: https://github.com/OnlyNoobDied/GadgetsMenu/issues/660

**Comment by libraryaddict** [comment]
This issue isn't a problem with Lib's Disguises
