### ISSUE TITLE
squid disguise does weird things with knockback

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#348]
using either `setVelocity` or punching a player disguised as a squid makes the squid fly all around weirdly

**Comment by theonlygusti** [comment]
This is only back in 1.8

**Comment by theonlygusti** [comment]
@libraryaddict do you know what causes it though and how to fix it?

**Comment by libraryaddict** [comment]
If this is a 1.8 issue it is not supported. To fix it is code, did you need
me to point you to the code that fixed it?

You'd need to branch and modify the plugin then compile

**Comment by theonlygusti** [comment]
@libraryaddict yeah do you know which code fixed it?

**Comment by libraryaddict** [comment]
I think it was split up into several commits, but it would've been catching velocity packets then cancelling non-living entities.
