### ISSUE TITLE
Plugin Not Working on spigot 1.13

### ISSUE THREAD

**Issue by Ifriedmonkey** [libraryaddict/LibsDisguises#351]
I have tried every 1.13 version of Lib's Disguise even the Latest 1.13.2 version and the plugin doesn't work at all. It says it's outdated.
https://hastebin.com/odumocatuh.css

**Comment by libraryaddict** [comment]
Sorry I didn't get back to you sooner, the latest version of 1.13 is the only supported version.

Prior to the latest version of Minecraft 1.13, the builds were testing builds.
