### ISSUE TITLE
Errors when logging out in disguise

### ISSUE THREAD

**Issue by Momshroom** [libraryaddict/LibsDisguises#352]
I get console errors when a player logs out in some disguises.  Here's an example of me logging out while disguised as a creeper:

https://pastebin.com/fBihCdVM

Using Libsdisguises build 271, with the premium jar in the folder.  The error is the same whether using Protocol Lib 4.4.0 release or the latest dev build (#425).

Config.yml: https://pastebin.com/xmv11Vj2

**Comment by Momshroom** [comment]
Changing the config option for these to false stops the errors:
SaveDisguises:
  Players: false
  Entities: false
but I would prefer to be able to use this without error spam if possible. Ty!

**Comment by libraryaddict** [comment]
Can you try build 273, it should be fixed.

**Comment by Momshroom** [comment]
Yes, that fixed it. Tyvm
