### ISSUE TITLE
Hostiles should count as an "entity"

### ISSUE THREAD

**Issue by mrcoffee1026** [libraryaddict/LibsDisguises#353]
SaveDisguises:
    Players: true
    Entities: true

Except that the only entities that save their disguises are non-hostiles like villagers.  I have a group of slimes I'd like to keep disguised for my amusement (as well as others)... is this doable?

**Comment by libraryaddict** [comment]
There was an issue in older builds, does this issue persist in the latest build?

Hostiles should indeed, count as an entity.

A potential reason is that the hostile you're seeing is not the hostile that was there before. Such as despawning and a new hostile spawns in. This is not handled by Lib's Disguises.

**Comment by mrcoffee1026** [comment]
Well I'm using the latest Jenkins build right now and my slimes won't stay disguised.  I had the release on prior to that but had to take it off since it was flooding the console with errors from startup on... something about the snowmen disguise which - I believe - TardisWeepingAngels was using.  Anyway the Jenkins doesn't error flood but it can't keep a hostile disguised through restart.

**Comment by mrcoffee1026** [comment]
And no they aren't despawning and new ones spawning in their place.  It isn't even a slime chunk I had to put them there.  Put a bunch (like six) of size one slimes in a fenced in area on ground level... they can't go anywhere.

**Comment by libraryaddict** [comment]
1. I teleported away from spawn
2. I spawned a cow, and a skeleton. Used different nametags on them then disguised them.
3. I left the game, disguises were saved in the folder as expected.
4. I rejoined the game, the disguises were successfully reapplied.
5. I spawned a slime in, did not use a nametag and disguised them as a player.
6. I left the game.
7. I rejoined the game and disguise was sucessfully reapplied.

Can you try the latest dev build and confirm it's still an issue? Teleporting far from spawn then leaving the game will unload the chunks, which should trigger a disguise save. You can check the folder to see if it changed. Then rejoin to see if the entity is disguised again.

I'm not sure if there's a command for this, but I'd recommend checking to make sure the UUID of the hostile entity is the same.

**Comment by mrcoffee1026** [comment]
Yes, when leaving the game they keep their disguises... they lose them on restart is what i'm saying.  They should be keeping them through restart from the documentation "Saves disguises so that they persist after server shutdown" .  This is what is failing to work for me.

**Comment by mrcoffee1026** [comment]
Well I don't believe mobs strictly have a UUID... they have a UUIDMost and UUIDLeast and a UUIDWorldMost, but I think what you're looking for here "are these uniquely different entities when I come back to them" then no they are not.  The situation is this:

![2019-04-19_18 33 54](https://user-images.githubusercontent.com/3322491/56446666-f7683780-62d1-11e9-8471-33f127a9e6df.png)

In any case they are the same entity after restart.  They're all named... I've modified their data so that they are invulnerable and have the persist flag set (they should not despawn - although up to now minecraft has used this setting as a "suggestion" more than a "rule").

**Comment by libraryaddict** [comment]
Yeah, I think I see your issue.

I haven't checked yet, but the problem is likely that Lib's Disguises is being disabled before the chunks are unloaded when the server shuts down.

I'll test this later today and hopefully have a build ready then.

**Comment by mrcoffee1026** [comment]
I don't think that's it either though since if I put Nitwit villagers there instead and disguised those, they'll still be disguised after a restart.  This seems to be something specific to hostile mobs.

**Comment by libraryaddict** [comment]
Found the issue, use the latest dev build.

https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar

**Comment by mrcoffee1026** [comment]
I guess that wasn't the issue since after disguising these guys they all lose their disguise after a restart.  This is even after warping away and coming back to ensure the disguises were saved.

**Comment by libraryaddict** [comment]
Can you provide your startup log?

**Comment by mrcoffee1026** [comment]
No errors that I can find in relation to this... here's a log from start up to shut down... I did another test just to ensure there wasn't something wrong with the mobs themselves as I recall naming them and they had lost their names at some point either before the upgrade to 1.13.2 or when I did that, I'm not sure... so in this log you even get the summon command I used to put 6 new size 0 slimes in place and even the disguise command I used on them.
https://pastebin.com/uUVhsHYu

**Comment by libraryaddict** [comment]
[22:36:39] [Server thread/WARN]: [LibsDisguises] You must purchase the plugin to use saved disguises!

**Comment by libraryaddict** [comment]
To add onto this, there shouldn't be any saved disguises at all. It's possible that you have another plugin disguising them.

**Comment by mrcoffee1026** [comment]
but i have purchased it so...

**Comment by mrcoffee1026** [comment]
yeah installed properly it works fine now thanks very much!
