### ISSUE TITLE
[Request] 1.12.2 Support against the latest ProtocolLib

### ISSUE THREAD

**Issue by Delfofthebla** [libraryaddict/LibsDisguises#357]
My server is running on MC version 1.12.2. I have downloaded the appropriate disguiseLib version for this MC version and downloaded the appropriate ProtocolLib version that you stated should be used on the spigot page.

This is all fine and well, but once I started updating other plugins, (such as ViaVersion), they demanded I use a newer version of ProtocolLib.

So I upgrade ProtocolLib and have ViaVersion work properly, or I don't use ViaVersion (or any other plugin that has released recently) and ensure that DisguiseLib works properly.

It's not a tough decision, but it's also not ideal. So I ask:

Is it possible for you to maintain a branch for 1.12.2 that references the latest ProtocolLib?

**Comment by libraryaddict** [comment]
Try https://www.dropbox.com/s/w0q1sy533k82fc7/LibsDisguises-1.12.2%20PL.jar?dl=0

**Comment by BestMark** [comment]
It doesn't work at all. When player disguised in wolf, he was kicked: https://pastebin.com/S0B5X0F8
