### ISSUE TITLE
Server crash because of Lib's Disguises

### ISSUE THREAD

**Issue by Blueeyestar** [libraryaddict/LibsDisguises#361]
Spigot Version: CraftBukkit version git-Spigot-03bd4b0-6984fc4 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

I put in the latest disguises and later the server crashed completely.

[16:29:40] [Spigot Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.CraftWorld.isChunkLoaded(CraftWorld.java:332)
[16:29:40] [Spigot Watchdog Thread/ERROR]: 		me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:67)

https://pastebin.com/iDSSATRG

**Comment by libraryaddict** [comment]
What version of disguises?

**Comment by Blueeyestar** [comment]
It was the build #283. But it is now a new released. I will now test if it is fixed or if it comes back.

**Comment by Blueeyestar** [comment]
I have taken the most recent files but still the server crashes with the file

https://pastebin.com/r3c1K2Zw

**Comment by greasemonkey123** [comment]
I'll just put this here.

me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:67)

**Comment by Blueeyestar** [comment]
No solution in sight?

**Comment by libraryaddict** [comment]
It's because I'm forgetful and the problem isn't as simple as I'd like.

I can't say this would fix it, please tell me if the issue crops up again.

**Comment by Blueeyestar** [comment]
With the new version unfortunately also a new problem arose

https://pastebin.com/B9PnTjRZ

**Comment by libraryaddict** [comment]
Can I confirm that the first error also happened every minute or so, and that you are running vanilla spigot.

The disguises used, what is disguised and your config options.

**Comment by libraryaddict** [comment]
I'm also interested in a pastebin log file, if you're unwilling to provide this here just send me a message through spigotmc.org

**Comment by libraryaddict** [comment]
Please confirm the issue is fixed

**Comment by Blueeyestar** [comment]
I'll test it out and let you know.

**Comment by greasemonkey123** [comment]
From the re-open, I guess the issue is still arising?

**Comment by Blueeyestar** [comment]
I just got it on the server today. I accidentally pressed the wrong button ^^

**Comment by Blueeyestar** [comment]
The crash isn't coming anymore. But now there is a new problem. Carrots and potatoes saturate 2 times more. and animals and mobs need 5 times more blows before they die. only when you remove the plugin again everything works normally again.

**Comment by libraryaddict** [comment]
I wasn't aware of the saturated issue, but I have an idea of a potential reason for the damage issue.

**Comment by libraryaddict** [comment]
Damage issue continued at #368
