### ISSUE TITLE
1.13.2 plugin out of date

### ISSUE THREAD

**Issue by fatmanjumprope** [libraryaddict/LibsDisguises#362]
When trying to load the plugin on my 1.13.2 server I get met with this error.

https://pastebin.com/A3JEqhBU

I was wondering if I was maybe using a 1.14 version or the wrong version in general?

**Comment by libraryaddict** [comment]
Please use https://ci.md-5.net/job/LibsDisguises/282/

**Comment by fatmanjumprope** [comment]
Thank you for the response. In the link I click on the LibsDisguises.jar and download but once I insert it into the server it gives the same error on restart.

**Comment by libraryaddict** [comment]
Ah sorry, I responded with the wrong link.

https://github.com/dmulloy2/ProtocolLib/issues/556#issuecomment-456212127

Your version of java was likely upgraded, please downgrade.
