### ISSUE TITLE
Client crash when a mob mythicmobs uses the libdisguise option

### ISSUE THREAD

**Issue by jere62smi** [libraryaddict/LibsDisguises#363]
Hello, so it will be several months now that I have crashes with some mobs mythicmobs using skins players. I give you the minecraft error I have every time my game crash https://pastebin.com/LvkQDYeB
I always have the same error but there is only the name of the mobs that changes because it varies.

**Comment by libraryaddict** [comment]
Please confirm the issue is fixed

**Comment by jere62smi** [comment]
Yes it seems to work but I need to do more extensive testing with your latest development version. It could be that I recreate a ticket in the week if ever the bug recurs, hoping that no ^^

**Comment by jere62smi** [comment]
Well, I come back to you with bad news but it continues to crash. I send you the crash report.
https://pastebin.com/WzYjssnk

**Comment by libraryaddict** [comment]
https://www.dropbox.com/s/k15j5k9tf3b1uws/PacketListeners.jar?dl=1

Use
/packetlisteners named_entity_spawn
And
/packetlisteners entity_metadata
And 
Spawn_entity_living or was it spawn_living_entity.. 

Either in console, or by a player. Give me the output of the commands.

The plugin just checks what packet listeners are listening to that packet name and outputs the class, plugin and priority.

**Comment by jere62smi** [comment]
https://hastebin.com/elosicuhuz.cs

**Comment by libraryaddict** [comment]
Hi, unfortunately that site is not mobile friendly. Mind using another site such as pastebin.com?

**Comment by jere62smi** [comment]
Oups sorry.
https://pastebin.com/UMKWaYx5

**Comment by libraryaddict** [comment]
Are holographic displays tested as well?

**Comment by jere62smi** [comment]
Yes the holograms work properly, more in my dungeons, there is no hologram so I do not see why it would infect disguised mobs.

**Comment by libraryaddict** [comment]
Sorry I meant did you try removing the plugin and seeing if the issue still occurs.

My first guess is that the hologram displays could be modifying packets it shouldn't.

I have some free time today, hoping I can get this done then.

Are you able to provide your full server log as well? Please send this to me on spigotmc.

https://www.spigotmc.org/conversations/add?to=libraryaddict

**Comment by jere62smi** [comment]
I sent you the logs of the servers (private on spigot) at startup and you will see that there is nothing abnormal. In addition, I want to clarify that this bug is present since version 1.13 of minecraft, just the fact of disguised a mob can crash the players, I have the impression may be that when the chunck is unloaded can be because good Minecraft is not 100% opti at this level the crahs could occur but without certainty. I have not tested without the plugin HolographicDisplay, without your plugin down the skins do not function so I think you're talking about holographicdisplay but it seems really weird because in areas where there are disguised mobs, no hologram is in this area in a very large radius.

**Comment by libraryaddict** [comment]
Doesn't mean holograms are impossible to be at fault. I asked you to test for a reason.

**Comment by libraryaddict** [comment]
I've just checked Holograms, can you confirm the types of mobs you're attempting to disguise?

Specifically: Armorstand, slime, dropped items.

If you still believe it's not the problem, please test with the hologram plugin removed and tell me if the problem still exists.

More notably, it should definitely have a problem if you attempt to use a hologram line on a disguised entity.

I strongly believe this plugin is at fault, the server is run globally and just because it's supposed to work in a certain area doesn't mean it doesn't monitor all areas.

**Comment by jere62smi** [comment]
I'm sorry but I can not reproduce the bug with or without HolographicDisplay, it is completely random and can happen very often as very rarely and I have very little time right now.
I also use as plugin MMOItems and this plugin uses HolographicDisplays as dependencies to display the infos of regen, damages and others on the mobs, can be related to that?
Meanwhile that's my config of one of the mobs that crash players.

https://pastebin.com/8JRRbSsE

Hope this can help you and that we will soon find this bug.

**Comment by libraryaddict** [comment]
I cannot help you further, sorry.

**Comment by jere62smi** [comment]
Ah down super, in any case it's going to be 1 month that I report the problem and still not solved... Disappointing, I do not know your plugin me, I gave you all the information I could give, the plugins, logs, my configs but hey I can not solve the problem of your plugin for you.
I will continue to search for myself when I have free time...
