### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by IgnisCraft** [libraryaddict/LibsDisguises#365]
I am struggling with the disguises latest build #289. Everything boots up fine, and the plugin runs, but when I have it running players cannot log in they receive Internal Server Error. I've done a few tests to determine that the issue is only present when LibDisguises is running properly (with the 9.8.2 premium jar file in the folder) but the issue is not present when running the server with LibDisguises #289 and the ProtocolAPI, so only when I have the premium plugin in the folder.
[2019-06-12-4.log.gz](https://github.com/libraryaddict/LibsDisguises/files/3281354/2019-06-12-4.log.gz)

**Comment by greasemonkey123** [comment]
I have posted this to [Pastebin](https://pastebin.com/KRpWdxsN) and removed all visible IPs.
From the looks of it, the crash isn't triggered by Lib's Disguises, but I'll leave it to LibAddict to decide.

**Comment by libraryaddict** [comment]
Please confirm the issue is fixed
