### ISSUE TITLE
new errors ?

### ISSUE THREAD

**Issue by anemul** [libraryaddict/LibsDisguises#366]
https://pastebin.com/K2GXTvXK

**Comment by greasemonkey123** [comment]
What server version are you trying to run this on?

**Comment by anemul** [comment]
1.13.2

**Comment by greasemonkey123** [comment]
Are you using [this build](https://ci.md-5.net/job/LibsDisguises/282/)?

**Comment by anemul** [comment]
Yepper , that is the one .

**Comment by anemul** [comment]
and protocol 440

**Comment by libraryaddict** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/556#issuecomment-456212127
