### ISSUE TITLE
[1.13.2]Lag and crash 

### ISSUE THREAD

**Issue by xion87** [libraryaddict/LibsDisguises#367]
Hi i noticed with Protocollib 4.4.0 and Libsdisguise 282 and latest version of Paperspigot 1.13.2 randomly the server will lag and player crashes if any disguise are used, the error that i have are these: https://gist.github.com/xion87/0dd37ed7df90c71e4a91610bbf64254e

**Comment by libraryaddict** [comment]
This sounds familiar, sorry I didn't get back to you. Unfortunately, I don't have time to look into this anytime soon.

The most obvious question is to check startup for any errors and see if there's a fix to be applied there.

**Comment by libraryaddict** [comment]
Closing as this appears to be an issue with PL, and although I've since changed API's in 1.14 it isn't a bug in LD itself.

Currently, I don't have the time to backport changes. Sorry.

**Comment by xion87** [comment]
That was caused by crash client hack, it helped me to track down these ones,, using viaversion patch the issue
