### ISSUE TITLE
LibsDisguises nerfs sword and axe damage

### ISSUE THREAD

**Issue by PsychoLynx** [libraryaddict/LibsDisguises#368]
Hello!

On our server we discovered a bug we tracked down to the 1.14 dev builds of LibsDisguises. Namely, all sword/axe (and I presume other items too) damage is nerfed to only 1-3 points of damage regardless of type, even diamond ones.

In order to ensure that LibsDisguises was the cause, we had the following setup.

**Test setup:**
**Server:** Latest available Spigot dev build (git-Spigot-df0eb25-30a6337 (MC: 1.14.2)
**LibsDisguises versions:** LibsDisguises dev build no. 290 and LibsDisguises Premium (9.8.2) in the plugin folder
**ProtocolLib:** Tried both versions ProtocolLib 4.5.0-SNAPSHOT-b8 and ProtocolLib 4.4.0-b425, but it made no difference which one was on the server. The bug persisted regardless of ProtocolLib version.

I tried changing many of LibsDisguises' settings, but none seemed to affect the sword damage nerf.

Cheers,
PsychoLynx

**Comment by Lix3nn53** [comment]
This error effects all of melee attacks for me. I change NBT attributes of tools to edit their damages. Tested bow, trident, axe. 286 nerfs damage by %20ish while 290 nerfs damage by %80ish.

**Comment by christofin** [comment]
Same here. 1.14.2, latest version of Spigot and Lib's Disguises. 

Fall damage is fine, but sword and axe damage for all players on the server is nerfed.

**Comment by jere62smi** [comment]
I also have the same problem, I tested your latest build version and it does not solve the problem.

**Comment by libraryaddict** [comment]
Please test the new latest build

**Comment by jere62smi** [comment]
Hello, I tested and it seems to work again. Thank you for fixing this bug.

**Comment by B-Knight49** [comment]
Anyone else getting this error again? I'm using v9.9.8 and every mob is only taking like 1-3 damage.
