### ISSUE TITLE
Mob turning invisible when

### ISSUE THREAD

**Issue by TofPlays** [libraryaddict/LibsDisguises#369]
A mob becomes invisible when disguised:

With this version: https://www.dropbox.com/s/w0q1sy533k82fc7/LibsDisguises-1.12.2%20PL.jar?dl=0
https://pastebin.com/qY1exTUz

I tried this version, spawned a disguised mob and got kicked out of the server
http://prntscr.com/o4v0eb
https://www.spigotmc.org/resources/libs-disguises.81/download?version=69816

https://pastebin.com/CUdFjzRL

**Comment by libraryaddict** [comment]
You are using the wrong version of ProtocolLib, as noted when you found the download link, you must be using a specific version of ProtocolLib.

https://www.spigotmc.org/resources/protocollib.1997/download?version=165553
