### ISSUE TITLE
Plugin not Working Spigot 1.14

### ISSUE THREAD

**Issue by LizzyTheOne** [libraryaddict/LibsDisguises#370]
I bought the premium version, followed all the steps, but /dis or any other command for libsdisguises does not seem to work, any advice?

**Comment by libraryaddict** [comment]
Please send me your full server log on spigotmc

**Comment by greasemonkey123** [comment]
If you do /pl, does LibsDisguises show as Green, Red or not in the list at all?

**Comment by LizzyTheOne** [comment]
Shows as green.

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/conversations/add?to=libraryaddict

Please send full server log to receive any further help. Closing ticket for now.
