### ISSUE TITLE
Chunk Crash

### ISSUE THREAD

**Issue by slvlr** [libraryaddict/LibsDisguises#371]
https://pastebin.com/9HCa4ex8

Server crashed, this was in the logs (spammed), has protocol lib errors in it?

It appears that this crash would occur when entering a certain chunk. The crash only happened when Libs disguises is installed, when removing Libsdisguises the chunk no longer causes the crashes

**Comment by greasemonkey123** [comment]
Same error, spams this in the console.
When someone is disguised, it makes **all of the players in the server** horribly lag.

https://pastebin.com/3MGipwf4

**Comment by libraryaddict** [comment]
greasemonkey your issue is with PL, but for the both of you I believe the latest version of LD may fix this.
