### ISSUE TITLE
Craftbukkit compatibility?

### ISSUE THREAD

**Issue by christofin** [libraryaddict/LibsDisguises#372]
Hello,

I'm wondering if it would be possible for this plugin to be updated to work with the latest craftbukkit revisions. When I try using this plugin with craftbukkit, the in-game chat states that an internal error occurred and I get a lot of console spam. If you're interested, I can post the console feedback. 

It's working flawlessly on the latest Spigot 1.14.2 versions.

**Comment by libraryaddict** [comment]
Bug in PL, not LD.
