### ISSUE TITLE
Console spam while using DisguiseType.UNKNOWN

### ISSUE THREAD

**Issue by Lix3nn53** [libraryaddict/LibsDisguises#373]
Hey, I want to make an entity invisible but it must be really quick. (Arrow) So I choose DisguiseType.UNKNOWN since that seems most light weight. Seems like it works perfect but I am getting spammed with WARN:

https://pastebin.com/wShWnrLv

**Comment by libraryaddict** [comment]
UNKNOWN is not intended for use...

I suppose I could make it such, but not currently.

**Comment by Lix3nn53** [comment]
This way makes disguising entities as invisible things really easy and boosts performance (creating a living disguise is slower for arrows if you use it regularly) So I appreciate if you make it

**Comment by Lix3nn53** [comment]
I found another solution for my case, I am using protocol lib to send WrapperPlayServerEntityDestroy packet. So if you don't wanna bother and no one needs this you can close the issue :smile:

**Comment by malonnnn** [comment]
@Lix3nn53 

What would the performance difference be between disguising as unknown, and disgusising as say a creeper with invisibility set?

Since a creeper is built into the game, it shouldn't have to load a skin.

If you have reasons that your way is better, I might want to use such a feature

**Comment by Lix3nn53** [comment]
As you can see in the video there is a delay before cat moves like it should:
https://www.youtube.com/watch?v=_Z3aayYkOCk&feature=youtu.be

Thats why I used WrapperPlayServerEntityDestroy packet(via protocol lib & packet wrapper). Which is very clean way if you want to make entity invisible forever.

**Comment by malonnnn** [comment]
Super interesting! If you had set the invisibility flag on the cat via libsdisguises, which also uses protocollib to stop sending packets, would that not be just as efficient?

**Comment by Lix3nn53** [comment]
I don't know how libsdiguises handles it but this is the cleanest way I think? Dont need to setup any disguise
