### ISSUE TITLE
When disguised as a another player, it freezes the player 1.14

### ISSUE THREAD

**Issue by magmiy** [libraryaddict/LibsDisguises#377]
When using the /d player command to disguise as another player, I freeze and is unable to move and therefore have to relog.

**Comment by libraryaddict** [comment]
Can you provide your server startup log

**Comment by magmiy** [comment]
https://pastebin.com/gNdVxiEr

**Comment by libraryaddict** [comment]
Is this a /reload type command?

If so, can you test with a an actual server restart. Reloader are not supported or recommended.
