### ISSUE TITLE
Getting this console spam on using /disguise im on 1.14.3

### ISSUE THREAD

**Issue by Vehzx** [libraryaddict/LibsDisguises#378]
ok so im getting this error pasted in my console over and over again after using /disguise
even using /disguise once, activates the spam and it just pastes it over and over until i stop the server, disguising also seems to be bugged in some way when i /disguise and try move around I slowly walk and everything is jittery, and i dont actually get disguised either

error pastebin: https://pastebin.com/BtSNWs2H
list of my plugins (incase you know of plugins that break libsdisguise): https://i.imgur.com/0N4WtVS.png

**Comment by libraryaddict** [comment]
Apologies for the late reply, are you using the correct builds of PL?

**Comment by Vehzx** [comment]
As far as I'm aware I'm pretty sure I'm using the latest version of both, is there somewhere that is not spigot where they release builds before putting them on spigot?

**Comment by Vehzx** [comment]
Oh, you helped me fix this through spigot DM, so everything is fine now.

There is one small issue still, the disguise always moves forward slowly on its own, even when im not touching any keys on my keyboard, it does this for players too.

Here is a short gif of what happens, all I did in this clip was tap w, then was using my mouse to turn, but the disguise walks forward on it's own, this isn't a huge issue, but just kind of a quality of life improvement if you will.

https://i.gyazo.com/20687bc0a3f20654e6efac9b6fe9a6d2.mp4

**Comment by libraryaddict** [comment]
This is commonly caused by scoreboard plugins, such as nametags.

Check if you can disable collisions in their configs.
