### ISSUE TITLE
Dropped item disguises non-functional in 1.14.3

### ISSUE THREAD

**Issue by dbhatfield** [libraryaddict/LibsDisguises#379]
Using the latest versions of LibsDisguises and ProtocolLib in their dev builds for 1.14.3, disguising as a dropped item with any material type simply makes the entity disappear with a slight flicker shadow on the ground. No errors appear in the console, and every mob type besides a dropped_item seems to work.

LibsDisguises Version: v9.8.2-SNAPSHOT-b293
ProtocalLib Version: v4.5.0-SNAPSHOT Build 9 (Jun 23)

**Comment by libraryaddict** [comment]
Possibly fixed in latest build
