### ISSUE TITLE
LibsDisguises 9.5.2 (latest for 1.12.2)

### ISSUE THREAD

**Issue by kenace87** [libraryaddict/LibsDisguises#382]
This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[LibsDisguises] Loading LibsDisguises v9.5.2-SNAPSHOT 

https://gist.github.com/kenace87/eea0b31498aee656c7a2117d2d3fe21c

Disguise as an enderman gives an error in console.

**Comment by libraryaddict** [comment]
I don't know why I haven't responded to this yet, but the problem is in ProtocolLib.

I believe I link a specific build on the plugin page to use for this Minecraft version.
