### ISSUE TITLE
Jenkins Build #295 shows every player disguise in tab even with ShowPlayerDisguisesInTab false

### ISSUE THREAD

**Issue by malonnnn** [libraryaddict/LibsDisguises#385]
The disguises are not disappearing from tab.
Checked build 294 and problem does not exist.

I'm setting skins using

/disguiseplayer \<player\> player \<someName\> setskin {"id":"\<uuid\>","name":"\<player\>","properties":[{"signature":"\<sig\>","name":"textures","value":"\<val\>"}]}

**Comment by libraryaddict** [comment]
Fixed in latest build

**Comment by malonnnn** [comment]
Sorry, it doesn't appear fixed to me

Run the following command on any entity, being sure to replace the UUID correctly obviously:

`
/disguiseplayer <UUID> player "testguy" setskin {"id":"87fb3c6c5ff64bf6b326992c6137ea12","name":"tektronic","properties":[{"signature":"HyMeZmZFLLB8DMb
QCoQtdldCSohvPMYNvBZbA1yEaqDZ+3Xc4GtjWLL01U23EAgT2PSIweuD1a0lPz1QMkUB0NZ9CQ3NXQd7zBS7iywLndEauP/GyrQwdegV3ij8NpaWaMvalMafg+qunrUAjtMyknVFWYqhUW6b992PnLwO6qnHghTtlCU57xExqfj3dh4InlwSxc6jvtRMKmjxVP+Z3kSDoNu9MI7LRuiU
rO2IiRcwyG0WSzXTRS5pz8gDQeusiFoSnyDLVpFEwtidAuNllZPg6BYjqSWYAfUQsDsNQTRC0C8ofG98kWrabGz6bPjG1XZnlNxjT2+Fs5CuidDFK7I46rhV7OYg/fr3i4VK4lxTx/jRhrnd7wKYwGhLIyq81nvwm+8Jur/ZGp2WQ/6C/KAPeLMzq86owcZmMAGakJdwfLPzYG8n4h3mx
CUjbmZJatzk0dP8oTkw/XMx+ze/wTv3DZ0hEfzBx+Iz53dS59cEKGss4yF65cXeESUF2D8t+7IQB7LjWWOxv0BY1lEbSaDA7TvllUYpKe7c3exLh15Hygtxgw6KW2jEMznGxTkpaWQVrr6voZGrc3fU3jpwvj+YH49PS0zWGA7WseEf5fHNm3iILox+TzRHC8DBdIOEcQC+b5YDsBWHyJ
Ta/brRn3A8QfzcrANZyTWuknNvS+8=","name":"textures","value":"eyJ0aW1lc3RhbXAiOjE1NjQwNzA0MjMyMzAsInByb2ZpbGVJZCI6IjM5MTc2MmViMjRmNjRkOTU4NGQ2YmZhYzY4MmQ1NzVhIiwicHJvZmlsZU5hbWUiOiJTdHJpa2VyTWF4Iiwic2lnbmF0dXJlUmVxdW
lyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81ZDNhNDJmOTdiN2UzZjY1MzZkNzBjMmM5MTc2MzI0ZjcxNDU5NzQ5MmY4ZTQzZDVlMzNlYzk0YzJlNjJhZDVmIiwibWV0YWRhdGEiOnsibW9kZWw
iOiJzbGltIn19fX0="}]}
`
