### ISSUE TITLE
NoSuchMethodException on Startup #2

### ISSUE THREAD

**Issue by firebl0od** [libraryaddict/LibsDisguises#387]
hi ! i have the same issue as this thread.
https://github.com/libraryaddict/LibsDisguises/issues/383
saw you closed it. 
can you explain how to resolve ? tanks !

**Comment by libraryaddict** [comment]
I'm sleepy and may have gotten this wrong but I believe the problem was failure to follow instructions.

Check plugin page for instructions. There are pictures 

Check right versions

**Comment by firebl0od** [comment]
okey i will try again then, i tried with multiple protocollib versions, im gonna search again ^^
