### ISSUE TITLE
Freezing Players

### ISSUE THREAD

**Issue by marvinej** [libraryaddict/LibsDisguises#388]
Teleportation while disguised causes player to be frozen and unable to move unless they log out and back in. 

Libs Disguises 9.8.2
Paper Build 152 Minecraft 1.14.4

**Comment by libraryaddict** [comment]
Is this an issue still?

**Comment by marvinej** [comment]
It seems to happen less frequently now. It happened a few times when i used /spawn (using essentials spawn)

**Comment by libraryaddict** [comment]
Is this still an issue? Are you using ProtocolSupport?
