### ISSUE TITLE
An internal error has occured, and another issue!

### ISSUE THREAD

**Issue by Pokecraftallday** [libraryaddict/LibsDisguises#390]
When I do anything using /disguise it says an internal error has occured, and when I disguise myself  I have a weird mouse glitch, like it turns fine but it is super jittery! How do I fix these issues, i'm using 1.14.4

**Comment by libraryaddict** [comment]
Can you provide your server log file?

**Comment by Vencorr** [comment]
I can provide server logs as I am experiencing the same if not a similar issue. However, I don't seem to be disguising.

https://pastebin.com/4Y84f2Ft

**Comment by libraryaddict** [comment]
Closed as the pastebin is no longer available.
