### ISSUE TITLE
"Must purchase..." error message in console, though paid for it

### ISSUE THREAD

**Issue by gmalone** [libraryaddict/LibsDisguises#396]
Getting unexpected message in console.
I purchased the 1.14.x version of Lib's Disguises, have the Paypal transaction record, used it on a now gone server, have installed latest 1.14.x version on new server and am getting this in console:
`09.09 09:13:15 [Server] ERROR You must purchase the plugin to use support for 1.14!
09.09 09:13:15 [Server] ERROR This will be released free once the plugin is stable!
09.09 09:13:15 [Server] ERROR If you've already purchased the plugin, place the purchased jar inside the Lib's Disguises plugin folder
09.09 09:13:15 [Server] INFO Disabling LibsDisguises v9.8.2-SNAPSHOT`
I realize what it's saying, but I find no email containing a link to a paid version.

Could it be under a name other than libraryaddict or Andrew Hicks?  Kindly assist.  I apologize if this is the wrong place to post this.

**Comment by SoSeDiK** [comment]
Did you follow the instructions?
https://imgur.com/a/AaXARfr
You should place the latest plugin's build inside the `plugins` folder and the jar from the spigotmc inside `plugins/LibsDisguises`.

**Comment by gmalone** [comment]
Got it, now.... again.  Thanks.  It's a bit of an unconventional approach though there's a clear bold link pointing to the instructions, so my bad. The description *might* be made a bit more clear too, amidst the immense clutter present on the Spigot overview page.  No prob, though. Thanks again.
