### ISSUE TITLE
loading plugin problem

### ISSUE THREAD

**Issue by Killance** [libraryaddict/LibsDisguises#398]
Hello,

I recently bought the plugin LibsDisguises but it doesn't work on my server. I followed the steps on https://imgur.com/a/AaXARfr because I have to use dev build on my server (paperMc 1.14.4). Here is the encountered encountered : https://pastebin.com/82cP2vzZ.

Killance

**Comment by libraryaddict** [comment]
Interesting.
You're using the latest ProtocolLib? The problem seems to be with that plugin.

Of course, you can always use Spigot.
