### ISSUE TITLE
Chunk Load problems on 9.5.2 (server side)

### ISSUE THREAD

**Issue by mckite** [libraryaddict/LibsDisguises#400]
What behavior is expected:
Chunks to load properly in a wide area around me.

What behavior is observed:
Chunks either didn't load that far around me on sync chunk loading ( 3 chunks ) or some parts on a certain map didn't load at all with async chunk loading, they are there though when sync chunk loading is on ( though on another map like I said it only loads 3 chunks in front of me )

I tried both original version of MC 1.12.2 without any mods, and with optfine.
The result was same, And many player have same problems. (Not a Client Problem / Without LibsDisguises, that problem didn't occur,)

![2019-09-10_17 31 08](https://user-images.githubusercontent.com/17083624/64656625-9dd5e600-d3f5-11e9-9360-445a247f42e4.png)

[08:03:15 INFO]: Plugins (7): Essentials, EssentialsSpawn, LibsDisguises, Protoc
olLib, Vault, WorldEdit, WorldGuard

**LibsDisguises version 9.5.2**

**I tried using ProtocolLib version 4.3.0 and 4.4.0 both /
tried on both PaperSpigot_1.12.2_1618 and latest version of 1.12.2 spigot**

When I removing LibsDisguises,
chunk load problem was fixed. **Without LibsDisguises, that problem didn't occur,**

And, I put LibsDisguises in plugin folder , that problem was occur again.

That problem occurs any render-distance, but especially very more in distance above 9. ( Below 8 has very low times occur)

I think LibsDisguises also causes this problems also on 1.13.2

https://github.com/PaperMC/Paper/issues/2518

**Comment by libraryaddict** [comment]
I see this with backwards support.

Try disable the bed settings in config. 
Should be near bottom and called bed

**Comment by mckite** [comment]
> I see this with backwards support.
> 
> Try disable the bed settings in config.
> Should be near bottom and called bed

How to fix or disable in 10.0.5
Because there are no option for bed
