### ISSUE TITLE
Anyway of getting this to play nice with armorstand editor?

### ISSUE THREAD

**Issue by mrcoffee1026** [libraryaddict/LibsDisguises#401]
This plugin:
https://dev.bukkit.org/projects/armor-stand-edit
Combined with yours would create some very cool possibilities... particularly with the /disguiseenity Player command.  The result as of now is that the armor stand is disguised - but into the most un-posed state possible.  Modifying the armor stand with the plugin is still possible but the disguise ignores all changes.  Would it be possible for the disguise to use information from the armor stand for placement... as I believe it does when a player is disguised (leg, arm, head placement).  I may have to approach them about this topic as well but I'm not sure if cooperation between the two plugins are needed here or if disguises just discards certain information about armor stands that it COULD keep and use if there was a reason to... as this would be a reason to.

**Comment by libraryaddict** [comment]
Am I correct in assuming you're trying to modify an armorstand to say, do pushups.

And you expect the player disguise to also be doing pushups?

If so, this is impossible.

It's like teaching a dog how to herd sheep, then trying to copy/paste the same information into a cat.

Sure it sounds like it should work, but a cat was never made to herd sheep... It just can't do it. Infact, it's not even a dog so the cat would have a brain meltdown.

Use /disguisehelp player - To see what you can do with a player disguise.

**Comment by mrcoffee1026** [comment]
That is about what i was looking for.  Thank you for the information, that's too bad... though if anyone ever makes a cat/dog brain swapping device, I'll be sure to try it here first.
