### ISSUE TITLE
Error when trying to load up plugin for the first time

### ISSUE THREAD

**Issue by Godlycreations** [libraryaddict/LibsDisguises#403]
After installing the plugin and starting the server, I receive the following error message:

18.09 21:54:31 [Server] INFO [LibsDisguises] Enabling LibsDisguises v9.8.2
18.09 21:54:31 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.EntityCow.<init>(net.minecraft.server.v1_14_R1.World)
18.09 21:54:31 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082)
18.09 21:54:31 [Server] WARN at java.lang.Class.getDeclaredConstructor(Class.java:2178)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createEntityInstance(ReflectionManager.java:158)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:41)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
18.09 21:54:31 [Server] WARN at java.lang.Thread.run(Thread.java:748)
18.09 21:54:31 [Server] WARN java.lang.NullPointerException
18.09 21:54:31 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.09 21:54:31 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18.09 21:54:31 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.09 21:54:31 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:55)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
18.09 21:54:31 [Server] WARN at java.lang.Thread.run(Thread.java:748)
18.09 21:54:31 [Server] WARN java.lang.NoSuchFieldException: tracker
18.09 21:54:31 [Server] WARN at java.lang.Class.getDeclaredField(Class.java:2070)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:515)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:528)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:72)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
18.09 21:54:31 [Server] WARN at java.lang.Thread.run(Thread.java:748)
18.09 21:54:31 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.EntityTracker
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
18.09 21:54:31 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
18.09 21:54:31 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
18.09 21:54:31 [Server] WARN at java.lang.Class.forName0(Native Method)
18.09 21:54:31 [Server] WARN at java.lang.Class.forName(Class.java:264)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsClass(ReflectionManager.java:466)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:528)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:74)
18.09 21:54:31 [Server] WARN at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
18.09 21:54:31 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
18.09 21:54:31 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
18.09 21:54:31 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
18.09 21:54:31 [Server] WARN at java.lang.Thread.run(Thread.java:748)
18.09 21:54:31 [Server] ERROR Error occurred while enabling LibsDisguises v9.8.2 (Is it up to date?)
18.09 21:54:31 [Server] INFO java.lang.ExceptionInInitializerError: null
18.09 21:54:31 [Server] INFO at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47) ~[?:?]
18.09 21:54:31 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-192]
18.09 21:54:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
18.09 21:54:31 [Server] INFO Caused by: java.lang.NullPointerException
18.09 21:54:31 [Server] INFO at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:515) ~[?:?]
18.09 21:54:31 [Server] INFO at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:528) ~[?:?]
18.09 21:54:31 [Server] INFO at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:74) ~[?:?]
18.09 21:54:31 [Server] INFO ... 10 more
18.09 21:54:31 [Server] INFO [LibsDisguises] Disabling LibsDisguises v9.8.2

I currently use PaperMC1.14.4, CMI, and the most recent version of ProtocolLib, I was not receiving any errors before installing your plugin on my server. After installing it, I also found that it caused errors with my Battle Arena plugin as well.

**Comment by libraryaddict** [comment]
Please read plugin description.
