### ISSUE TITLE
Spawning of Disguised mobs via MythicMobs is Glitched 1.14.4

### ISSUE THREAD

**Issue by Possemaster** [libraryaddict/LibsDisguises#405]
I bought the Dev plugin today in order to get my MythicMobs to spawn disguised as players.
But it is very glitchy see video for more detials. If I remove lib disguise the issue goes away and my mobs are obviously not disguised but rootcause lies with lib disguise.
The mobs are spawning from center of my sscreen and than teleport to their spawn location, very weird. Only the disguised mobs do this.

https://wwls.nl/mythicmobs  is the video where you can see the behaviour.

MC Version: 1.14.4
PaperMC: paper-199

**Comment by libraryaddict** [comment]
Hi, sorry for the late response.

Unfortunately that link does not work.

Are you able to test with the latest version of PaperMC, without ProtocolSupport (If you are using) and with the latest builds of Lib's Disguises.
