### ISSUE TITLE
Issue Enabling LibsDisguises

### ISSUE THREAD

**Issue by Hqvox** [libraryaddict/LibsDisguises#406]
My server is running Spigot 1.13.2 with the server host Server.pro. I am using LibsDisguises 9.8.2 and ProtocolLib 4.4.0 as the Spigot Page for LibsDisguises instructs.. I cannot, for the life of me, figure out what's wrong. I am stumped. My dev team is stumped. Here's a paste: https://pastebin.com/zQvg3sfr

**Comment by libraryaddict** [comment]
Issue with Java hotspot in ProtocolLib

Try changing Java version
