### ISSUE TITLE
Unable to hit players disguised as ender dragons with melee

### ISSUE THREAD

**Issue by NeoFalcon1605** [libraryaddict/LibsDisguises#407]
Using version 9.8.2-SNAPSHOT-b294, Spigot, mc version 1.14.4
I tested using silverfish, spider, ghast and ender dragon disguises.  Silverfish, spider and ghast all had their melee hitboxes changed according to the hitbox of the disguise but for the ender dragon there was no hitbox for melee (the overall hitbox and individual hitboxes didn't work and neither did where the player was).  I believe this issue may be related to the dragon having multiple hitboxes due to it working for other disguises.

**Comment by libraryaddict** [comment]
Vanilla thing.
