### ISSUE TITLE
JSON Malformed Error

### ISSUE THREAD

**Issue by Peda1996** [libraryaddict/LibsDisguises#409]
After installing this plugin, some of my users get kicked with the message: (this only happens when a user is disguised)

![grafik](https://user-images.githubusercontent.com/1789749/69651013-ba3a0400-106f-11ea-94e1-589c240f7aa6.png)

The console isn't showing any errors..

Update:
- after using the option: 
```# Shall the players view their disguises?
# Best used when viewing yourself in 3rd person
ViewSelfDisguises: false
```
users are not kicked anymore, but they can't see themself disguised.

I am using paper spigot build 230, behind the newest version of waterfall

**Comment by libraryaddict** [comment]
Sorry for the super late response, are you using ProtocolSupport? That has compatibility issues with the plugin.

**Comment by Peda1996** [comment]
Yes, I am using ProtocolSupport to enable players that do not have the version 1.14.4 to play on my server. Do you know any alternative for ProtocolSupport?

**Comment by libraryaddict** [comment]
Sorry no, the only other plugin that comes to mind is ViaVersion.
