### ISSUE TITLE
Having issues with the falling block and dropped item constructor

### ISSUE THREAD

**Issue by boddahburnout** [libraryaddict/LibsDisguises#411]
I'm using this from the Creating a disguise page linked on the spigot 

MiscDisguise miscDisguise = new MiscDisguise(DisguiseType.FALLING_BLOCK, 18, 1); 

But when I add this to my plugin it still shows me as a stone block for both falling block and dropped item alike. I noticed only on these two in the ide it show they are depreciated? I don't see it on the docs anywhere. If this is really depreciated what is the new way of doing this?

**Comment by libraryaddict** [comment]
Unless using an old version of MC, should be using material types instead of material ids.

That said, I've noticed there's no constructor to do so, I'll push the change in a sec

**Comment by libraryaddict** [comment]
Forgot to link it, but will be the latest build.

Use "new MiscDisguise(DisguiseType.FALLING_BLOCK, Material.DIAMOND_BLOCK)" for example.

**Comment by boddahburnout** [comment]
I did also just figure out this works
MiscDisguise miscDisguise = new MiscDisguise(DisguiseType.FALLING_BLOCK, Material.DIAMOND_BLOCK, 1);
thanks for the quick reply
