### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 123ab2** [libraryaddict/LibsDisguises#413]
whenever i try to do  a command it says an internal error occoured while attempting to preform this command

**Comment by libraryaddict** [comment]
Can you provide your latest.log?

The current known issues are.

1. If you're on 1.14 its likely you have an apache error, in which case try http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/
2. ProtocolSupport is known to have some issues
3. If you're on 1.15 then use the latest build of ProtocolLib https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by 123ab2** [comment]
im on a server hosted by a website i dont know how to install custom plugins minehut.net

**Comment by libraryaddict** [comment]
You can try contacting your server host for further support, have a good day!
