### ISSUE TITLE
Problem with saving a disguise

### ISSUE THREAD

**Issue by SoSeDiK** [libraryaddict/LibsDisguises#414]
I need to save the disguise upon player rejoining, so I've enabled this feature in the config (`SaveDisguises.Entities: true`), but I faced two problems.

Used code for the disguise: https://pastebin.com/4ekApvFN
- ItemStack doesn't save CustomModelData.
I have a custom model for that specific CustomModelData, but upon rejoining it shows just a regular hoe.
- java.lang.StackOverflowError on disabling *(and so disguise doesn't get saved)*.
Full server log: https://pastebin.com/sF4uVTcK

**Comment by libraryaddict** [comment]
Unable to replicate, disguise saves as expected.

Can you verify that you don't have other entities nearby that could be disguised?

**Comment by SoSeDiK** [comment]
Yes. Just in case I started a fresh server *(new map, old settings cleared)* with only ProtocolLib, LibsDisguises, and my TestPlugin.

ItemStack when spawning a disguised mob and after rejoining the server: https://imgur.com/a/Gn4YmN0

Paper and plugins' builds are the latest ones for now *(versions can be seen in the log below)*.
Here's the new log: https://pastebin.com/4SVYdTQu

The whole TestPlugin is just this one class: https://pastebin.com/m651H54K

Plugin's config *(if needed)*: https://pastebin.com/fnSEEUiY

**Comment by libraryaddict** [comment]
Unfortunately I wasn't able to replicate your issue with gson deserializing, I did however discover that item metadata wasn't being serialized at all...

Which is now fixed. Commit coming shortly.

Please try the build once available and tell me if the problem persists.

**Comment by SoSeDiK** [comment]
ItemMeta is fine now, thanks.
I still have the deserializations issue though. Not sure what's causing it.

**Comment by libraryaddict** [comment]
Using paper I can replicate the issue, not with spigot.

So of course I need to figure out what paper touched, but it's not obvious.
I have to go do other stuff, I'll try look into this when I get back.

**Comment by libraryaddict** [comment]
Fixed in latest build, you'll notice that the issue happened everytime the disguise was loaded not created, then tried to save.
