### ISSUE TITLE
Watcher doesn't get updated after logout

### ISSUE THREAD

**Issue by SoSeDiK** [libraryaddict/LibsDisguises#416]
Example plugin: https://pastebin.com/YvksT7tw
LivingWatcher works fine setting the disguise on fire and extinguishing it, but it stops to do so once a player rejoins the server.

Using LibsDisguises build 350 (*with* `SaveDisguises.Entities: true`), ProtocolLib build 443 and Paper 1.15.1 build 26.

**Comment by libraryaddict** [comment]
Thats because the zombie despawned.
