### ISSUE TITLE
LibsDisguises break event call on NPCLib

### ISSUE THREAD

**Issue by pluttotv** [libraryaddict/LibsDisguises#417]
NPCLib is a great api for creating npc without the need to create like in citizen real entity.
the problem is that you can't interact with npc on NPCLibs with this amazing plugin -> libsDisguises is running on the server at the same time with NPCLibs. 

with and without the disguise it still break the event called for interaction with the npc created in NPCLibs.

https://github.com/JitseB/NPCLib/issues/45

**Comment by libraryaddict** [comment]
What are you holding when you interact, what is the real entity, what is the entity type, and are you disguised at the time of attempting to interact?

**Comment by pluttotv** [comment]
im not disguised when i do it. 
to interact with the packet npc you click left or right mouse

**Comment by libraryaddict** [comment]
What are you holding in your Minecraft Player hand, both offhand and main hand, the item, when you interact.

What is the real entity of the NPC.

What is the Disguise Type of the entity.

**Comment by pluttotv** [comment]
its an npc created with a packet not an living entity -> its has skins like normal players.

**Comment by libraryaddict** [comment]
`ProtocolLibrary.getProtocolManager().addPacketListener(clientInteractEntityListener);`

I've checked the code over and ProtocolLib is used as expected and does not cancel or modify the packet if the entity id is not owned.

NPCLib however is using TinyProtocol, which is different.

My suggestion: NPCLib needs to look into compatibility with ProtocolLib.

https://github.com/dmulloy2/ProtocolLib

https://github.com/dmulloy2/ProtocolLib/tree/master/TinyProtocol
