### ISSUE TITLE
LibDisguises permissions not working

### ISSUE THREAD

**Issue by Exarchh** [libraryaddict/LibsDisguises#421]
Hi, I use luckperms on my server and I've tried to give player access to disguises. However players can't seem to access any disguises even if I give them the libsdisguises.disguise.* or libsdisguises.disguise.*.* permission, even individual perms like libsdisguises.disguise.sheep don't work, however myself as an OP can use the commands. Is there any clarification you can offer? or maybe i'm doing something wrong?

I'm currently using the latest version of both plugins and the command I'm using is
/lp group/user [group/user] permission set libsdisguises.disguise.[permission]

**Comment by libraryaddict** [comment]
Hi, I've responded to you on spigotmc however I'll put the reply here as well.

The latest builds are for 1.15, if you're using that version can you try them and use /libsdisguises permtest

https://ci.md-5.net/job/LibsDisguises/

You will need to place the jar downloaded from spigotmc in your Libs Disguises folder.

**Comment by Exarchh** [comment]
Hi, yes I saw your reply on SpigotMC as well.

I'm currently using 1.15.1, but all jars are up to date and placed in the correct folders. However, still only OPs can use disguises.

**Comment by libraryaddict** [comment]
If you've purchased the plugin and are using the dev builds, follow the instructions here: https://imgur.com/a/AaXARfr

https://www.spigotmc.org/resources/libs-disguises.32453/download?version=306176
Put that in the libs disguises folder

**Comment by Exarchh** [comment]
Yes I have them installed in those folders

**Comment by libraryaddict** [comment]
Does it say Lib's Disguises is not purchased, or no permission to use?

And what do the results of "/libsdisguises permtest" say?

**Comment by Exarchh** [comment]
![image](https://user-images.githubusercontent.com/55347392/72698145-ea48e380-3b96-11ea-9954-a454a39637c6.png)
No there's no errors or anything I can see to suggest an issue

**Comment by Exarchh** [comment]
When assigning permissions to someone, LuckPerms doesn't recognise the .disguise part of the permission, but it should still work since it's hooked into libsdisguises

**Comment by libraryaddict** [comment]
Can you give them the permission "libsdisguises.disguise.pig" and see if it works.

It looks like a misconfiguration with your permissions plugin.

**Comment by Exarchh** [comment]
![image](https://user-images.githubusercontent.com/55347392/72698421-42341a00-3b98-11ea-85c7-2d46152249f2.png)
I gave them libsdisguises.disguise.pig and they received this msg when trying to use /d pig

**Comment by libraryaddict** [comment]
Did you negate the seecmd permission?

https://www.spigotmc.org/wiki/lib-s-disguises-setting-up-permissions/

Another option is that they need to use /dis or /disguise

**Comment by Exarchh** [comment]
/dis worked but /d and /disguise didn't. Still no errors in console.

And no, they have the libsdisguises.seecmd permission

**Comment by libraryaddict** [comment]
It looks like another plugin has taken over /d and /disguise.

I'm not sure how to see what plugin has done that, my only idea is to tabcomplete.

**Comment by Exarchh** [comment]
We don't have any plugins that might clash with those commands, LibsDisguises is the only gadget/cosmetic plugin we have installed

**Comment by libraryaddict** [comment]
Lib's Disguises does not give that error.
It says you are forbidden to use that command.

It looks a lot like you've negated the permissions on the commands. And the only way I can think of is by negating the seecmd permissions.

**Comment by Exarchh** [comment]
Giving a player libsdisguises.seecmd lets them see and use the commands, and when I remove the permission, they get the same error as shown before

**Comment by libraryaddict** [comment]
And seeing as they have the permission by default, as defined in Bukkit specs. That means you're either negating it, or your permission plugin is negating it.

And seeing as no one else had this issue, it appears that you've misconfigured your permissions to negate it.

**Comment by Exarchh** [comment]
I might have hah. Thanks for the help :)

**Comment by soshimee** [comment]
I have this issue too, but not with the bukkit's default permission message, it's libsdisguises permission message. All seecmd permissions there, disguises permissions there.

**Comment by libraryaddict** [comment]
> 
> 
> I have this issue too, but not with the bukkit's default permission message, it's libsdisguises permission message. All seecmd permissions there, disguises permissions there.

Because I don't want you to hide that :)
