### ISSUE TITLE
Disguised Mounts Lose Movment Speed

### ISSUE THREAD

**Issue by pentlock1** [libraryaddict/LibsDisguises#425]
When I use a disguise on on ride-able mount it does not keep its original movement speed. If the mount is undisguised the movement speed returns to normal. It seems to inherit the lowest base speed of the mount in which the ride able mob is disguised as. If horse is disguised as a non ride able mob, all control of mount is lost. I have tested this on both vanilla mounts and ones created with MythicMobs and the effect is the same. Logs and MM setup in link below. All configs for paper localhost and plugins are as they are when freshly generated, excluding ProtocolLib in which debug modes were turned on for information purposes. Tested on both paper-83 and paper-87 builds with same effect. Not sure if this is a bug, intended, or unavoidable but thought I would report it just in case it is a bug. Not sure if this belongs here or in your support channel on the MM discord. Thanks for looking at this, great plugin.

https://pastebin.com/BvL952Qs

**Comment by libraryaddict** [comment]
Losing control of mount is unavoidable, however the losing mount speed attributes should be a bug.

**Comment by libraryaddict** [comment]
Fixed in https://github.com/libraryaddict/LibsDisguises/compare/b65bbb634067...ed098752f6e6
