### ISSUE TITLE
mobs now attacked disguised players

### ISSUE THREAD

**Issue by mrcoffee1026** [libraryaddict/LibsDisguises#426]
Latest release - in spite of selection in config - mobs will attack disguised players.  Also the release download is titled 9.9.2 instead of 9.1.2.

**Comment by libraryaddict** [comment]
Can I confirm you are setting MonstersIgnoreDisguises?
Mobs will ignore pvp and pve settings.
9.9.2 is accurate..

**Comment by mrcoffee1026** [comment]
yeah sorry when i went to download the version prior it gave me 9.1.1... making me think the version made this huge leap.  From my config:
```
# This prevents disguised players from being targeted by monsters.
# This doesn't prevent their targeting you if already targeting when disguised
# They will just ignore you unless provoked.
MonstersIgnoreDisguises: true

```

**Comment by libraryaddict** [comment]
Mind providing your startup log?

**Comment by mrcoffee1026** [comment]
https://pastebin.com/ifsUrtsa

**Comment by libraryaddict** [comment]
Ah, found a critical bug. My apologies. I'll release 9.9.3 shortly.
