### ISSUE TITLE
Mohist support

### ISSUE THREAD

**Issue by Matthysse** [libraryaddict/LibsDisguises#431]
Hello !
Could you add a Mohist support for your plugin? It would allow us to play with Lib's disguise and with mods!

**Comment by libraryaddict** [comment]
Sorry but I don't plan to support modded servers, it'd bloat the plugin too much and require a lot of compatibility changes.

**Comment by Mgazul** [comment]
> Sorry but I don't plan to support modded servers, it'd bloat the plugin too much and require a lot of compatibility changes.

If you agree, Maybe I can make a version for Mohist

**Comment by libraryaddict** [comment]
You can, although I won't be able to offer assistance.
