### ISSUE TITLE
Players without proper perms can autocomplete LD commands

### ISSUE THREAD

**Issue by SoSeDiK** [libraryaddict/LibsDisguises#432]
As the title says. That's kind of annoying thing.
Running 1.15.2 Paper 130, ProtocolLib 447 and LibsDisguises 445.

**Comment by libraryaddict** [comment]
You mean the /disguise command
Or /disguise bat?

If its the /disguise command, then there's a separate set of commands for that found here: https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/resources/plugin.yml#L116

**Comment by SoSeDiK** [comment]
I mean every single command.
https://imgur.com/a/2vTYLtd

**Comment by SoSeDiK** [comment]
Oh. I didn't see that part.
Well, it's kind of strange that players can see commands by default even though they don't have permissions to execute them.
So guess I'll have to update the plugin.yml on every update, right?

**Comment by libraryaddict** [comment]
Update it to what though?
As far as I'm aware, "libsdisguises.disguise.sheep" doesn't make "libsdisguises.disguise" true

**Comment by SoSeDiK** [comment]
I mean libsdisguises.seecmd lets players see the commands by default. So player can autocomplete /grabskin, but can't use it. You can't see the command in tab completion if you are not allowed to use it in vanilla. That's why I was a little confused. I don't use any of the permissions plugins, so I'll have to set that perm to false directly in the plugin.yml every time. Am I correct?

**Comment by libraryaddict** [comment]
Unless you have a feasible suggestion that doesn't make everything harder for people who use permission systems as intended, this isn't possible to my knowledge.

**Comment by SoSeDiK** [comment]
My point is:
1. libsdisguises.seecmd is granted to every player as default permission: https://imgur.com/TUar1pA
2. Players can see and autocomplete LD commands because of that: https://imgur.com/Ytw3hAL
3. When they type a command they get a message that usage is forbidden: https://imgur.com/a/jPPw4s7

That doesn't really fit the current vanilla behavior. You shouldn't be able to see the commands if you are not allowed to execute them.

**Comment by libraryaddict** [comment]
plugin.yml controls the permissions for seeing and not seeing.
Without completely redoing the permissions system or requiring everyone to get the permission to see the commands, I have no way to do this.

It doesn't matter if its vanilla, I don't have a way to do this without getting hacky.
All because someone doesn't want to bother with permissions systems and wants to have plugin authors rewrite their code.

If you don't want a permissions system, that's fine. But I'm not going to do something that hurts the overwhelming majority of the userbase just to sastify you.

**Comment by libraryaddict** [comment]
Of course, you can always disable commands in the config.

**Comment by SoSeDiK** [comment]
Yeah, I get it. That's just not something vanilla or any other plugin has.
Having the ability to see the commands but not to run them is unusual, I've never faced this before.
What's the use-case though? I mean, why would the player need to see the command if he has no right to use it?

**Comment by libraryaddict** [comment]
Added it regardless, happened to be possible in this case.

**Comment by SoSeDiK** [comment]
Ah, many thanks! By the way, I do believe in permissions, and I do use LuckPerms ;)
But this exact server is mostly complete vanilla for a small group of people, and I'm the only person with OP rights there. I don't really need a permission plugin in this case.
