### ISSUE TITLE
Build 449 -> 457 blew up.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#437]
Updating from 449 -> 457
https://gist.githubusercontent.com/andrewkm/8d77454986ab51f44fee8477f8a2f869/raw/d5dd571752b3d7748b76960b00c1af49fd671b6e/gistfile1.txt

Insane spam, thousands beyond thousands of lines.
Had to revert.

**Comment by libraryaddict** [comment]
Fixed due to rollback
