### ISSUE TITLE
A lot of exceptions

### ISSUE THREAD

**Issue by BestMark** [libraryaddict/LibsDisguises#438]
Please, fix a lot of exceptions which your plugin outputs.
Paper 1.12.2, latest ProtocolLib dev build. JFR:
![image](https://user-images.githubusercontent.com/18399104/77831990-c7f9b600-7143-11ea-8d26-21cdf0bde8a8.png)

**Comment by BestMark** [comment]
I sent you .jfr in SpigotMC conversation.

**Comment by libraryaddict** [comment]
I have no idea what a jfr is

**Comment by BestMark** [comment]
@libraryaddict sorry, JMС*

**Comment by BestMark** [comment]
Is it connected with ViewSelfDisguises? If I will disable this feature, the exceptions will disappear?
