### ISSUE TITLE
Make disguised players rideable (those mobs that are rideable)

### ISSUE THREAD

**Issue by Skydragonsz** [libraryaddict/LibsDisguises#442]
I want disguise myself as an pig and take some of my players on an adventure. 
I do see that there is a setSaddle option but this only shows the saddle and not make it rideable.

**Comment by libraryaddict** [comment]
Sorry this will not be implemented, I don't see it as a function that Lib's Disguises should include.

**Comment by libraryaddict** [comment]
Correct, and to make them rideable would likely come under a "fun" plugin.
Like those that make tnt do huge explosions.
