### ISSUE TITLE
Bossbars

### ISSUE THREAD

**Issue by x1p** [libraryaddict/LibsDisguises#443]
Bossbar works when disguising
When undisuising (undis) bossbar doesn't disappear.

When another disguise is given, another bossbar is added. Now there are 2 bossbars.
When undisguising, both bars don't disappear.

You can add a lot of bossbars this way.
![Screenshot_20200405_144043](https://user-images.githubusercontent.com/28690790/78498582-7953a980-774b-11ea-8de9-b1204edcfa5f.png)
LibsDisguises 10.0.0

**Comment by libraryaddict** [comment]
Fixed in latest build
