### ISSUE TITLE
Painting disguise spam.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#444]
Anytime someone disguises as a painting console spams:
https://pastebin.com/raw/5aRZQuUT

Paper: 161
Libsdisguises: 9.9.9/465

To reproduce make sure other players are around you when disguised as a painting.
Being alone without other players in/around your loaded area will not reproduce the issue.

**Comment by libraryaddict** [comment]
Fixed in latest build
