### ISSUE TITLE
MiscDisguise

### ISSUE THREAD

**Issue by IBROI** [libraryaddict/LibsDisguises#446]
MiscDisguise miscDisguise = new MiscDisguise(DisguiseType.FALLING_BLOCK, new ItemStack(Material.FLOWER_POT));
DisguiseAPI.disguiseEntity(player, miscDisguise);

if I write this code, then I just don’t show the pot, I can’t become one.
same problem with the cauldron and brewing stand

**Comment by libraryaddict** [comment]
What version of the plugin?
What version of the server?

On the latest release of Lib's Disguises on 1.15, those three disguises are working with no issues.

**Comment by IBROI** [comment]
1.12.2 paper
10.0.3 LibsDisg
ProtocolLib 4.5.0

and the same problem with CakeBlock

config LibsDisg - https://pastebin.com/mtMHNmif

**Comment by IBROI** [comment]
You help me ?

**Comment by libraryaddict** [comment]
Fix will be pushed once I've resolved a bigger issue.
You do know the fix will be removing those disguises as valid right? So you can't disguise as a cake.

**Comment by IBROI** [comment]
I did not understand you. Will you just remove these disguises?

**Comment by libraryaddict** [comment]
Yes, this is what you ask for
