### ISSUE TITLE
Disguised shulker bullet orientation/direction wrong

### ISSUE THREAD

**Issue by totemo** [libraryaddict/LibsDisguises#448]
LibsDisguises 10.0.0-SNAPSHOT
PaperClip 1.15.2 161

I'm seeing odd results when disguising shulker bullets as mobs (bees). The "bees" appear to fly sideways. I note that the facing vector of shulker bullets is always backwards from the direction of motion.

I'm wondering if we could get an option or special case to have the disguise's facing vector be the instantaneous velocity of a projectile, but not be updated if the projectile has velocity zero.

**Comment by libraryaddict** [comment]
Forgot to mention this is fixed in latest builds.
