### ISSUE TITLE
"ExplicitDisguises: true" Turns Creepers Passive

### ISSUE THREAD

**Issue by Webman97** [libraryaddict/LibsDisguises#449]
When setting `ExplicitDisguises: true`, Creepers that spawn naturally (and all Creepers in general) do not explode. They simply stare at you as if they _do not have permissions to explode?_

Do I need to grant a permission node to players that allows Creepers to explode?

Duplication Steps:
1. Install plugin, start server and generate config files
2. Shut down server, set `ExplicitDisguises: true` in config.yml
3. Start server, hit a Creeper. It will not explode, it will stare at you and nod.
4. Shut down server, set `ExplicitDisguises: false` in config.yml
5. Start server, hit a Creeper. It will explode as normal. _Note that reloading the config does not work, you need to shut down the server_

**Comment by Webman97** [comment]
Spigot-1.15.2
LibsDisguises-10.0.3

**Comment by libraryaddict** [comment]
Unable to replicate on my end.
Can you use /libsdisguises config - And tell me the output
Are you disguised during this?

**Comment by Webman97** [comment]
I am not disguised during this.

Before config regeneration:
![libsdisguises config](https://user-images.githubusercontent.com/2503727/79307189-85b2d180-7ec4-11ea-97aa-847598452d40.png)

After config regeneration (latest config per /libsdisguises config` feedback from above, still ran into this issue)
![libsdisguises config 2](https://user-images.githubusercontent.com/2503727/79308126-07572f00-7ec6-11ea-8726-add475d83d67.png)

**Comment by libraryaddict** [comment]
The problem is, the offending config option literally does nothing but check if you have permissions.
I've even checked the code that's being called from it.

Can you remove every other plugin but ProtocolLib and Lib's Disguises and see if the problem persists.
If it does, can you try replicating on a new server.

**Comment by Webman97** [comment]
I removed every plugin except for ProtocolLib & Lib's Disguises, the problem vanished.

After extensive investigation, it seems there is an issue elsewhere within my server setup/configuration. I've invested enough time to know for certain that this plugin does not cause the issue - my apologies!
