### ISSUE TITLE
Server shutting down with an InvocationTargetException on startup

### ISSUE THREAD

**Issue by macjuul** [libraryaddict/LibsDisguises#451]
During startup, the server shuts down while trying to load LibsDisguises due to the throwing of an InvocationTargetException

Stacktrace: https://pastebin.com/RdXBq9Vm
Java Version: openjdk version "11.0.6" 2020-01-14
Paper version: 1.15.2 193

While it is most likely unrelated, this warning is printed out before the error
https://pastebin.com/SV9VsGC8

**Comment by libraryaddict** [comment]
Going to need full startup log :\

**Comment by libraryaddict** [comment]
I'm also interested in your arguments for starting the server

**Comment by macjuul** [comment]
Oddly enough the crash has disappeared overnight without tweaking any configs or plugins. The plugin seems to work fine again now, and I can't seem to reproduce yesterdays error 😕 

Anyway, thanks for your response. I'll report back if the issue arises again

**Comment by libraryaddict** [comment]
I'm assuming you don't manage the server you host this on, likely the server hoster tweaked a setting without telling you.
