### ISSUE TITLE
Set configurable maximum slime size

### ISSUE THREAD

**Issue by SrLeojaco** [libraryaddict/LibsDisguises#452]
Actually players can set an slime up to size 50 without we being able to override that. Looking up the code values over 50 are always 50, but besides that it's still anoyying.

Propossal:

- Slime size by permission
- Slime size by config (preferred)

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/wiki/lib-s-disguises-setting-up-permissions/#negating-disguise-option-values

**Comment by SrLeojaco** [comment]
So complex. Finally found it https://github.com/libraryaddict/LibsDisguises/issues/307

>libsdisguises.disguise.slime.-setsize
