### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by khanhtung74** [libraryaddict/LibsDisguises#453]
https://pastebin.com/pjAHGw6j

I get this error spamming in my console , can you help me ?

**Comment by libraryaddict** [comment]
You need an older build of protocol lib for that version

**Comment by khanhtung74** [comment]
I use the lastest version of protocollib in spigot. Maybe i need to use dev build ?

**Comment by libraryaddict** [comment]
You need 4.3.0 or older

**Comment by khanhtung74** [comment]
Yeah , i use the 4.5.0 version

**Comment by khanhtung74** [comment]
I use this LibsDisguise build https://ci.md-5.net/job/LibsDisguises/282/

**Comment by libraryaddict** [comment]
I've told you how to fix it, this issue is locked.
