### ISSUE TITLE
missing options for packet.bed in 10.0.5

### ISSUE THREAD

**Issue by mckite** [libraryaddict/LibsDisguises#454]
There are no option for disabling the bed option which caused chunk send glitch.

PacketsEnabled:
  # This disables the animation packet. If a disguised entity sends a animation packet and they are using a non-living disguise. People will crash.
  # Disabling this also means that if a player disguised as a non-player leaves a bug. People will crash

  Animation: true
  # This disguises the collect packet. If a living entity disguised as a non-living entity picks up a item. People will crash. This fixes it
  # This also fixes people crashing if a item disguised as a sleeping player is picked up - Only true if Bed is enabled as well
  Collect: true
  # This disables a fix for when a disguised entity wearing armor dies, if the disguise can wear armor. It drops unpickupable items to anyone watching.
  EntityStatus: true
  # Entity equipment is the packets that are sent to ensure that a disguise has or doesn't have armor, and their held item.
  # Disabling this means that any disguises which can wear armor or hold items will show the armor/held item that the disguised is wearing.
  Equipment: true
  # This doesn't actually disable the packet. It would introduce problems. Instead it does the next best thing and caches the data.
  # This means that entity metadata will not change, and will only be sent in the spawn packet.
  # This is good if performance is extremely in need.
  # This is bad to disable unless you are ONLY going to use the disguises for decorations.
  # To be honest. This is basically "Disable entity animations". That option is called 'AddEntityAnimations' in the config but unlike that, this is always in effect.
  # Animations set by use of the api or through the disguise command are still in effect.
  Metadata: true
  # Movement packets are the biggest cpu hit. These are majorly used to ensure that the disguises facing direction isn't bugged up.
  # If you are using the Item_Frame disguise, when a packet is sent (Roughly every 2min) the disguise will bug up until they move.
  Movement: true
  # Disable this if you don't mind crashing everytime you see someone riding something disguised as a non-living entity
  Riding: true
  # When disguised as a wither skull, it sends a look packet every tick so that the wither skull is facing the right way.
  WitherSkull: true

**Comment by libraryaddict** [comment]
Because there's no bed packets.
