### ISSUE TITLE
The player who used the command does not see some mobs

### ISSUE THREAD

**Issue by WolverStones** [libraryaddict/LibsDisguises#461]
Some mobs are not visible (for /dis player), and need to change the world in order to load..

**Comment by libraryaddict** [comment]
Can you provide your latest.og

**Comment by WolverStones** [comment]
ProtocolLib: https://ci.dmulloy2.net/job/ProtocolLib/447/
Lib's Disguises 10.0.6
PaperSpigot 1.15.2 Build 227

They use the command but I can't see the mob ..
https://prnt.sc/s8b0z6 


Log: https://pastebin.com/4yG5DmKL


[01:34:05] [Server thread/INFO]: WolverStone issued server command: /dis Ender_Dragon
[01:34:05] [Server thread/WARN]: [LibsDisguises] Scoreboard conflict, the collisions for a self disguise player team has been unexpectedly modifed!


It looks like the plugin will have a problem with this
https://www.mc-market.org/resources/14009/

**Comment by libraryaddict** [comment]
Is this an issue with self disguises, more notably the "tall" versions not working?
That's due to a new config option which auto hides tall disguises.
You can disable this in the config, the newer builds have it disabled by default.
