### ISSUE TITLE
Disguises still broken with Paper, for latest 227 build.

### ISSUE THREAD

**Issue by Fonzee9** [libraryaddict/LibsDisguises#462]
Using latest version of ProtocolLib, and LibsDisguises build 548 and disguises for animals and players don't work.

**Comment by Fonzee9** [comment]
![2020-04-30_09 34 08](https://user-images.githubusercontent.com/21323258/80657569-f4119b00-8a51-11ea-99e0-9d553c2cd2ac.png)

**Comment by Fonzee9** [comment]
![Uploading 2020-04-29_19.46.24.png…]()

**Comment by libraryaddict** [comment]
Is this an issue with self disguises, more notably the "tall" versions not working?
That's due to a new config option which auto hides tall disguises.
You can disable this in the config, the newer builds have it disabled by default.

**Comment by Fonzee9** [comment]
Thank you
