### ISSUE TITLE
There is an update ready message does not say what plugin

### ISSUE THREAD

**Issue by Klawdek** [libraryaddict/LibsDisguises#463]
There is a update ready to be downloaded! You are using v9.9.9, the new version is v10.0.6!
This is the message in my console.  Since I have a list of my plugins with the versions in one column I was able to skim down that column and guess that it was from LibsDisguises.  It is a minor issue but I thought you might want to know about it.

**Comment by libraryaddict** [comment]
Update message has since changed.
