### ISSUE TITLE
An internal error has occurred while attempting to perform this command

### ISSUE THREAD

**Issue by DruggedTurtle** [libraryaddict/LibsDisguises#465]
When I try to do any command within this plugin it says 'An internal error occurred while attempting to perform this command'.

When this occurs, the user who tried to do the command either turns invisible or freezes - but on their screen they are moving around freely.

Server is running Spigot and is on 1.14.4

**Comment by DruggedTurtle** [comment]
This is the error I get below within the console:
-------------------------------------------------

05.05 17:02:40 [Server] Server thread/INFO TestMunkay issued server command: /disguise player TestMunkay setSkin DruggedTurtle
05.05 17:02:40 [Server] Server thread/ERROR null
05.05 17:02:40 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'disguise' in plugin LibsDisguises v10.0.8
05.05 17:02:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
05.05 17:02:40 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
05.05 17:02:40 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
05.05 17:02:40 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
05.05 17:02:40 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
05.05 17:02:40 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
05.05 17:02:40 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
05.05 17:02:40 [Server] INFO at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:1210) ~[?:?]
05.05 17:02:40 [Server] INFO at me.libraryaddict.disguise.disguisetypes.Disguise.startDisguise(Disguise.java:1058) ~[?:?]
05.05 17:02:40 [Server] INFO at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.startDisguise(PlayerDisguise.java:537) ~[?:?]
05.05 17:02:40 [Server] INFO at me.libraryaddict.disguise.commands.disguise.DisguiseCommand.onCommand(DisguiseCommand.java:77) ~[?:?]
05.05 17:02:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Spigot_Latest_1.14.4.jar:git-Spigot-56f8471-3e3818b]
05.05 17:02:40 [Server] INFO ... 17 more

**Comment by libraryaddict** [comment]
What version of Lib's Disguises are you using/

**Comment by DruggedTurtle** [comment]
LibDisguises-10.0.8

**Comment by libraryaddict** [comment]
Can you provide the latest.log file?

**Comment by libraryaddict** [comment]
Actually, it sounds like you need to update ProtocolLib

**Comment by DruggedTurtle** [comment]
The version of ProtocolLib I have was last updated 22nd September 2018 - I take it that is outdated now?

**Comment by libraryaddict** [comment]
Almost 2 years old, yeah.

**Comment by DruggedTurtle** [comment]
Thanks - I had the outdated Bukkit version, didn't realise there was a separate Spigot version. That's solved it now.
