### ISSUE TITLE
RuntimeException, Packet related

### ISSUE THREAD

**Issue by yakovliam** [libraryaddict/LibsDisguises#466]
Server version: `Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

Entire Stack Error:
```
[20:52:14 INFO]: yakovliam issued server command: /d cow
[20:52:14 INFO]: yakovliam lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
```

Steps: `/d cow` (only tested w/ cow)

Exact line where the issue is happening: `DisguiseUtilities.java LN 1924`
Same line below:
```
            manager.sendServerPacket(player,
                    manager.createPacketConstructor(Server.NAMED_ENTITY_SPAWN, player).createPacket(player));
```

How do I know this? I debugged for about an hour and commented out packet-related lines to see if any difference was shown. This is the only line that, if commented out, does _not_ cause any issues. My guess is that this is a Paper compatibility issue, but I can't know for sure without debugging for another few hours. I'd submit a PR with the line removed, but I am not sure what it actually does.

**Comment by libraryaddict** [comment]
Don't submit a PR :P
Are you on latest release or dev build? Because latest dev build is experimental

**Comment by yakovliam** [comment]
Whatever the latest build is of the master branch.

**Comment by libraryaddict** [comment]
That's the dev build then.

Can you use "/ld update! release"
