### ISSUE TITLE
Can not see own disguise

### ISSUE THREAD

**Issue by bloggy** [libraryaddict/LibsDisguises#467]
After updating from 1.13.2 to 1.15.2 I am no longer able to see my own disguise (as another player).
I did:
/disguise player anticos
But nothing changed for me. Other player's indeed can see my disguise.
Same issue when disguising another player with another player. 

Versions:
This server is running Tuinity version git-Tuinity-"9616aa9" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

[LibsDisguises] Loading LibsDisguises v10.0.8

**Comment by libraryaddict** [comment]
Update to latest dev build or reverse tall disguises config

**Comment by bloggy** [comment]
Updated to latest and I see my disguise but now there is another bug, look at this:
https://i.imgur.com/IqCzALa.png

**Comment by libraryaddict** [comment]
Did you turn on armorstands in config?

**Comment by bloggy** [comment]
config:
https://hastebin.com/eyikenatot.makefile

**Comment by libraryaddict** [comment]
Are you using the plugin "TAB"?

**Comment by bloggy** [comment]
No, I don't use this plugin.

**Comment by libraryaddict** [comment]
Fixed in the next build

**Comment by bloggy** [comment]
Alright, gonna test it then :-)
