### ISSUE TITLE
Task #16892 for LibsDisguises v10.0.8 generated an exception

### ISSUE THREAD

**Issue by juliacorco** [libraryaddict/LibsDisguises#468]
The plugin works, but every time anyone on my server disguises, a million errors are spit into the console. Here's the paste:
https://pastebin.com/jCHZVR5e
(I didn't paste the entire thing because it's essentially the same error over and over again)
Anyone know why this is happening? I don't know what "Task #16892" is or how to fix it.
Thank you!

**Comment by libraryaddict** [comment]
Plugin doesn't support Craftbukkit, update to spigot.
