### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by GamerPro0505** [libraryaddict/LibsDisguises#470]
When I disguise the camera just drifts away from me

**Comment by libraryaddict** [comment]
Can you give me a picture or video

**Comment by GamerPro0505** [comment]
here is the video https://1drv.ms/u/s!Aklkm9a5OdxAryxlvU5RlyEIcofJ?e=b6PtWf I had to make it a onedrive file because it does not support the original file. also sorry it took me so long

**Comment by libraryaddict** [comment]
If you're talking about "being pushed around" use /ld scoreboard

If you're talking about the self disguise not being 100% where you are, remember that it's sent by the server and it's effectively a fake mob spawned where you are. Because I can't change your own model to the disguise model.
