### ISSUE TITLE
Disguised mob stuck in portal

### ISSUE THREAD

**Issue by x1p** [libraryaddict/LibsDisguises#476]
When disguised, you can see yourself as a mob (selfview)
When you try to pass through a nether portal, you get stuck on the destination side of the portal.
When you try to pass through an end portal, you enter the end and can't move anymore.

Undisguising doesnt help. The only way to get out of this situation is teleporting by means of home, warp or tppos.

Is there something to prevent being stuck?

LibsDisguises-10.0.12 Premium
default config
Paper 1.15.2

**Comment by libraryaddict** [comment]
Are you up to date on Paper and ProtocolLib?

If yes, what versions specifically are you using?

**Comment by x1p** [comment]
ProtocolLib build 456
Purpur 1.15.2 build 585 equals Paper 1.15.2 build 332

**Comment by libraryaddict** [comment]
You could try the dev builds of Lib's Disguises, though I'm not sure it'd help.

The other thing I can think of is disabling anti-xray and seeing if that fixes the issue.

**Comment by x1p** [comment]
I switched the test server back to paper, xray is default off here. Tried the latest build 611. No luck yet.

**Comment by libraryaddict** [comment]
Going to look into it tomorrow, but I need to know how to reproduce it.

For starters, does it happen 100% of the time? What plugins do you use? Does it still occur when using just Lib's Disguises and ProtocolLib?
