### ISSUE TITLE
Lib's Disguises wont start 

### ISSUE THREAD

**Issue by Honzzzox** [libraryaddict/LibsDisguises#484]
https://pastebin.com/fvN3d4XG

CraftBukkit 1.14.4 server
using lib's disguises version 9.8.4 
ProtocolLib 4.5.0 gradle

Can someone help me with this?

**Comment by libraryaddict** [comment]
Please use spigot not craft bukkit

**Comment by Honzzzox** [comment]
okay thanks, my bad

**Comment by Honzzzox** [comment]
still says it couldnt load libs disguises

**Comment by libraryaddict** [comment]
Can you provide your latest.log?

**Comment by Honzzzox** [comment]
[latest.log](https://github.com/libraryaddict/LibsDisguises/files/4803975/latest.log)
