### ISSUE TITLE
Disguised entities are not recognized as player objects

### ISSUE THREAD

**Issue by malonnnn** [libraryaddict/LibsDisguises#486]
I'm not sure if the title is accurate, but it's my best guess.

The bug is that a disguised player can no longer be tab-completed, and hearts don't appear in the tab menu

/tp Supermalon - would work
/tp Supermalo - would not work, it would say "that person is not online", basically autocomplete not working, requires that last "n"

Basically you cannot press TAB to autocomplete, and the server does not automatically autocomplete incomplete player names

https://i.imgur.com/vpbpCQh.png (small red text to read)

https://i.imgur.com/yfQuIc0.png (Frenchi is missing from the tab list, related to the prev pic)

**Comment by libraryaddict** [comment]
This might just be a way Minecraft works. I'm guessing you're hiding player names from tab?
LD doesn't prevent player names from tab completing.

**Comment by malonnnn** [comment]
I'm hiding Player disguises from tab.

HideDisguisedPlayersFromTab: false
ShowPlayerDisguisesInTab: false

The above works fine, all autocompletion is good

HideDisguisedPlayersFromTab: true
ShowPlayerDisguisesInTab: true

autocomplete does not work for vanilla minecraft commands when both are set to true.

If you're confident that it's not libsdisguises, just leave this closed and I'll just not used disgusied icons.
