### ISSUE TITLE
1.16 IllegalArgumentException

### ISSUE THREAD

**Issue by jmanpenilla** [libraryaddict/LibsDisguises#488]
https://mcpaste.io/7139d5b8ace040f1

I get this stacktrace every time I run /d. The disguise works fine in game though.

I am using version compiled from latest commit to master

**Comment by libraryaddict** [comment]
I don't know what you're running

**Comment by jmanpenilla** [comment]
Sorry for not being more clear, but I'm running the latest 1.16.1 spigot build. I will re test with the new changes you pushed and see if the issue persists

**Comment by libraryaddict** [comment]
I prefer you try the latest jenkins build

**Comment by jmanpenilla** [comment]
Did not know of that, will do

**Comment by jmanpenilla** [comment]
Just tested with the latest build from Jenkins and got an identical result
[https://mcpaste.io/d3a4ae4e1fe97cd2](https://mcpaste.io/d3a4ae4e1fe97cd2)

**Comment by jmanpenilla** [comment]
My log file: https://pastebin.com/8cfqsUZZ, my config file: https://pastebin.com/1TvGF8v6 and my disguises file: https://pastebin.com/Fjp6gXrn

**Comment by libraryaddict** [comment]
Update ProtocolLib

**Comment by jmanpenilla** [comment]
I just tested with the latest build off of their [Jenkins](https://ci.dmulloy2.net/job/ProtocolLib/) and got the same result
My log file: https://pastebin.com/UtnanmDt, my config file: https://pastebin.com/QWyrF7fc and my disguises file: https://pastebin.com/gsxLWE1A
