### ISSUE TITLE
All disguises are invisible

### ISSUE THREAD

**Issue by Nibrock** [libraryaddict/LibsDisguises#492]
When I use the disguise command, it says I'm now disguised as that mob or object, and the height and everything is right, it's just completely invisible. 

Running PaperSpigot 1.16.1 # 90 
& Latest version of ProtocolLib
Plugins (36): Admin-GUI, AuctionMaster, ChatFeelings, ChestSort, CustomDeathMessages, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, GSit, HeadsInventory, HeadsPluginAPI, Holograms, HologramsPlaceholders*, LibsDisguises, LuckPerms, MoneyDrops*, MyCommand, PixelPrinter, PlaceholderAPI, PlayerGUI, ProtocolLib, ShopGUIPlus, SignShop, SignShopGuardian, SkinsRestorer, SlotMachine, TAB, TimeIsMoney*, Towny, TownyChat, TownyNameUpdater, Vault, Wild, WorldEdit, WorldGuard

This is the error I get in the console:

13.07 10:04:39 [Server] WARN java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: 1}, {Type: input instanceof interface net.minecraft.server.v1_16_R1.Packet, Index: 0}, {Type: Exact double, Index: 2}, {Type: input instanceof interface java.util.Collection, Index: 3}], paramCount=4}
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.reflect.FuzzyReflection.getConstructor(FuzzyReflection.java:558)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.wrappers.WrappedAttribute$Builder.build(WrappedAttribute.java:375)
13.07 10:04:39 [Server] WARN at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.constructSpawnPackets(PacketHandlerSpawn.java:96)
13.07 10:04:39 [Server] WARN at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.handle(PacketHandlerSpawn.java:68)
13.07 10:04:39 [Server] WARN at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:69)
13.07 10:04:39 [Server] WARN at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerViewSelfDisguise.onPacketSending(PacketListenerViewSelfDisguise.java:74)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.NetworkManager.b(NetworkManager.java:288)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.NetworkManager.dispatchPacket(NetworkManager.java:244)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.NetworkManager.sendPacket(NetworkManager.java:220)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1630)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.PlayerConnection.sendPacket(PlayerConnection.java:1603)
13.07 10:04:39 [Server] WARN at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
13.07 10:04:39 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13.07 10:04:39 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:690)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:675)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:401)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786)
13.07 10:04:39 [Server] WARN at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740)
13.07 10:04:39 [Server] WARN at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:2104)
13.07 10:04:39 [Server] WARN at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:2479)
13.07 10:04:39 [Server] WARN at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:1163)
13.07 10:04:39 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
13.07 10:04:39 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
13.07 10:04:39 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
13.07 10:04:39 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by libraryaddict** [comment]
Provide latest.log please

**Comment by Nibrock** [comment]
https://pastebin.com/v4BmPdfD

**Comment by libraryaddict** [comment]
Use latest dev build of protocol lib
