### ISSUE TITLE
Option to snap falling_block entity to block center.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#497]
Would it be possible to add an option to snap falling_block disguises to the center of the block you are standing on? For gamemodes such as BlockHunt so you are perfectly symmetrical with other blocks and have less perceived movement stutter with the update rate.

**Comment by libraryaddict** [comment]
Use /dhelp falling_block next time

**Comment by mibby** [comment]
Apologies, that setting escaped me. However I noticed blocks seem to snap to the standing block rounded down. If you are a block, cauldron, or potted plant for example on top of a slab, you are inside the slab. Small disguises like potted plants are inside the slab, making you invisible. 

Whereas when you try to place a potted plant normally, it is floating in the air.

**Comment by mibby** [comment]
Examples;

Not grid locked.
![link](https://i.imgur.com/S56dLu1.png)

Grid locked.
![link](https://i.imgur.com/rRisEVF.png)

Area is a bottom slab on top of a top slab. Nothing else underneath.

**Comment by libraryaddict** [comment]
Fixed in latest builds

**Comment by mibby** [comment]
Thanks, I'll give it a test in a few. I also noticed farmland is broken and sends you below as well.

**Comment by libraryaddict** [comment]
Also fixed.

**Comment by mibby** [comment]
Confirmed fixed, thanks very much!
