### ISSUE TITLE
Option to hide player hitbox.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#499]
Is it possible to add an option to mask / hide the player hitbox? Players can cheat in games such as BlockHunt by turning hitboxes on with F3 + B.

Examples;

![link](https://i.imgur.com/lkJzcN7.png)
![link2](https://i.imgur.com/nn6OeRk.png)
![link3](https://i.imgur.com/io9qth0.png)

**Comment by libraryaddict** [comment]
But how?

**Comment by mibby** [comment]
Since it works based on line of sight, would covering the player in falling_block barrier blocks prevent the hitbox from appearing?

**Comment by libraryaddict** [comment]
Doubt it

**Comment by mibby** [comment]
Tested it, barrier blocks don't seem to obscure hitboxes. So not entirely sure on how to fix either. :(

**Comment by libraryaddict** [comment]
Yeah, impossible ;)
