### ISSUE TITLE
Disguised as Falling Block

### ISSUE THREAD

**Issue by LoXR** [libraryaddict/LibsDisguises#508]
Tried using the latest DEV build in hope it fixed the blocks in the Hide N Seek Minigame plugin:https://www.spigotmc.org/resources/hideandseek.9777/
But sadly it never worked & the only build that worked was #654. This is what shows if on the latest: https://mcpaste.io/18069f1d54578c75
Server Version is 1.12.2 aswell.

**Comment by libraryaddict** [comment]
Opps, forgot to close this issue. Fixed in latest dev build
