### ISSUE TITLE
Disguises can't be controlled

### ISSUE THREAD

**Issue by Caketans** [libraryaddict/LibsDisguises#509]
the owner can't control the disguise, he is just teleported to the same spot and walk out of it.

**Comment by libraryaddict** [comment]
I need your latest.log

**Comment by Caketans** [comment]
sorry it took me this long, i didn't knew exactly how to get the log, it wasn't generating logs for some reason, this is what it shows on my server whenever i try to use a disguise on worldcontroller plugin from dream or force it from any disguise commands, some times i can move then when i use a command directly but have no view and can't attack..

https://pastebin.pl/view/9d92284b

Idk if you can help me or if i'm in the right place, if not thank you anyways

**Comment by libraryaddict** [comment]
Update Libs Disguises
