### ISSUE TITLE
SUGGESTION: Disguises' ambient sounds.

### ISSUE THREAD

**Issue by IIPedro** [libraryaddict/LibsDisguises#510]
Might be tough to implement, but ambient sounds would make disguises more convincing for trolling. Right clicking could do the trick. In case of multiple ambient sounds, make it so if you change inventory slots the sound changes. Example: creeper hisses on slot 1 and 2, creeper exploding on slot 3.

**Comment by libraryaddict** [comment]
Sorry, this will not be implemented.
