### ISSUE TITLE
[Suggestion] Add option to disable automatic head rotation / lookAt

### ISSUE THREAD

**Issue by LoneDev6** [libraryaddict/LibsDisguises#512]
Would be cool to disable the head rotation of disguises.

Thanks all

**Comment by libraryaddict** [comment]
Already implemented in the latest dev builds.

**Comment by LoneDev6** [comment]
Can you please provide me an example or the commit link?
Thanks

**Comment by libraryaddict** [comment]
Setlockpitch I believe
