### ISSUE TITLE
Question: Is there a way to check the current mob animation?

### ISSUE THREAD

**Issue by LoneDev6** [libraryaddict/LibsDisguises#513]
Hello!
Is there a way to check the original mob animation or if it's walking/swimming?
Thanks a lot!

**Comment by libraryaddict** [comment]
getEntityPose on FlagWatcher? Otherwise I'm not sure on what spigot api offers

**Comment by LoneDev6** [comment]
Thanks for the info!

Sadly these are the only poses available:
```
    STANDING,
    FALL_FLYING,
    SLEEPING,
    SWIMMING,
    SPIN_ATTACK,
    SNEAKING,
    DYING;
```
Seems there is no way to check if a mob is walking other than checking if position is changed

**Comment by libraryaddict** [comment]
Correct. I can't tell either.

**Comment by libraryaddict** [comment]
Oh I misunderstood slightly.

If the entity is moving, the model will walk. It's not an entity pose.

**Comment by LoneDev6** [comment]
Yes exactly, is there a method to know if the entity is moving?
Thanks!

**Comment by libraryaddict** [comment]
No
