### ISSUE TITLE
[Suggestion] Customize disguise height/hitbox

### ISSUE THREAD

**Issue by LoneDev6** [libraryaddict/LibsDisguises#514]
Would be cool to be able to customize entity height or hitbox, this would allows devs to change collisions behaviours between disguises.

For example I have a SQUID which I disguised to ZOMBIE.
Sadly the zombie looks like it's partially walking on the water and I'd prefer it to be underwater.

Another solution would be to be able to set a position offset for the fake entity so that it would always be sent to the client with a shifted location, in this case Y-2 or so.

Thanks a lot for your efforts

**Comment by libraryaddict** [comment]
Added y modifier to disguises, you must be OP if you're a player to access this to prevent abuse.
