### ISSUE TITLE
mob disguised as exp orb cannot attack with melee attack

### ISSUE THREAD

**Issue by hkkongou** [libraryaddict/LibsDisguises#529]
mob disguised as exp orb cannot attack with melee attack, we used mythicmobs with lib disguise function , we cannot use sword or hand to attack exp orb disguised zombie, we can only use arrow and bow to attack it.

**Comment by libraryaddict** [comment]
Not a bug, experience orb has no hit box.

**Comment by hkkongou** [comment]
wait, then how come arrow can attack 🤔

**Comment by libraryaddict** [comment]
BEcause the hitbox is client sided.
