### ISSUE TITLE
Tropical fish disguise poses have strange orientation.

### ISSUE THREAD

**Issue by totemo** [libraryaddict/LibsDisguises#530]
The tropical fish disguise has the fish lying on its side for all `setEntityPose` enumeration values except `SLEEPING`, where it has it's head is pointing up along the Y axis and the top-bottom line of the body points left-right perpendicular to the direction of player motion.

I think it's a bug to not have the normal `SWIMMING` pose be the same orientation that a fish would normally adopt, in-game. (Although arguably `STANDING` is also valid, but that could be purposed for a "fish standing on it's tail" pose.)

It would be nice if the `SLEEPING` pose could be the current sideways orientation.

**Comment by libraryaddict** [comment]
Can you try summon a fish outside of water and see if it does the same thing.

**Comment by totemo** [comment]
Ah that puts an interesting complexion on it. The disguise is true to the behaviour of a fish when out of the water, and has the correct orientation when in the water. In the water, the sleeping pose is still mouth up, tail down.

Would you consider allowing `setEntityPose SWIMMING` to override the pose on land, or is that defined by the client and out of your control?

**Comment by libraryaddict** [comment]
Defined by the client and out of my control. You can see this if you somehow glitch a fake water block to appear that the server doesn't know about.

**Comment by totemo** [comment]
Thank you for your time.
