### ISSUE TITLE
Failed to find a registered ID, flagWatcher

### ISSUE THREAD

**Issue by hkkongou** [libraryaddict/LibsDisguises#531]
this error keep popping out , don't know what does this mean and never use related features
![image](https://user-images.githubusercontent.com/61608872/103184244-22ea5480-48f2-11eb-840f-b32da03ef88a.png)

plugin version:
![image](https://user-images.githubusercontent.com/61608872/103184257-3f868c80-48f2-11eb-95d8-6147f4eb7388.png)

server version:
![image](https://user-images.githubusercontent.com/61608872/103184266-46ad9a80-48f2-11eb-8ddd-eff07e1d2993.png)

**Comment by libraryaddict** [comment]
Forgot to close this, it's fixed in latest dev builds
