### ISSUE TITLE
Heart animations cancelled on damage

### ISSUE THREAD

**Issue by alfiejsmith** [libraryaddict/LibsDisguises#538]
Using the latest download from Spigot, on a Paper 1.16.4 server, heart animations seem to not work / render when taking damage. It works when undisguised, and occurs when disguised through `/disguise` or the `DisguiseAPI`

Running LibsDisguises v10.0.21
Running ProtocolLib 4.6.0-SNAPSHOT-b492

A gif of the issue can be seen here: https://i.imgur.com/QbKWqIv.gif

/ver output:
![ver output](https://user-images.githubusercontent.com/42497992/103847499-49e61a80-5098-11eb-8a19-e04f0d42c56e.png)

/pl output:
![pl output](https://user-images.githubusercontent.com/42497992/103847548-6da96080-5098-11eb-818f-8df6656bb5db.png)

**Comment by libraryaddict** [comment]
Are you sure? Punching seems to display no hearts, as is vanilla. But using a wooden sword displays hearts.
This is both for a disguise and non-disguise.

Not sure that falling blocks should be playing hearts as well, but eh.
