### ISSUE TITLE
Cauuldron issue 1.7.10 1231.2.209

### ISSUE THREAD

**Issue by micmou** [libraryaddict/LibsDisguises#54]
Using Latest Dev Build and ProtocolLib Cauldron Version

Could not pass event PlayerMoveEvent to LibsDisguises v8.2.6-SNAPSHOT

MCMA Log Most Complete log I know forge permittor spews stuff too but that is working
http://dev.bukkit.org/paste/10918/

**Comment by NavidK0** [comment]
Just post the error next time, not the entire file. Resolved.
