### ISSUE TITLE
Teleport Message spam

### ISSUE THREAD

**Issue by trilliumhq** [libraryaddict/LibsDisguises#540]
My players are getting this message when they teleport or sleep in bed on latest version of the plugin.
When I remove LibsDisguises the messages are gone....

![image](https://user-images.githubusercontent.com/69016902/104115399-1516d500-52dd-11eb-80d7-aff9257d4a0c.png)

**Comment by libraryaddict** [comment]
Sir, these issues are meant to report bugs with the free and premium versions of the program.

Unfortunately, pirated versions of the plugin do not get supported.
