### ISSUE TITLE
Stop it from downloading protocollib!

### ISSUE THREAD

**Issue by roast247** [libraryaddict/LibsDisguises#541]
How do I Stop it from downloading protocollib!

**Comment by libraryaddict** [comment]
Can you outline why you don't want it to download ProtocolLib?

This should only occur when your build of ProtocolLib is fatally outdated, or missing.

**Comment by roast247** [comment]
why do I need it? Why does the dman plugin ping different IPs? Why does it decide to "auto update" Even when I configure it not too.

**Comment by libraryaddict** [comment]
You need it if you want Libs Disguises to work. And Libs Disguises auto updates it only if the ProtocolLib won't work on your current version

**Comment by roast247** [comment]
yeah well now plugin metrics won't stop popping up in the plugins folder after deleting your plugin. How do I stop it?

**Comment by libraryaddict** [comment]
I don't understand.

You're aware that libsdisguises requires protocol lib? 
Metrics can be disabled

**Comment by roast247** [comment]
I deleted all the plugins but plugin metrics still pops up! why!?

**Comment by libraryaddict** [comment]
Because it's part of spigot I believe
