### ISSUE TITLE
LD_NoName Issues

### ISSUE THREAD

**Issue by Kqmu** [libraryaddict/LibsDisguises#548]
Hey, I've been Using Lib's Disguises for awhile now for the support with Mythic Mobs, and making custom mobs, and after the new Update Removing The Blank Names and replacing it with LD_NoName instead, is messing up with our Tab Plugin, before when it was a Blank name it showed the skin and then updates and disappears but after the Update they just stay in tab creating this 
![image](https://user-images.githubusercontent.com/70139586/107254212-184cd000-6a05-11eb-90c0-5a3e1162d309.png)
And the only way to fix it, is to have the Client ReLog, but I hate just having my players relog when it gets overcrowded, and I was wondering if there is a way to disable it ( I tried down grading to a prior Version ( 10.0.21 ) which is the version right before the change, but after the restart it still registers it as ( 10.0.23 ) which is after causing this issue, if you have any advice for me. Please Respond here or in DMs on Discord Kamu#8525, Thank you! have a wonderful day!

**Comment by libraryaddict** [comment]
I've reverted the changes and this should hopefully no longer be an issue, though I was unable to test the build.
