### ISSUE TITLE
Entity instance errors

### ISSUE THREAD

**Issue by KasearMC** [libraryaddict/LibsDisguises#550]
1.16.5
Paper
LD: 10.0.24

there are a series of startup errors.

https://pastebin.com/JdFf4S1z

**Comment by libraryaddict** [comment]
Hi, I need the full startup log

**Comment by KasearMC** [comment]
sorry for the delay.
https://pastebin.com/FdumtGux

**Comment by libraryaddict** [comment]
Which version of Java? Could you try using a dev build, use `/ld update dev`

**Comment by KasearMC** [comment]
sorry for the delay, again.

the java version is: 11.0.8+10-LTS
i updated to the latest dev build and the error still persists.

**Comment by libraryaddict** [comment]
Took a deeper look into it, and I still can't see a good reason for that to happen. Best guess is a modified server.

As I can't replicate this on my end, are you able to see if a fresh server install + the plugins works properly.

It may be another plugin, or a server setting that interferes.
