### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Pindastruikgamer** [libraryaddict/LibsDisguises#553]
hey,
I got this plugin from the minehut server thing. so i'm trying to disguise myself or just try any command, but everytime i try i get: "An internal error occurred while attempting to perform this command". does anyone know how i can fix this?

**Comment by libraryaddict** [comment]
I need the error for any useful help.

**Comment by Pindastruikgamer** [comment]
oh, well lets just say i am not that good with all of this. The only thing i know is what i already said in the post above, that every time i try a command, i get that message. I dont really know how i can see those errors. Im sorry that i can't give anymore info about it, cause i don't know much about this stuff.

**Comment by libraryaddict** [comment]
Can you upload your latest.log file to a site like pastebin or gist and give the link here.

**Comment by libraryaddict** [comment]
Also, be sure you're on the latest release of Libs Disguises, and read console for any errors.
