### ISSUE TITLE
LibsDisguise & MythicMobs issues

### ISSUE THREAD

**Issue by Sodies** [libraryaddict/LibsDisguises#556]
In mythicmobs disguise option I had a mob that disguise as item. The mob can hit me but I can't. I even had ModifyBoundingBox: false in the disguise option in mythicmobs. Still doesn't work. 

`Disguise:
    Type: ITEM
    Item: GLOWSTONE_DUST
    ItemData: 0
    ModifyBoundingBox: false`

The item doesn't have hitbox. Even I set the mob type to ghast

Using 1.16.4 spigot 
Using both latest version of mythicmobs and libsdisguise that I've downloaded yesterday from the official site

**Comment by libraryaddict** [comment]
Not a bug. Disguise armorstand instead.
