### ISSUE TITLE
Cannot set falling block data

### ISSUE THREAD

**Issue by MarcoLvr** [libraryaddict/LibsDisguises#562]
Hi,
I have a problem with the apis. When i try to disguise to a falling block a player the plugin disguise it but without data. My Code:
`MiscDisguise disguise = new MiscDisguise(DisguiseType.FALLING_BLOCK, Material.WOOD, 5);
        disguise.setEntity(p);
        disguise.startDisguise();`
(minecraft version: 1.12)

**Comment by libraryaddict** [comment]
Use FallingBlockWatcher. 

FallingBlockWatcher watcher = (FallingBlockWatcher) disguise.getWatcher()
