### ISSUE TITLE
Even with the FallingBlockWatcher the block still remain oak (it had to be Dark Oak)

### ISSUE THREAD

**Issue by MarcoLvr** [libraryaddict/LibsDisguises#563]
`MiscDisguise disguise = new MiscDisguise(DisguiseType.FALLING_BLOCK);`
`FallingBlockWatcher watcher = (FallingBlockWatcher) disguise.getWatcher();`
           ` ItemStack stack = new ItemStack(Material.WOOD);`
        `    stack.setDurability((short) 5);`
        `    watcher.setBlock(stack);`
        `    disguise.setEntity(p);`
          `  disguise.startDisguise();`
I tried with this but the block still remain oak planks (version 1.12) 
the id (5) is correct.
![2021-05-31_19 45 26](https://user-images.githubusercontent.com/42388782/120227167-f643bb80-c248-11eb-9ecb-bbeeb1299349.png)

**Comment by libraryaddict** [comment]
I'd prefer if you used the previous issue instead of opening a new one, regardless it looks like a new bug indeed.

**Comment by libraryaddict** [comment]
Forgot to link this, but fixed in latest dev build
