### ISSUE TITLE
setskin not a method

### ISSUE THREAD

**Issue by 1-demon-slayer** [libraryaddict/LibsDisguises#565]
When i do /d player 1_demon_Slayer setSkin Skeppy 
I get "Cant find Method 'setSkin'"

when i do /dishelp Player
I get:
![2021-06-03_08 40 52](https://user-images.githubusercontent.com/66424650/120654806-a4b54f80-c447-11eb-9226-8ec6c31e0168.png)

**Comment by libraryaddict** [comment]
Please upload your latest.log to a site such as pastebin, then give the link to that.

**Comment by 1-demon-slayer** [comment]
found what was wrong apparently Apexhosting had a cracked version
