### ISSUE TITLE
selfd error

### ISSUE THREAD

**Issue by Philippoius** [libraryaddict/LibsDisguises#566]
Selfd saves the current state (true/false)

But when it is set to true and a player disguises (for example "/dis cow") he does not see the disguise.
The player has to enter /selfd 2 times (one time to disable selfd and then enable it again) to see the own disguise.

**Comment by libraryaddict** [comment]
Can you provide your latest.log in a site such as pastebin.com

**Comment by Philippoius** [comment]
Unfortunately i cant provide the whole latest.log due to data protection.
But here is a shortened log file with all information regarding LibsDisguises.

https://pastebin.com/KDduiuSc

After entering "/dis creeper" all other players see the disguise.
By entering "/selfd" the first time nothing but the message that selfd is deactivated happens.
By entering this the second time everything works as intended for the current disguise.
