### ISSUE TITLE
Strange WARN in the paid version

### ISSUE THREAD

**Issue by sergservis** [libraryaddict/LibsDisguises#568]
Papper Spigot 1.12.2
https://pastebin.com/5ys6UTtS
Lib's Disguises 10.0.24

**Comment by libraryaddict** [comment]
Not enough information, I can see a strange stack trace which indicates that you're not even using a normal server.

My first guess is that you're using Java 16. My other guesses, I can't even begin.

If you need more support, I'll need you to provide your full startup log.
