### ISSUE TITLE
Error occurred while enabling LibsDisguises v10.0.25 (Is it up to date?)

### ISSUE THREAD

**Issue by cloakfox** [libraryaddict/LibsDisguises#572]
Full error: https://gist.github.com/cloakfox/ffa6b995086a245f0ac30efbc6d82e80

Running Airplane version git-Airplane-"a13c511" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
on Java 16

**Comment by libraryaddict** [comment]
That's not the full error. It also looks like you used /reload?

**Comment by cloakfox** [comment]
> That's not the full error. It also looks like you used /reload?
> 
> To go ahead with this, I'll need your actual server log. And for you to have restarted the server.

That is on a fresh server boot no reloads, I've attached full server log to this comment.
[latest.log](https://github.com/libraryaddict/LibsDisguises/files/6608227/latest.log)

**Comment by libraryaddict** [comment]
Use this jar

https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar

Apparently my genius of auto update if fails to startup, fails if there's another error in the updater.
So the real error has been suppressed, which this build aims to fix.

**Comment by cloakfox** [comment]
> Use this jar
> 
> https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar
> 
> Apparently my genius of auto update if fails to startup, fails if there's another error in the updater.
> So the real error has been suppressed, which this build aims to fix.

Getting this error with that build: https://gist.github.com/cloakfox/6e71d55de61f780055c040fdee7f9c25

Attached full log too

[latest.log](https://github.com/libraryaddict/LibsDisguises/files/6608290/latest.log)

**Comment by libraryaddict** [comment]
Ah, the genius of a plugin shading in the adventure text library but excluding classes without repackaging..

**Comment by libraryaddict** [comment]
https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar

Download it again, error should be fixed now.

**Comment by cloakfox** [comment]
> https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar
> 
> Download it again, error should be fixed now.

Same error I think
https://gist.github.com/cloakfox/9a53f2606f1159b97e04af3138ee1e49

[latest.log](https://github.com/libraryaddict/LibsDisguises/files/6608373/latest.log)

**Comment by libraryaddict** [comment]
Nope. You are using a build thats one version older. Redownload.

**Comment by cloakfox** [comment]
> Nope. You are using a build thats one version older. Redownload.

I double checked im running the build you send to me last, I was also confused.

**Comment by libraryaddict** [comment]
Same url, but different jar.

 Jenkins Build: #936
The newest is 937

**Comment by cloakfox** [comment]
> Same url, but different jar.
> 
> Jenkins Build: #936
> The newest is 937

I redownloaded just now and got same error

**Comment by cloakfox** [comment]
Can you send the direct link to latest build?

**Comment by libraryaddict** [comment]
Then can you provide your log file. That is the direct link. But here's another.

https://ci.md-5.net/job/LibsDisguises/937/artifact/target/LibsDisguises.jar

**Comment by cloakfox** [comment]
> Then can you provide your log file. That is the direct link. But here's another.
> 
> https://ci.md-5.net/job/LibsDisguises/937/artifact/target/LibsDisguises.jar

Got latest jar now, works with no errors. Thanks!
