### ISSUE TITLE
[LibsDisguises] Unhandled exception occured in onPacketSending(PacketEvent) 

### ISSUE THREAD

**Issue by taka1945** [libraryaddict/LibsDisguises#578]
https://pastebin.com/v2a7DfEX

server is running CraftBukkit version 3161-Spigot-f773da8-f81f499 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

LibsDisguises-945

**Comment by libraryaddict** [comment]
Error in PL
