### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) for LibsDisguises java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by taka1945** [libraryaddict/LibsDisguises#579]
plug-in version:
LibsDisguises dev #946

server version:
Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)

https://pastebin.com/f6cg61Pq

**Comment by libraryaddict** [comment]
Fixed in latest build
