### ISSUE TITLE
#961 java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init> /ld logs

### ISSUE THREAD

**Issue by taka1945** [libraryaddict/LibsDisguises#589]
Server : 1.17.1
Client: LibsDisguises #961

https://pastebin.com/iwXKN0sP

**Comment by libraryaddict** [comment]
For this I would need your full startup log. Such as /ld logs

**Comment by taka1945** [comment]
hi, 
    full startup log here , 
    https://pastebin.com/5ahn26BZ

**Comment by libraryaddict** [comment]
Wrong log, also can you update ProtocolLib if you haven't already, as well as your server Jar and tell me if this is still an issue.
