### ISSUE TITLE
ProtocolLib #529 latest ,  but LibsDisguises #962 still ask download  ProtocolLib 4.7.1 ? 

### ISSUE THREAD

**Issue by taka1945** [libraryaddict/LibsDisguises#590]
ProtocolLib #529 dump log link:

https://pastebin.com/7FJB739C

it's   version  4.7.0 not 4.7.1 or  has minimum version .

**Comment by libraryaddict** [comment]
Whoops, wonder how I missed that. Though the backup build number should have caught it, wonder why not.
