### ISSUE TITLE
Packet Event Error

### ISSUE THREAD

**Issue by SirCraftypants** [libraryaddict/LibsDisguises#592]
Paper Spigot 1.17

Libsdisguises #965

Installed, started up Server which was fine, ran around a bit and tested a few custom shields i created was blocking correctly, went to shut down the server as i usually do and found this error. I don't think it was related to any action i took as the above has no baring on libsdisguises and i never ran any libsdisguise functions/commands. 

It just happened.

https://paste.helpch.at/zopibexuro.rb

**Comment by SirCraftypants** [comment]
I created 3 custom model shields using a plugin named Itemsadder and i had all 3 in my action bar, i did hold down block and cycle through the 3 shields, that was the last thing i did before finding the error. That's all the info i have to provide.

**Comment by libraryaddict** [comment]
Update to 1.17.1
