### ISSUE TITLE
Unhandled exception number 128 occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by ErythroCraft** [libraryaddict/LibsDisguises#595]
Hello @libraryaddict 

After Installation v.10.0.26 your plugin create a bug in server console.

**full** on start up the server
https://pastebin.com/KW83WSGX

**simple** on stop the server
https://pastebin.com/7xSLkYmr

**Comment by TheIntelloBox** [comment]
I can confirm.

**Comment by libraryaddict** [comment]
Update ProtocolLib

**Comment by libraryaddict** [comment]
Was there even an error telling you to do so? Should've been
