### ISSUE TITLE
ERROR Unhandled exception

### ISSUE THREAD

**Issue by twistedh** [libraryaddict/LibsDisguises#597]
When ever trying to use the plugin, this error returns. On MC paper/spigot 1.17 with latest updates of this plugin and other req plugins. Not working on any of our servers hosted at shockbyte

19.07 01:07:18 [Server] ERROR Unhandled exception number 256 occured in onPacketSending(PacketEvent) for LibsDisguises
19.07 01:07:18 [Server] INFO java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.events.PacketContainer.getIntLists()'
19.07 01:07:18 [Server] INFO at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerEntityDestroy.onPacketSending(PacketListenerEntityDestroy.java:43) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
19.07 01:07:18 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:294) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:258) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1905) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1891) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ServerEntity.removePairing(ServerEntity.java:261) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2400) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2308) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2053) ~[patched_1.17.1.jar:git-Paper-103]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2074) ~[patched_1.17.1.jar:git-Paper-103]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:881) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:752) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:555) ~[?:?]
19.07 01:07:18 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[patched_1.17.1.jar:git-Paper-103]
19.07 01:07:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-103]
19.07 01:07:18 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-103]
19.07 01:07:18 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-103]
19.07 01:07:18 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-103]

**Comment by libraryaddict** [comment]
Can you provide your full log? Use pastebin or a similar paste service.

**Comment by libraryaddict** [comment]
Actually, disregard that. The issue is that you're on an outdated version of ProtocolLib
