### ISSUE TITLE
Watcher methods should be hidden if the disguise types ignose those flags

### ISSUE THREAD

**Issue by Yahiamice** [libraryaddict/LibsDisguises#603]
Pillagers, Vindicators, Ravagers, Witches and Evokers all have setCastingSpell available as a disguise parameter, which would make them raise their arms.
However, it only actually effects Evokers (and --despite their inability to cast spells--, Vindicators?), so it seems pretty useless to have it available

**Comment by libraryaddict** [comment]
This isn't a bug to be clear. It's Mojang exposing flags, me exposing those flags, but Mojang ignoring those flags.
