### ISSUE TITLE
How to spawn an item with ProtocolLib for one player ?

### ISSUE THREAD

**Issue by MrClean1337** [libraryaddict/LibsDisguises#607]
Hello and yes I know that this is the wrong section, but I think you guys are my **last hope** before giving up with ProtocolLib :/

4 years before, I used LibsDisguises for many many things!
It was and it is the best disguise plugin.
So I already know that there is a option to disguise as a "dropped_item".
This is very cool and I want to use these packets for my own plugin.

Im really really new to ProtocolLib, because in the past I used only NMS.
Any detailed tutorials are welcome for me :D

As far as I know, I need these two:
1. https://wiki.vg/Protocol#Spawn_Entity
2. https://wiki.vg/Protocol#Entity_Metadata

But im not really able to understand and spawn a item with ProtocolLib!
Im trying to spawn a item with this lines of code:
https://pastebin.com/Rz4nfT5i

But it just appears this:
https://i.imgur.com/Jbqt7LO.png

Why ? I just want to spawn an item with ProtocolLib for one player.
And in the code at the MetaData part, I really don't know how to attach an ItemStack to it.
Any ideas ?

Im using git-Tuinity-23 (MC: 1.17.1) and ProtocolLib v4.7.0

Thanks :)

**Comment by MrClean1337** [comment]
Or maybe you guys show me the lines of code in this repo, for my problem o.O

**Comment by libraryaddict** [comment]
The pic loooks like you spawned area effect cloud instead or something?

Maybe the wrong entity type id. I don't calculate it at compile time but run time using nms.

Nothing else sticks out.

**Comment by MrClean1337** [comment]
> The pic loooks like you spawned area effect cloud instead or something?
> 
> Maybe the wrong entity type id. I don't calculate it at compile time but run time using nms.
> 
> Nothing else sticks out.

How do you calculate it ?
How do you do this to create a packet like this ?
