### ISSUE TITLE
How to make armour not visible when disguised

### ISSUE THREAD

**Issue by HELPMEPLEASE0011** [libraryaddict/LibsDisguises#614]
What would the command be to say, turn in to a skeleton, not showing the armour that im wearing.
Much appreciated, Thanks!

**Comment by libraryaddict** [comment]
Set all four arguments to air. So air, air, air, Air

**Comment by HELPMEPLEASE0011** [comment]
so /d skeleton air air air Air?

**Comment by libraryaddict** [comment]
So /disguise skeleton setarmor air,air,air,air

**Comment by HELPMEPLEASE0011** [comment]
OK THX
Edit: sorry capas

**Comment by HELPMEPLEASE0011** [comment]
oWo please help it still shows elytra and my shield ._.

**Comment by libraryaddict** [comment]
Picture? I'm about to sleep

**Comment by HELPMEPLEASE0011** [comment]
ok

**Comment by HELPMEPLEASE0011** [comment]
gimmie a sec

**Comment by HELPMEPLEASE0011** [comment]
![Screen Shot 2021-08-29 at 9 45 32 am](https://user-images.githubusercontent.com/83633983/131233665-df0d3ec2-e954-40b9-9096-1af8a5d64651.jpg)
![Uploading Screen Shot 2021-08-29 at 9.45.32 am.jpg…]()

**Comment by HELPMEPLEASE0011** [comment]
btw its not visible but elytras there

**Comment by libraryaddict** [comment]
Assuming we're talking about the self disguise and not the stuff on the player itself.. Shields and elytra shouldn't be removed for the stuff on the player themselves as it would break interactions.

As for the skeleton disguise itself, mind providing your latest.log?

**Comment by HELPMEPLEASE0011** [comment]
i have the shield and elytra on my player, is it possible to hide that or do i have to take off?

**Comment by libraryaddict** [comment]
It should be hidden on the disguise, but the player will see it on themselves.

You can disable this in the config.
