### ISSUE TITLE
No marketplace entries found to handle Execution

### ISSUE THREAD

**Issue by voltywolty** [libraryaddict/LibsDisguises#618]
Hey all, I'm importing the LibsDisguises project into Eclipse, but I ran into an error. When I tried to import the project, I got this error: No marketplace entries found to handle Execution my-execution, in /LibsDisguises-master/pom.xml in Eclipse.

Is there a way I can fix this so I can use this with my plugin. Thanks.
![Screenshot 2021-09-15 173945](https://user-images.githubusercontent.com/36797676/133519211-16113716-caa4-4dac-84bf-158c9f3f45b5.png)

**Comment by libraryaddict** [comment]
I don't know what this error is, but the recommended way is to use it as a maven project, not importing the project itself.
