### ISSUE TITLE
DisguiseAPI.parseToString does not return correct values

### ISSUE THREAD

**Issue by JeffHD** [libraryaddict/LibsDisguises#621]
I have this code
`DisguiseType dis = DisguiseType.ARMOR_STAND;`
`MobDisguise mobDisguise = new MobDisguise(dis, false);`
`ArmorStandWatcher watcher = (ArmorStandWatcher) mobDisguise.getWatcher();`
`watcher.setInvisible(true);`
`watcher.setSmall(true);`
`watcher.setCustomNameVisible(true);`
`watcher.setMarker(false);`

after that i use `DisguiseAPI.parseToString(mobDisguise)` to get the disguise  and save it to my DB.
but the string in my DB looks like that:
ARMOR_STAND setInvisible  setDisguiseName "Armor Stand" setCustomNameVisible setMarker

if i load the entity and the disguise from DB and apply the disguise to the entity, the name of the entity shifts down to the bottom and i can't interact anymore with it.

the setMarker is the problem. when i remove setMarker from the string in my DB and than load the disguise, everything works again.

i tried `watcher.setMarker(false);` but the string have still the setMarker in it.

for now i take the disguise string and do `replace("setMarker","")` but that is not a long term solution

**Comment by libraryaddict** [comment]
Might have some wrong values mapped, I'll look into this shortly
