### ISSUE TITLE
Entity metadata leak 

### ISSUE THREAD

**Issue by Owen1212055** [libraryaddict/LibsDisguises#622]
https://github.com/libraryaddict/LibsDisguises/blob/d3d4df2d6522056e037e47a6bf86a7b1569b5925/src/main/java/me/libraryaddict/disguise/disguisetypes/Disguise.java#L795-L799

When removing the disguise, it seems that the metadata is removed and then readded again.

This causes a memory leak, albeit very little it does add up.
![image](https://user-images.githubusercontent.com/23108066/135355513-d50108ef-c722-4ee1-bda5-b141ddc98f40.png)

Running Version 10.0.26

**Comment by libraryaddict** [comment]
To clarify, you're saying the memory leak is that there is a metadata value right? Not that the metadata hangs around after supposedly being removed.

Should only be as many objects as there are players at most.

**Comment by Owen1212055** [comment]
> To clarify, you're saying the memory leak is that there is a metadata value right? Not that the metadata hangs around after supposedly being removed.
> 
> 
> 
> Should only be as many objects as there are players at most.

Ahh yea perhaps I didn't explain clearly. The issue was that they were sticking around after being removed. This was apparent as there were a large amount of these keys with weak hash maps.

**Comment by libraryaddict** [comment]
Just realized that this sounds less like a problem with Lib's Disguises, and more like a memory leak in the server itself.

What version of the server is this? Might have been fixed in later versions?

**Comment by Owen1212055** [comment]
> Just realized that this sounds less like a problem with Lib's Disguises, and more like a memory leak in the server itself.
> 
> 
> 
> What version of the server is this? Might have been fixed in later versions?

I don't recall there being any fixes related to this. But mostly I was considering that this was a libs disguises issue as it isn't clearing metadata correctly. And looking further, it doesn't seem that metadata is removed for entities even when they are removed. Fixing this would probably break anything that used this system with this strange behavior. However, we use a 1.16.5 Paper server.

**Comment by Owen1212055** [comment]
This fix doesn't account for entities, only players. x)

**Comment by libraryaddict** [comment]
Meh
