### ISSUE TITLE
1.18: ZombieWatcher.setUpsideDown and setCustomName not working.

### ISSUE THREAD

**Issue by MarioFinale** [libraryaddict/LibsDisguises#631]
When I try to set a mob upside down, it doesn't work. Same code was working on 1.17.1.
Code:
![image](https://user-images.githubusercontent.com/15223565/145942917-ab42ed2a-089d-4bfc-8ef7-685d9d390824.png)

Result:
![image](https://user-images.githubusercontent.com/15223565/145942940-f3cde4cd-ff95-4270-b6dd-66ad4ea3091b.png)

**Comment by DigitalJokerMan** [comment]
I am also experiencing the same issue. 1.18 broke something perhaps?

**Comment by libraryaddict** [comment]
Fixed
