### ISSUE TITLE
The skins disappear after I move away and return from the disguises.

### ISSUE THREAD

**Issue by aematsubara** [libraryaddict/LibsDisguises#632]
I'm basically having the same problem as this one: https://github.com/libraryaddict/LibsDisguises/issues/474
I didn't know whether to respond to it or create a new issue; here is a video of the problem.

https://www.youtube.com/watch?v=EE5ax5-05TQ

If I reconnect, they appear as they should.

More info:
* I'm disguising them in the onEnable() method of my plugin (Disguising the villagers as real players).
* LibsDisguises v10.0.27-SNAPSHOT
* Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
* I've also tested this error in 1.12 and 1.18 and the same thing happens.

**Comment by dado997** [comment]
I have this problem too, hope will be a fix for that

**Comment by jaylawl** [comment]
I am having this issue too. If this isn't preventable on the side of libsdisguises, i would like to ask instead: what _exactly_ causes this to happen? Because i'm willing to code a workaround on my end for this.

**Comment by libraryaddict** [comment]
I don't know specifically what causes it to happen when to the best of my knowledge it should already be worked around.

To discover more about the issue I'd need to mod a client to print off debug information, which I've just never found the time for.

To explain how skins work, the tab list entries contain the skin information and the tablist entries must still be in the tab when the player first sees the player entity, and thus actually apply the skin to the player entity.

When the player entity is destroyed on the client side, they must see the tablist entry again to render the skin on the entity.

The reason it turns into steve is because LD hides the tab list entry as soon as it can. Which means there's no skin data to apply to the entity.

**Comment by jaylawl** [comment]
@aematsubara 

I was playing around with this code snipped:
```
    public static void resendDisguisePackages(final @NotNull PlayerDisguise playerDisguise) {
        final PacketContainer addTab = DisguiseUtilities.getTabPacket(playerDisguise, EnumWrappers.PlayerInfoAction.ADD_PLAYER);
        final PacketContainer deleteTab = addTab.shallowClone();
        deleteTab.getPlayerInfoAction().write(0, EnumWrappers.PlayerInfoAction.REMOVE_PLAYER);
        try {
            for (final Player player : Bukkit.getOnlinePlayers()) {
                ProtocolLibrary.getProtocolManager().sendServerPacket(player, addTab);
                new BukkitRunnable() {
                    @Override
                    public void run() {
                        try {
                            ProtocolLibrary.getProtocolManager().sendServerPacket(player, deleteTab);
                        } catch (InvocationTargetException exception) {
                            exception.printStackTrace();
                        }
                    }
                }.runTaskLater(JNPCs.getInstance(), 20L);
            }
        } catch (InvocationTargetException exception) {
            exception.printStackTrace();
        }
    }
```

This method successfully "reloads" the skins for me. The packet code is copied from a private libsdisguises method

**Comment by jaylawl** [comment]
> I don't know specifically what causes it to happen when to the best of my knowledge it should already be worked around.
> 
> To discover more about the issue I'd need to mod a client to print off debug information, which I've just never found the time for.
> 
> To explain how skins work, the tab list entries contain the skin information and the tablist entries must still be in the tab when the player first sees the player entity, and thus actually apply the skin to the player entity.
> 
> When the player entity is destroyed on the client side, they must see the tablist entry again to render the skin on the entity.
> 
> The reason it turns into steve is because LD hides the tab list entry as soon as it can. Which means there's no skin data to apply to the entity.

Thank you for the detailed answer!

As things are right now, how is LibsDisguises handling this on a logic level? Are the tablist packets sent just once or is LibsD implementing a smart system that tries to re-send the tablist packages whenever a player has the entity loaded in their client?

**Comment by libraryaddict** [comment]
The entity is created by the server, and whenever that happens the server tries to send the tab list packets the same way.

To force them to load, it teleports the entity invisibly in front of the viewing player, then back to their real position and they're made visible again. This should be unnoticeable.

Sometimes the timing of the player disguise being in front of the player differs, but it shouldn't be a real issue. Again, this needs to be debugged on the client level.

**Comment by jaylawl** [comment]
Aight thank you. I will mess about more with re-sending of the tablist packages and report on my findings, if anything useful pops up.

**Comment by libraryaddict** [comment]
The issue is more of "Why does the skins not load, despite LD doing things 'correctly'", I don't think modifying LD itself will help too much finding that.

**Comment by jaylawl** [comment]
Oh yeah absolutely. I'm not saying the plugin is doing anything wrong; rather just trying to find a solution for a problem that people have. Nothing ever wrong with sharing findings/information
