### ISSUE TITLE
Error Spigot 1.8.3

### ISSUE THREAD

**Issue by trulywitty** [libraryaddict/LibsDisguises#64]
I also Have a problem on 1.8.3.
The plugins loads using 8.2.6 of LibsDuisguise
and Build #83 of ProtocolLib

The only things that I noticed is when I disguise as any creature It does not change a thing.

Here is my error paste
http://pastebin.com/YriBkwBL

Also I noticed with version #363 from http://ci.md-5.net/job/LibsDisguises/

I dont get that long error has. Any reason why that is?
Also disguise don't show up with that ether.

**Comment by MatteCarra** [comment]
Update your ProtocolLib.
http://ci.shadowvolt.com/job/ProtocolLib/

**Comment by NavidK0** [comment]
Resolved.
