### ISSUE TITLE
Display name for mobs doesnt appear (Mythic Mobs)

### ISSUE THREAD

**Issue by Jeeon112** [libraryaddict/LibsDisguises#640]
I recently updated my Lib's DIsguises and MythicMobs (free)  to their latest versions because I ran into an issue in my old version (1.16.5) where my custom mobs display names would be overwritten to their respective disguise names. for example,
SLSkelF:
  Type: ZOMBIE
  Disguise: SKELETON
  Display: '&BSkeletal Fighter'

The mob would spawn normally with the disguise however the displayname "&BSkeletal Fighter" does not appear, instead the display name is "Skeleton." I reloaded mythicmobs without Disguise: SKELETON and the display name appeared perfectly fine. I thought this was an outdated version issue so I updated the plugins Lib's Disguises, Mythic Mobs and even ProtocolLib to their latest versions however the same problem is present. 
Anyone have an idea how to fix this?

**Comment by libraryaddict** [comment]
Forgot to release. Try /ld update dev
