### ISSUE TITLE
Non-op players cannot interact with entities at all

### ISSUE THREAD

**Issue by SkytAsul** [libraryaddict/LibsDisguises#641]
When using premium version, non-op players cannot interact with entities (the PlayerInteractEntityEvent does not get fired).
This issue is not happening with the free version.
It is _really_ annoying as it makes all plugins that relies on interaction with NPCs etc. unusable.

**Comment by libraryaddict** [comment]
Please stop pirating.

**Comment by SkytAsul** [comment]
?? My users reported me this bug, and I believe in them, they do not use a pirated version.

**Comment by libraryaddict** [comment]
You are running a pirated version of Lib's Disguises

**Comment by SkytAsul** [comment]
I am not using LD myself, I'm reporting what multiple users reported me about my own quests plugin: when using LD, they cannot interact with the NPCs. Are you sure that's because they are using a pirated version? No other way?

**Comment by libraryaddict** [comment]
If your users are reporting that issue with Lib's Disguises, then it means their server is running a pirated version of Lib's Disguises.

**Comment by SkytAsul** [comment]
They are _not_. At least one of them is guaranteeing me that he has purchased the plugin. If you want to get in contact with him, tell me.
It is a shame not wanting to fix a problem on its own plugin by hiding behind a "you pirated the soft" wall. Face you problems dude.

**Comment by libraryaddict** [comment]
Then have them get in contact with me.

Every single user that comes to me with this "problem" has pirated the plugin.

**Comment by libraryaddict** [comment]
The absolute minimum I require is the username they purchased the plugin on.

If they have purchased it, then they are using the pirated version instead of the premium version. And they need to delete the pirated version first.

**Comment by Aderomis** [comment]
Hi, i'm the user in question ! But i foun the problem, i put my LibsDisguisesPrenium.jar in the "plugins" folder instead of put it in the "LibsDisguise" folder in the "plugins" folder so it's ok now. And i paid the plugin, i can prove it if you want on discord.
