### ISSUE TITLE
Java 6 compatibility.

### ISSUE THREAD

**Issue by HoaxIT** [libraryaddict/LibsDisguises#65]
please revert back to having compatibility with java 6.

**Comment by Techcable** [comment]
@HoaxIT 
Do you like using depreciated versions of java?
I certainly like using a version of java from 2013. It makes me feel safer knowing that there are 100s of security vulnerabilities fixed in the next 2 versions of java.

**Comment by HoaxIT** [comment]
Those so called security vulnerabilities only apply to desktop clients. Some of my clients are forced to run java6 for a few reasons.

**Comment by NavidK0** [comment]
There server can have updated Java you know, it doesn't matter what version of Java the client connects with.
