### ISSUE TITLE
some disguises work, some don't

### ISSUE THREAD

**Issue by bluicecube** [libraryaddict/LibsDisguises#653]
I started using the FREE version of the plugin and found that some disguises do work and some don't. I proceeded to buy the paid version of the plugin because I was thinking it may be that I needed the premium version for certain disguises to work. It turns out that the premium plugin doesn't changed the fact that some of them don't work. When I go in F5 and look at my character, I can just see my normal character when disguised as certain things such as Enderman, Wither, Enderdragon, blaze, slime and lots and lots of others. The only ones that really seem to work are the basic animals (such as chicken, pig, cow sheep).

I am using Spigot 1.18.2 and everythin looks okay in the console. I have attached a screenshot. The plugin version is the one downloaded from the Spigot page (just today) so should be up to date?

Thankyou
![dfh](https://user-images.githubusercontent.com/104699058/166124512-92dddb3e-514a-40cc-ba98-924025640df3.PNG)

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/wiki/lib-s-disguises-faq/#tall-disguises-self-disguises

Would you like me to give you a refund?

**Comment by bluicecube** [comment]
Is there no fix for the issue though or is it something specific to the way I’m using it? I would ideally like it to work :(

**Comment by bluicecube** [comment]
Actually could I have a refund please? If that’s okay or would be greatly appreciated . Thankyou

**Comment by libraryaddict** [comment]
> Actually could I have a refund please? If that’s okay or would be greatly appreciated . Thankyou

The issue is that tall disguises is enabled by default, so disguises that would block your view are not actually applied for self disguises.

Everyone will see you disguised as expected however.
The config lets you change the behavior to stop doing that.

I've refunded your payment as requested.
