### ISSUE TITLE
Request: Command to toggle viewing of own disguise

### ISSUE THREAD

**Issue by Theepwner** [libraryaddict/LibsDisguises#66]
It would be great to have a command that could toggle the viewing of your own disguise.

For example: "/disguise seeself" could be a toggle between seeing your own disguise and not seeing your disguise. Or there could be /disguise seeself true/on, and /disguise seeself false/off.

Not sure if this is possible or not, but I sure hope it is.

**Comment by makkarpov** [comment]
Better to add not only command, but also API to toggle it.

**Comment by NavidK0** [comment]
Finally got around to this, added
