### ISSUE TITLE
Warning spamming console

### ISSUE THREAD

**Issue by srnyx** [libraryaddict/LibsDisguises#660]
- **Software:** git-Purpur-1628 (MC: 1.18.2)
- **LibsDisguises:** 10.0.28
- **ProtocolLib:** 4.8.0
- **Plugins:** https://paste.srnyx.xyz/folavizica.txt

https://paste.srnyx.xyz/quwovekohu.md

**Comment by libraryaddict** [comment]
Not sure how you got that error, are you sure your LD and PL versions are correct?

What does /version <Plugin> say?

**Comment by srnyx** [comment]
> Not sure how you got that error, are you sure your LD and PL versions are correct?
> 
> What does /version say?

That's what `/version` said. Also, the warning is spammed thousands of times. Then randomly (or not randomly, but I just don't know why) stops.
The thing is, I don't even use Lib's Disguises for anything right now, I just have it since it's an optional dependency for ItemsAdder.

**Comment by libraryaddict** [comment]
Yeah, looking at the code of the error.

It sounds like another plugin is messing around with metadata packets, and isn't doing it in a sane way.

**Comment by srnyx** [comment]
> It sounds like another plugin is messing around with metadata packets, and isn't doing it in a sane way.

```
Plugins (45): ConsoleSpamFix, CoreProtect, CustomCrafting, DiscordSRV, dynmap, Dynmap-WorldGuard*, Essentials, EssentialsSpawn, FarmControl, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, GlowAPI, IABlockUpdater, InventoryRollbackPlus, InvSeePlusPlus, ItemsAdder, ItemsAdder-WorldEdit, LibsDisguises, LightAPI, LimitPillagers, LoneLibs, LuckPerms, Multiverse-Core, Multiverse-Inventories, MyCommand, MythicMobs, PacketListenerApi, PL-Hide, PlaceholderAPI, ProtocolLib, TAB, TradeSystem, Treasury, Vanadium, VanillaTweaks, Vault, VentureChat, ViaVersion, ViewDistanceTweaks, voicechat, VooDooPlugin, WolfyUtilities, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags
```

**Comment by libraryaddict** [comment]
Don't recognize Vanadium 

PacketListenerApi could also be a guilty member
GlowAPI could be worth trying removing
FarmControl is weird, not sure but could be worth trying.

Those are just guesses.

**Comment by srnyx** [comment]
> Don't recognize Vanadium

Vanadium is my own plugin, I don't think it touches "metadata packets"

> PacketListenerApi could also be a guilty member

Not even sure what uses that to be honest, will still try

> GlowAPI could be worth trying removing

Don't think it's used at all so probably not, will still try

I'll still try them all, though (unless I forget 😔)
