### ISSUE TITLE
Skin layer issue with Player disguises.

### ISSUE THREAD

**Issue by rafael5gr2** [libraryaddict/LibsDisguises#662]
Hello there,
I don't know if this issue is already known, but when I disguise myself as a Player and want to remove a part or parts of the outer layer of their skin, it removes the wrong one or every part. Here is an example: https://www.youtube.com/watch?v=R9qL-MQ-xpw
Server setup: Paper 1.19 build 36 + LibsDisguises(with premium enabled) build 1101 + ProtocolLib(v5) build 569
And another server setup that I didn't record a video but it has the issue: Paper 1.18.2 build 386 + LibsDisguises Premium Latest from SpigotMC + ProtocolLib v4.8.0

**Comment by libraryaddict** [comment]
Also, the toggling self disguises bypassing the tall disguises thingy. That was a bug and has been fixed.

I'd advise using /dmod to modify your current disguise instead, or turning off the tall disguise when constructing said disguise
