### ISSUE TITLE
Falling_Block / Dropped_Item disguises dont work with block data (IE: colored wool/clay)

### ISSUE THREAD

**Issue by Sugudo14** [libraryaddict/LibsDisguises#67]
Hello, im having this issue running a 1.8.3 spigot server with latest version of both LibsDisguises and ProtocolLib after a lot of research and exhaustive tests, I feel like I should better ask for some help since I cant see where the problem is after hours of research.

Problem is that whenever I want to disguise a player as a falling block with color data (red wool for example), the disguise will always be the default material, without the data (default white wool). It happens with all the blocks that have that extra byte of data to select the variant of the block. Same happens with the dropped_item disguise type. I have tried a 100% clean installation of spigot 1.8.3 with latest protocollib and libsdisguises, a clean 1.8 spigot with 1.8 versions of both plugins and a clean 1.7.10 spigot with 1.7.10 versions of both plugins where it worked fine.

The bug occurred with 1.8.3 and 1.8, but this problem seems to not exist in 1.7.10.

There is no error or warning in the console, everything just seems to be fine, but I cant find the reason why the blocks variants are not working.

![1](https://cloud.githubusercontent.com/assets/11926419/7118130/614e1822-e1fd-11e4-9785-c1b7a43181cc.png)
![2](https://cloud.githubusercontent.com/assets/11926419/7118131/614fab06-e1fd-11e4-9c93-760e2f35533c.png)
![3](https://cloud.githubusercontent.com/assets/11926419/7118172/a0707bc6-e1fd-11e4-8e44-6d03349894c7.png)
![4](https://cloud.githubusercontent.com/assets/11926419/7118173/a0745070-e1fd-11e4-80aa-21f8b6fdd962.png)

Thank you in advance!

**Comment by NavidK0** [comment]
I've been extremely busy as of late with finals coming up and what not, but I am looking into this.

**Comment by Sugudo14** [comment]
That sounds awesome! Thanks for your effort even with the finals. I'll be definitely waiting for this fix.

**Comment by NavidK0** [comment]
Solved, although some block types still do not work with the recent change to block states.
