### ISSUE TITLE
LibsDisguises doesn't enable on the recent Paper builds

### ISSUE THREAD

**Issue by mercurialmusic** [libraryaddict/LibsDisguises#672]
Heya! Looks like LibsDisguises doesn't enable on the recent Paper builds. Just updated Paper and the build I was using (LibsDisguises-b1124) errored. Tried updating to b1130 and got the same:

https://gist.github.com/mercurialmusic/5c47aec02eb83cf37cfea95aaed0bb7f

Unfortunately can't downgrade Paper so I'm at your mercy. 

Paper: git-Paper-204 (MC: 1.19.2)
LibsDisguises: build 1124 (previous) and 1130

Would appreciate any assistance!

**Comment by mercurialmusic** [comment]
Welp, I was wrong about the downgrade, I was able to go back to Paper 202 which fixed the issue. I had previously tried to go back to Paper 166 or whatever I was on and it didn't like that. Leaving this open I guess in case the error is useful or someone else stumbles on here looking for the same thing I did.

**Comment by andrewkm** [comment]
Paper 1.19.2 Build 202 works just fine.
The following commit however breaks LibsDisguises:
https://github.com/PaperMC/Paper/commit/6b26cfcd310c7345330e46e89fc90b0e3368f0e0

While we're here, I should also mention that your commit here @libraryaddict:
https://github.com/libraryaddict/LibsDisguises/commit/a05bf1ed9489a57c47c6ec3eef576c68fdbd7cb9

Breaks your own Jenkins builds.
On our Jenkins they build fine but in an "unstable state"
https://gist.github.com/andrewkm/9dfcedcfbf1041dba0bbdcce443d1e33

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/7fe34e95089808e8d80ecb8c05c6f3b3506b8ed4 - Should be fixed here

**Comment by SideLo98** [comment]
can someone confirm if it's fixed in paper 207 build ?

**Comment by andrewkm** [comment]
Yes it's confirmed fixed.
The issue can be closed.
