### ISSUE TITLE
AdvancedEnchants dolphins grace not working when in /dvs

### ISSUE THREAD

**Issue by smuddgge** [libraryaddict/LibsDisguises#673]
I'm unsure if you are able to do anything about this. However, when in /dvs (where you can see your morph) as the armour disappeared, I believe the effects from dolphins grace no longer work.

**How to recreate**
- Wear boots with dolphins grace enchant from advanced enchants
- Go into /dvs so you can see your morph
- Effect no longer works

**Comment by libraryaddict** [comment]
Rephrased,

Armor enchantments that the client relies on are not played properly as self disguises visually removes the armor.
So if the enchantment let you walk on water, the client wouldn't know this as it thinks you're not wearing armor, and you'd instead sink as usual.
