### ISSUE TITLE
1.19.4 not working

### ISSUE THREAD

**Issue by NoxWilding** [libraryaddict/LibsDisguises#689]
Heyo!

I know it is early to ask support for the latest 1.19.4 version, but yeah. PaperMC 1.19.4 [#462](https://api.papermc.io/v2/projects/paper/versions/1.19.4/builds/462/downloads/paper-1.19.4-462.jar) does not support the current version of LibsDisguise.

**Comment by Brokkonaut** [comment]
Afaik ProtocolLib has to be updated first

**Comment by StanByes** [comment]
ProtocolLib has been update for 1.19.4 yesterday

**Comment by DaddyRobLIVE** [comment]
> ProtocolLib has been update for 1.19.4 yesterday

where's the link?

**Comment by StanByes** [comment]
> > ProtocolLib has been update for 1.19.4 yesterday
> 
> where's the link?

https://ci.dmulloy2.net/job/ProtocolLib/621/

**Comment by andrewkm** [comment]
LibsDisguise is not yet updated to 1.19.4
```
[12:12:09] [Server thread/ERROR]: [LibsDisguises] You're using the wrong version of Lib's Disguises for your server! This is intended for v1.12 & v1.13 & v1.14 & v1.15 & v1.16 & v1.17 & v1.18 & v1.19.R1 & v1.19.R2 & UNSUPPORTED!
[12:12:09] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v10.0.32-SNAPSHOT
```
Best to give it another week or two.
Things are just rolling out for 1.19.4

**Comment by libraryaddict** [comment]
Added initial 1.19.4 support

**Comment by andrewkm** [comment]
Thank you! :)
