### ISSUE TITLE
Player Skins are not shown in the Tab bar

### ISSUE THREAD

**Issue by mineyannik** [libraryaddict/LibsDisguises#69]
The Player Heads in the tab bar are not shown in the Skin with whom they are distinguished.

**Comment by NavidK0** [comment]
Not enough info? Seems unrelated, player heads are shown on my server.

**Comment by Carbonax** [comment]
No, same issue.
Basically if you disguise as dinnerbone, the player heads in tab will still be your own skin, not dinnerbone's head
