### ISSUE TITLE
A little question about other entity enteractions

### ISSUE THREAD

**Issue by YoYomec** [libraryaddict/LibsDisguises#690]
Hello,
I tried to disguise myself as a cat, but the creepers weren't afraid of me, even they were exploding. I changed the `MonstersIgnoreDisguises` property in Combat.yml so creepers don't explode anymore, but they still weren't scared of me.

Can you add the fact that the entities take into consideration the entity in which we disguised ourselves.
So that the creepers are afraid of me when I'm disguised as a cat. But also for example that the golems attack us if we are disguised as a monster.

Excuse my english and thanks in advance

**Comment by libraryaddict** [comment]
Libs Disguises does not change monster AI
