### ISSUE TITLE
Mobs interactions

### ISSUE THREAD

**Issue by YoYomec** [libraryaddict/LibsDisguises#699]
Hello,

Recently I saw that mobs don't see me as another mob.
Examples:
- If I disguise myself as a cat, the creepers won't be afraid of me
- If I disguise myself as a monster, the iron golems won't hit me

I haven't looked at the source code, because I don't know how to do it, but I may have an idea where the error could come from:
I think the plugin work like the 1st algorythm:

![libs drawio](https://user-images.githubusercontent.com/98414804/229150058-bde2efe2-a0d3-41a8-94ff-88aedea6ccc9.png)

But I think the 2nd algorythm is better because the tick precessing is done with me as a cat, it would imply that the creepers are afraid of me
I don't know if that's how it works and if it's complicated to modify, but it would involve some very interesting mechanics. Also, I'm not a developer, but I believe that ProtocolLib allows to manage/modify packets, so it shouldn't be too difficult to modify C2S packets before they are received by the tick process

Thanks for your very nice plugin.

**Comment by libraryaddict** [comment]
Lib's Disguises doesn't work that way.

Picture instead that you're an actor on a movie set. You put on the makeup and the costume, and you now look like an evil vampire.

Everyone will be scared of you if you run about, but you only look like the vampire. You don't have any superpowers.

Lib's Disguises only changes the way you look, it doesn't change mob behavior. Well, it does have some config options to disable targeting. But its nothing like you're describing.

**Comment by libraryaddict** [comment]
Also I don't intend to add this functionality to the plugin.
