### ISSUE TITLE
Does not work in 1.19.4 needs fixing asap

### ISSUE THREAD

**Issue by kalleswe** [libraryaddict/LibsDisguises#703]
Plugin does not work in 1.19.4, needs fixing asap

**Comment by games4681** [comment]
I already informed the programmer, he laughed at me on his discord server and closed my issue request, he is in no hurry and doesn't care about his plugin.

**Comment by libraryaddict** [comment]
I don't know who games4681 is, but you need the dev build of Lib's Disguises and an older build of PaperMC or Spigot. The latest builds of those are broken.

**Comment by games4681** [comment]
> I don't know who games4681 is, but you need the dev build of Lib's Disguises and an older build of PaperMC or Spigot. The latest builds of those are broken.

Ok thanks but when you update the plugin to work on lastet version of paper 1.19.4?
