### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by DejVIIKBob** [libraryaddict/LibsDisguises#705]
Best plugin pls update
[Server thread/ERROR]: [LibsDisguises] You're using the wrong version of Lib's Disguises for your server! This is intended for v1.12 & v1.13 & v1.14 & v1.15 & v1.16 & v1.17 & v1.18 & v1.19.R1 & v1.19.R2 & UNSUPPORTED!

**Comment by Brottweiler** [comment]
It has already been updated. https://github.com/libraryaddict/LibsDisguises/issues/689
