### ISSUE TITLE
Is permissions not working with most recent version

### ISSUE THREAD

**Issue by mcraftpete** [libraryaddict/LibsDisguises#71]
[LibsDisguises] Loading LibsDisguises v8.3.3
This server is running CraftBukkit version git-Spigot-c136710-0af2738 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
Enabling ProtocolLib v3.6.3-SNAPSHOT-b118

Works fine as op and was working prior to update.

**Comment by NavidK0** [comment]
Fixed.
