### ISSUE TITLE
Stop Auto-Updating ProtocolLib

### ISSUE THREAD

**Issue by MrTommyt** [libraryaddict/LibsDisguises#715]
Come on, auto updating the plugin on someone else's behalf it's awful, and it's causing a lot of trouble on our server because the network does not support the latest version of ProtocolLib. 

Please stop doing that automatically, some people might appreciate it but it should be opt-in, currently I see no way of opting out of it except from changing the Update folder permissions, which, it's obviously not ideal.

Please remove it, or at least make it opt-in.

**Comment by libraryaddict** [comment]
Lib's disguises breaks on older versions

**Comment by MrTommyt** [comment]
Yet, it should be up to the owner to decide whether to update or not their Version. Not to update the ProtocolLib without the user's consent. On my case, it's working perfectly fine, but the update messes up everything.

I understand it might break, but it should NOT be forced upon the user.
