### ISSUE TITLE
Laggy block disguises

### ISSUE THREAD

**Issue by makkarpov** [libraryaddict/LibsDisguises#72]
I have an issue with misc disguises such as Falling_Block or Dropped_Item. They works, but when player is moving, items moving abruptly and it looks like that they are teleporing many times instead of moving. Mob disguises works fine.

Plugin is most recent version compiled from commit 9083a5ba84d11cce03460a9df3ae7653eeac4926

**Comment by NavidK0** [comment]
It's always been like that, this can't really be fixed.

**Comment by makkarpov** [comment]
But there is a servers where block disguises are smooth for both yourself and other players. They use same vanilla 1.8 client as any other server, so this is not a client issue.

**Comment by NavidK0** [comment]
Since I've always seen this on my own servers, I assumed it was natural. What plugins do you use?

**Comment by makkarpov** [comment]
Not so much, LibsDisguises + ProtocolLib + my own minigames plugin that use disguises. I use some custom ProtocolLib code, but this code isn't interfering with disguises because it related with inventory handling and per-observer mob names.

**Comment by NavidK0** [comment]
Issue here:
https://github.com/libraryaddict/LibsDisguises/issues/89
