### ISSUE TITLE
Cannot see self disguise - new build for MC 1.20.2

### ISSUE THREAD

**Issue by DarktisDH** [libraryaddict/LibsDisguises#729]
Hello,

I have a problem, players cannot see themselfs as disguised. I have enabled this in the config but it still does not work.

![image](https://github.com/libraryaddict/LibsDisguises/assets/98430826/99253f62-324c-4130-a2ff-6b041159959c)

Others can see my disguise but I cannot see myself as disguised. It works only on few disguises like bat, but most of others does not work.

No errors or exceptions were thrown. Stack trace is clear.

I am running the new build of libsdisguises for MC 1.20.2

Thank you in advance.

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/wiki/lib-s-disguises-faq/#tall-disguises-self-disguises
