### ISSUE TITLE
Error when I come near a player disguised

### ISSUE THREAD

**Issue by xX1bumblebee1Xx** [libraryaddict/LibsDisguises#73]
Latest version of LibsDisguise and ProtocolLib. Spigot 1.8.3.
When I come near a player disguised as something I get the error below, disguises don't work either
start/error log: http://pastebin.com/yQ2Ybd9U

**Comment by NavidK0** [comment]
LibsDisguises has been updated for 1.8.6, try the latest Spigot version, LibsDisguises, and ProtocolLib and respond back with another issue if it occurs again.
