### ISSUE TITLE
Sword in double and vision obstructed

### ISSUE THREAD

**Issue by idkw** [libraryaddict/LibsDisguises#74]
I have a strange bug when using the /disguise command with a mob wearing equipment while holding a sword.

The sword is in double.

Picture : http://i.imgur.com/IJWZicI.png

Spigot version : 1.8.7
LibsDisguise for 1.8.7
ProtocolLib build #165

Only I can see it, other players can't, but it still weird.

Also when diguising as a player, I can't see anything because I'm inside the fake player.
http://i.imgur.com/lF0cDp6.png
Is there any way to make the disguise visible only to other players ? This way I wouldn't have my vision obstructed.

Am i doing something wrong ?

**Comment by NavidK0** [comment]
Change the config option ViewSelfDisguises: true to false
