### ISSUE TITLE
Dinnerbone/Grumm upside-down disguise doesn't work

### ISSUE THREAD

**Issue by TheJoshue** [libraryaddict/LibsDisguises#740]
Hello
there is an example here
https://www.spigotmc.org/wiki/lib-s-disguises-using-the-commands/
That goes
```
Upside-down player disguise with Notch's skin
/disguise player Dinnerbone setSkin Notch
```

however, when you try this, it simply does not flip player upside down
![image](https://github.com/libraryaddict/LibsDisguises/assets/56804505/f37bb91e-598f-4124-941b-67c168919c0f)

Running latest paper-1.12.2
Running LibsDisguises 10.0.40

**Comment by libraryaddict** [comment]
Use `/disguise player Notch setupsidedown`

**Comment by TheJoshue** [comment]
> Use `/disguise player Notch setupsidedown`

Thank you very much
is it possible to not touch username displayed above head at all? to leave it to server, but to set skin to specific username

**Comment by TheJoshue** [comment]
i tried `/disguise player setSkin Notch setupsidedown` but this returns "Nameless Player" above player character

**Comment by libraryaddict** [comment]
Try `/disguise player ""` or `/disguise player Notch setNameVisible false`

**Comment by TheJoshue** [comment]
> /disguise player Notch setNameVisible false

This seems to hide it fully,

i managed to do this by using `/disguise player "[Admin] TheJoshua" setSkin Notch`

I also wanted to suggest (**let me know if i should open this as new issue just to be more concize**)
to think about adding papi support for this command, especially for the part that comes after `player`, because this could be useful for like `/disguise player "%luckperms_prefix% TheJoshua" setSkin Notch` (as you can see here papi placeholder is used)

**Comment by TheJoshue** [comment]
@libraryaddict this would be my last sub-question here

How to execute this command as console or other player, targeting another player

so i want to apply disguise to my player "Test"

**Comment by libraryaddict** [comment]
Use /disguiseplayer or /disguiseuuid

**Comment by TheJoshue** [comment]
@libraryaddict is it possible to disguise while letting TAB plugin handle the nametag?
