### ISSUE TITLE
Frog Disguises Lack Sounds

### ISSUE THREAD

**Issue by UltraFaceguy** [libraryaddict/LibsDisguises#743]
For some reason, Frog disguises have no sounds. Can be quickly reproduced by disguising a slime as a frog. Seems to block the sounds even if you set a sound group for the disguise. It doesn't seem to be an issue with slimes, tested disguising slimes as multiple different entities and it always othered otherwise.

**Comment by libraryaddict** [comment]
Works fine for me. Check your minecraft settings, you may have turned off "Friendly Creatures"
