### ISSUE TITLE
Dev build #1286 flags Windows Defender as a virus & cannot be transferred to server for same reason in WinSCP

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [libraryaddict/LibsDisguises#744]
Dev build #1286 flags Windows Defender as a virus & cannot be transferred to server for same reason in WinSCP

Using Windows 11 if it matters. 

https://ci.md-5.net/job/LibsDisguises/

Defender msg:
https://gyazo.com/3d33d7029d4c9bdf3b175ec68e597b9f
More info shows:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FPhonzy.B!ml&threatid=2147772967

Though VirusTotal claims it is okay:
https://www.virustotal.com/gui/file/d9d6144ea936c99057b02d0de82051ae7b244275da4f8d0d594166572381721b

Just would be nice if you could fix whatever is causing Defender to falsely flag it.

**Comment by Brickgard** [comment]
This has been identified, you can read more discussion on the in [the Discord](https://discord.com/channels/213109157983813633/579140593293328414/1195175721107202049)
The false positive has been sent to Microsoft's security team for review - it's ultimately in their hands now.

**Comment by libraryaddict** [comment]
This may be fixed in the latest dev build, not sure. It may be a problem specific to the jenkins

**Comment by libraryaddict** [comment]
I'm told this isn't fixed in latest dev build. Unfortunately I'm closing this ticket as there's not much I can do. It may be specific to the jenkins site.
