### ISSUE TITLE
I get this warn on startup

### ISSUE THREAD

**Issue by Billybobertjoe** [libraryaddict/LibsDisguises#745]
[Server] WARN [PacketFilterManager] Plugin LibsDisguises tried to register listener for unknown packet CUSTOM_PAYLOAD[PLAY, CLIENT, 16, classNames: [net.minecraft.network.protocol.game.PacketPlayInCustomPayload, net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket, net.minecraft.network.play.client.CPacketCustomPayload] (unregistered)] [direction: from CLIENT]

**Comment by libraryaddict** [comment]
Please give the output of `/ld logs`

**Comment by Billybobertjoe** [comment]
> Please give the output of `/ld logs`

My log file: https://mclo.gs/agexd9q, my combined config files: https://mclo.gs/HflAGZu and my disguises file: https://mclo.gs/m5ZrGzf

**Comment by libraryaddict** [comment]
Best guess I have is that Geyser-Spigot is doing that.
