### ISSUE TITLE
Strange behavior with vanilla /teams command

### ISSUE THREAD

**Issue by ryanhatfield** [libraryaddict/LibsDisguises#749]
I've been looking into a strange issue on our server, and I wanted to see if anyone here could help me track down if it's the LibsDisguises plugin that's causing it.

I was attempting to write some custom functions, and use the /teams command directly but I'm getting strange behavior.

When I make a team, then add myself (or other users) that have a nickname set (or rank prefix), it adds them then removes them quick.

Here's my reproduction steps:

```
/team add tr_test "Test Team"
/scoreboard objectives add tr_testobjective killedByTeam.blue "Killed By Blue"
/scoreboard objectives setdisplay sidebar.team.blue tr_testobjective
/team modify tr_test color blue
/team join {user}
```

And the reason to use a colored scoreboard here is because it shows it's being added and removed really quick, as the scoreboard shows for a split second then goes away.

Now the reason I'm asking you guys, is that if I find a team I'm already on, one of the ones that is a randomized hex string like `abb2266f00fa8b4d`, I can interact with that team, but if I kill a mob it flashes a random UUID to the scoreboard with 1 point then goes away. I think those teams are being added by this plugin, because if I set a disguise for someone, it adds a team and adds them to it.

Any ideas?

**Comment by libraryaddict** [comment]
As far as I'm aware, it shouldn't be constantly modifying the scoreboard.
You also shouldn't be on a scoreboard controlled by LD if you're not disguised.
