### ISSUE TITLE
Disguise acts as a follow for player

### ISSUE THREAD

**Issue by Elements-** [libraryaddict/LibsDisguises#75]
https://i.elmnts.co/view.php?img=5192737

I am having an issue where the disguise is being shown to the player and it trails a few seconds behind when you run.

ProtocolLib v3.6.4-b169

Latest Libs Disguises
Latest Spigot 1.8 build

**Comment by NavidK0** [comment]
In the LibsDisguises page it says: "The 2 problems are: The disguise lags a little bit behind and sometimes the disguise 'gets in the way'."

This is an unfixable problem. If you don't like the shown disguises, you can disable third-person disguises in the config.
