### ISSUE TITLE
Player is kicked out when connecting to the server

### ISSUE THREAD

**Issue by qaz197418i** [libraryaddict/LibsDisguises#750]
When a player connects to the server, they will be kicked out and a console error will occur. I am not sure what is causing this, but it only appears when I install LibsDisagrees. After I delete it, the player's connection is normal
https://pastebin.com/M0V9itRb

Server version: Paper 1.12.2
Java11
Plugins:
![image](https://github.com/libraryaddict/LibsDisguises/assets/30312760/a317aa30-c4ce-49c8-b1d1-d19a752ed01a)

**Comment by qaz197418i** [comment]
can someone help?

**Comment by libraryaddict** [comment]
Huh. Not sure how I missed it. But this would probably be due to a setting in the config.

In configs/protocol.yml, change "LoginPayload" from true, to false.

**Comment by qaz197418i** [comment]
When I set LoginPayload to false, the same problem still occurs

**Comment by qaz197418i** [comment]
> Huh. Not sure how I missed it. But this would probably be due to a setting in the config.
> 
> In configs/protocol.yml, change "LoginPayload" from true, to false.

When I set LoginPayload to false, the same problem still occurs

**Comment by libraryaddict** [comment]
After server restart?

**Comment by qaz197418i** [comment]
> After server restart?

Yes, I even tried twice

**Comment by libraryaddict** [comment]
Hmm, should've guessed it'd close it when I said "fixes"
Anyways, in a few minutes try `/ld update dev` to update the plugin, then restart again with it on `false`

**Comment by libraryaddict** [comment]
Or download this https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar

**Comment by qaz197418i** [comment]
I'm sorry for the late reply, but even after trying the latest build, the same problem still exists

**Comment by qaz197418i** [comment]
I think this issue may be due to ProtocolLib 5.2.0

**Comment by qaz197418i** [comment]
> Or download this https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar

This issue has been fixed and requires the latest development and construction of ProtocolLib
