### ISSUE TITLE
Mythicmob undisguises everytime the server restarts

### ISSUE THREAD

**Issue by sejungH** [libraryaddict/LibsDisguises#753]
Hi,

I'm trying to create a npc with a playerskin using the libdisguises and mythicmobs,
and I below is the yml of the npc I'm adding:

Type: armor_stand
Display: 'Test'
AITargetSelectors:
  - 0 clear
  - players

Options:
    AlwaysShowName: true
    Collidable: false
    Despawn: persistent
    MovementSpeed: 0
    Interactable: false
    KnockbackResistance: 1
    NoAI: false
    PreventItemPickup: true
    PreventOtherDrops: true
    Silent: true
    CanMove: false
    PreventSunburn: true
    PreventVanillaDamage: true
  Skills:
  - disguise{d="Player Steve setDynamicName true setSkin {username}"} @self ~onSpawn
  - disguise{d="Player Steve setDynamicName true setSkin {username}"} @self ~onLoad
  - cancelevent{sync=true} @self ~onDamaged

It's working when I spawn the mob, but whenever I restart the server, it undisguises until I hit the entity at least once.
Please assist me with this issue.

**Comment by PadawanAmy** [comment]
use the disguise settings instead of the disguise mechanics
https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Mobs/Disguises

**Comment by sejungH** [comment]
> use the disguise settings instead of the disguise mechanics https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Mobs/Disguises

I added this line to the setting and respawned the mob then restarted it.
`Disguise: Player Steve setDynamicName true setSkin EVa_98`

But result was like below:
![2024-05-16_08 59 51](https://github.com/libraryaddict/LibsDisguises/assets/25574836/794a48e2-ca6c-4cc0-a834-a38a6bdca495)
![2024-05-16_09 00 48](https://github.com/libraryaddict/LibsDisguises/assets/25574836/1dc3866e-f530-4e15-92de-1b5a15b9a4ba)

**Comment by libraryaddict** [comment]
Maybe lacking premium, dunno because this is MM support not Libs Disguises
