### ISSUE TITLE
For a better information on "Dodgy Users"

### ISSUE THREAD

**Issue by Yarkane** [libraryaddict/LibsDisguises#754]
Hi everyone.

Recently, our server started to experience weird issues : random damages, random height when jumping, activated PvP besides region configuration, etc etc. As you may be aware of, these issues are volontary and due to LibDisguise "anti crack" protection. We discover, after a whole week of investigation, that without any update of our own, this was due to libdisguise which was cracked by the previous team of administrator without our knowledge.

https://github.com/libraryaddict/LibsDisguises/blob/4e9133b323fcea91c7dbc97b72bdbfb46e4d125c/plugin/src/main/java/me/libraryaddict/disguise/utilities/listeners/DisguiseListener.java#L148

The previous team of administrators did crack the plugin, but we thought it was paid and legit. As soon as we discovered we were using such version of the plugin, we immediatly paid for a legit premium plugin, and for this inconvenient I would like to apologize. It is not in the culture and spirit of our community to act this way.

However, I'm a bit frustrated that this issue was not easiest to spot. As I totally respect and encourage this kind of measure (as it is "non-destructive", it's not like the map are deleted or something like that, I think it's fair and, frankly, very funny), I think it would be beneficial to inform the users, or at least the administrators, that the version is cracked. If such messages exist, we were not able to spot it in the logs or during our investigations. With the admin who cracked the plugin gone and not in the tech team anymore, we would have appreciated such warning (and would have repaired this even with only a warning message, but I get this won't be enough to many servers).

Anyway, thank you very much for your work and have a good day !

**Comment by libraryaddict** [comment]
Isn't this a request to let pirates know if they need to crack it again?

**Comment by Yarkane** [comment]
I mean, pirates will know what the "anti-pirate" measures are so... I guess it does not make a difference at all, for them.
