### ISSUE TITLE
Protocollib broke Libsdisguise.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#756]
Paper 1.20.4 Build 497 (https://github.com/PaperMC/paper/commit/d8d54d927974f36ab1f919c808c0ed9e67e0e6f0)
LibsDisguise compiled against https://github.com/libraryaddict/LibsDisguises/commit/ed2a33f7035fd84a865ae45b45fbe1d541138bab
Protocollib latest compiled against https://github.com/dmulloy2/ProtocolLib/commit/8272ecb33d7a0197ca9c96037cf1d95ca3dd603f

Error on initializing: https://pastebin.com/raw/3JxxYsBk

I've tracked the ProtocolLib issues to one of the following builds: https://github.com/dmulloy2/ProtocolLib/commit/f0468e04d99c1acd7b2004cab5919b4fa275cce5
https://github.com/dmulloy2/ProtocolLib/commit/76432f9d3674b1186674af0081e38d2e04a053ea (a change made 10 minutes later)

Unfortunately my jenkins pings every 10 minutes, so those two commits slipped into one build.

Not sure if you care to fix it for us 1.20.4 folks who want to use the latest ProtocolLib currently as it has some changes, or if you prefer to ignore due to your packetevents project. ProtocolLib is suddenly active out of the blue so idk.

If it's an easy fix and you intend to push it in the meantime, thank you. :)
If not, feel free to close. Looking forward to your rewrite!

**Comment by libraryaddict** [comment]
Issue in PL, not LD. May be fixed in newer builds

**Comment by andrewkm** [comment]
@libraryaddict 
https://github.com/dmulloy2/ProtocolLib/commit/914bc9aa7f64be287041020ba2be804eb76eb292 has fixed initialization, but I'm getting this on disguise now: https://pastebin.com/raw/BTfXUwq8

Going to assume this is continued issues with ProtocolLib?

**Comment by libraryaddict** [comment]
Yep, you'd be correct

**Comment by andrewkm** [comment]
Confirming all looks good as of https://github.com/libraryaddict/LibsDisguises/commit/ed2a33f7035fd84a865ae45b45fbe1d541138bab & https://github.com/dmulloy2/ProtocolLib/commit/389233f599b6d0008e607f8c498bfb152a130424 via Paper 1.20.4.
