### ISSUE TITLE
Maven repository?

### ISSUE THREAD

**Issue by minecrafter** [libraryaddict/LibsDisguises#76]
Lib's Disguises used to be built on md_5's build server with a Maven repository. Since switching to Gradle and building on your own instance of Jenkins, no updated Maven repository exists. I'd like to have a supported Maven repository to take advantage of newer APIs.

**Comment by JBou** [comment]
We both already asked on spigot forums but didn't get any response. I'm really interested into it too, else I have to set up my own jenkins instance.
Regards

**Comment by NavidK0** [comment]
Working on it.

**Comment by NavidK0** [comment]
Done, new maven repo at: http://psmc.ca/repo/

**Comment by JBou** [comment]
nice work, thanks a lot!

**Comment by minecrafter** [comment]
:+1:

**Comment by minecrafter** [comment]
Umm @NavidK0, did you mean to include `gradle.properties`?

https://github.com/libraryaddict/LibsDisguises/blob/master/gradle.properties

**Comment by NavidK0** [comment]
Again, I don't see why it matters since it's an encrypted password (that you can't use to login) and that it's a localhost repo that's reverse proxied to only show /repo, but since people are concerned about security I added it to the .gitignore.

**Comment by minecrafter** [comment]
Alright, thanks for explaining.
