### ISSUE TITLE
After using the disguise of Lib's Disguises plugin, I was kicked out of the server and unable to enter again

### ISSUE THREAD

**Issue by qaz197418i** [libraryaddict/LibsDisguises#761]
After using the disguise of Lib's Disguises plugin, I was kicked out of the server and unable to enter again

console error:
https://pastebin.com/RDLt2Cp3

**Comment by libraryaddict** [comment]
Try updating to dev builds via https://ci.md-5.net/job/LibsDisguises/ or `/ld update dev` command.
You're using the release build which is based on ProtocolLib, which is being dropped. A large rewrite was done to do so.

**Comment by qaz197418i** [comment]
> Try updating to dev builds via https://ci.md-5.net/job/LibsDisguises/ or `/ld update dev` command. You're using the release build which is based on ProtocolLib, which is being dropped. A large rewrite was done to do so.

The latest development version cannot be loaded
https://pastebin.com/gHTc9Pkj

**Comment by libraryaddict** [comment]
> > Try updating to dev builds via https://ci.md-5.net/job/LibsDisguises/ or `/ld update dev` command. You're using the release build which is based on ProtocolLib, which is being dropped. A large rewrite was done to do so.
> 
> The latest development version cannot be loaded https://pastebin.com/gHTc9Pkj

Unfortunately you trimmed the log and its missing important information. Please post the full log

**Comment by qaz197418i** [comment]
> > > Try updating to dev builds via https://ci.md-5.net/job/LibsDisguises/ or `/ld update dev` command. You're using the release build which is based on ProtocolLib, which is being dropped. A large rewrite was done to do so.
> > 
> > 
> > The latest development version cannot be loaded https://pastebin.com/gHTc9Pkj
> 
> Unfortunately you trimmed the log and its missing important information. Please post the full log

https://pastebin.com/
This is the complete server startup log

**Comment by libraryaddict** [comment]
That's the pastebin site yes, but not the log

**Comment by qaz197418i** [comment]
> That's the pastebin site yes, but not the log

Sorry, my mistake. I didn't notice that the log exceeded the maximum character limit
[latest.log](https://github.com/user-attachments/files/16106293/latest.log)

**Comment by libraryaddict** [comment]
This is an issue in packetevents, Libs Disguises relies on PacketEvents but if you downgrade to the last Libs Disguises release, then it'll use ProtocolLib instead.

Line 134

```
[14:39:37] [Server thread/INFO]: [packetevents] Loading packetevents v2.4.0
[14:39:38] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_12_R1.CraftServer] java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @3a763f75 initializing packetevents v2.4.0 (Is it up to date?)
java.lang.IllegalStateException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @3a763f75
	at io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:107) ~[?:?]
	at io.github.retrooper.packetevents.PacketEventsPlugin.onLoad(PacketEventsPlugin.java:40) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @3a763f75
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
	at com.github.retrooper.packetevents.util.reflection.Reflection.getFields(Reflection.java:40) ~[?:?]
	at com.github.retrooper.packetevents.util.reflection.Reflection.getField(Reflection.java:66) ~[?:?]
	at com.github.retrooper.packetevents.util.reflection.Reflection.getField(Reflection.java:74) ~[?:?]
	at io.github.retrooper.packetevents.util.SpigotReflectionUtil.initFields(SpigotReflectionUtil.java:294) ~[?:?]
	at io.github.retrooper.packetevents.util.SpigotReflectionUtil.init(SpigotReflectionUtil.java:419) ~[?:?]
	at io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103) ~[?:?]
	... 5 more```

**Comment by qaz197418i** [comment]
> This is an issue in [packetevents](https://github.com/retrooper/packetevents/issues), Libs Disguises relies on PacketEvents but if you downgrade to the last Libs Disguises release, then it'll use ProtocolLib instead.
> 
> Line 134
> 
> ```
> [14:39:37] [Server thread/INFO]: [packetevents] Loading packetevents v2.4.0
> [14:39:38] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_12_R1.CraftServer] java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @3a763f75 initializing packetevents v2.4.0 (Is it up to date?)
> java.lang.IllegalStateException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @3a763f75
> 	at io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:107) ~[?:?]
> 	at io.github.retrooper.packetevents.PacketEventsPlugin.onLoad(PacketEventsPlugin.java:40) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @3a763f75
> 	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
> 	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
> 	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
> 	at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
> 	at com.github.retrooper.packetevents.util.reflection.Reflection.getFields(Reflection.java:40) ~[?:?]
> 	at com.github.retrooper.packetevents.util.reflection.Reflection.getField(Reflection.java:66) ~[?:?]
> 	at com.github.retrooper.packetevents.util.reflection.Reflection.getField(Reflection.java:74) ~[?:?]
> 	at io.github.retrooper.packetevents.util.SpigotReflectionUtil.initFields(SpigotReflectionUtil.java:294) ~[?:?]
> 	at io.github.retrooper.packetevents.util.SpigotReflectionUtil.init(SpigotReflectionUtil.java:419) ~[?:?]
> 	at io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103) ~[?:?]
> 	... 5 more```
> ```

But if I use the latest version of Libs Issues, I will encounter problems like the one that starts with this issue. If I use the latest version of ProtocolLib instead of the development version, I will encounter issues related to https://github.com/libraryaddict/LibsDisguises/issues/750 Same question
This makes me very distressed, I can't use them normally no matter what

**Comment by libraryaddict** [comment]
I think you may be able to fix this one by either upgrading java or downgrading java. I'm not sure which direction you would go though.

**Comment by qaz197418i** [comment]
> I think you may be able to fix this one by either upgrading java or downgrading java. I'm not sure which direction you would go though.

if i want to upgrading java which version is better

**Comment by libraryaddict** [comment]
Java 8 is the minimum, so you could try java 16, then 15, or just jump straight to 8.

**Comment by qaz197418i** [comment]
> Java 8 is the minimum, so you could try java 16, then 15, or just jump straight to 8.

I tried to downgrade all the way to Java11, but it didn't work. Even under Java11, the viaversion plugin couldn't run anymore, so I couldn't downgrade to a lower level

**Comment by libraryaddict** [comment]
You can try filing an issue on packetevents, which is who the problem actually is
https://github.com/retrooper/packetevents

**Comment by qaz197418i** [comment]
> 我尝试在 packetevents 上提交问题，这就是问题所在 https://github.com/retrooper/packetevents

No problem, I will open an issue

**Comment by qaz197418i** [comment]
> You can try filing an issue on packetevents, which is who the problem actually is https://github.com/retrooper/packetevents

No problem, I will open an issue
