### ISSUE TITLE
Conflicts with other plugins and an error is reported

### ISSUE THREAD

**Issue by cyt1260** [libraryaddict/LibsDisguises#766]
Through many tests, I proved that this plugin was the cause. I swear I'm telling the truth, and It's not packetevents-spigot-2.4.0 responsibility.
 
I installed packevents-spigot-2.4.0.jar alone and there was no error, but it started to report errors after installing libsdisguise.

version: latest dev version for 1.21
core: paper-1.21-109

log(you can see the error at the bottom)：
https://paste.fastmirror.net/?42425501cf4242f7#5xNhz2gWa6B56Z5yNbyx82VjGDpdr3FrFDXBP9zoztUB

especially:
<img width="1371" alt="Image_1722043521858" src="https://github.com/user-attachments/assets/6663adbe-a0ca-40bc-a1a1-c3b8168836ef">

**Comment by libraryaddict** [comment]
https://github.com/retrooper/packetevents/pull/866
