### ISSUE TITLE
FallingBlock damage value always 0

### ISSUE THREAD

**Issue by westjet1** [libraryaddict/LibsDisguises#77]
As the title says, I'm trying to disguise a Player as a fallingblock. I can do the id value, but the damage value is completely ignored. Any ideas? What am I doing wrong?

MiscDisguise md = new MiscDisguise(DisguiseType.FALLING_BLOCK,5,3);
		DisguiseAPI.disguiseToAll(p,md);

**Comment by NavidK0** [comment]
On the Spigot forums I mentioned that this is broken due to the recent 1.8_R3 API update. I'm looking for a fix.

**Comment by NavidK0** [comment]
Fixed with https://github.com/libraryaddict/LibsDisguises/commit/aee904200ba76d5e02105091453834682cb2d73e
