### ISSUE TITLE
Shearing casuing disconect when using a disguise to all near by players

### ISSUE THREAD

**Issue by KugelblitzNinja** [libraryaddict/LibsDisguises#774]
LibsDisguises is causing players nearby anyone shearing sheep, using a select list of disguises to disconnect.

The only message server side we get to see is 
  - PlayerName lost connection: Disconnected

This has been happning since we updated to 1.21

The disguised used in the attached video is eye of ender.

https://github.com/user-attachments/assets/ad9d1ff1-5076-46e8-aef5-96fa9c8a5fe7

using Lib's Disguises v10.0.44-SNAPSHOT-b1451

Players have the following related perms
 - libsdisguises.disguise.ender_signal.nooptions
 - libsdisguises.disguise.ender_crystal.setglowing  
 - libsdisguises.disguise.shulker_bullet.nooptions

**Comment by libraryaddict** [comment]
Try updating, a build was pushed earlier today that fixed a similar issue

**Comment by KugelblitzNinja** [comment]
Updated to the dev build, and yes it has been fixed.
