### ISSUE TITLE
Enabling SelfDisguisesScaling causes the disguise visible to others to scale even further

### ISSUE THREAD

**Issue by anviks** [libraryaddict/LibsDisguises#775]
After enabling SelfDisguisesScaling in players.yml, the self disguise is correct, but the disguise visible to others becomes even larger for large entities and smaller for small entities.
Example with Giant:

![My POV](https://github.com/user-attachments/assets/db2bb435-3275-4ae6-9206-7a739f7768aa)
![Observer's POV](https://github.com/user-attachments/assets/c261edf4-f0ee-4c82-8905-fa41de536de1)

**Comment by libraryaddict** [comment]
It's annoying that this is both really simple in logic, and difficult to execute well. Still working on this rest assured.

**Comment by libraryaddict** [comment]
A fix was deployed, update via `/ld update dev` to grab it
