### ISSUE TITLE
Incompatible with latest Paper 1.21.1 or ProtocolLib 5.3.0 release

### ISSUE THREAD

**Issue by Geitenijs** [libraryaddict/LibsDisguises#777]
After updating Paper to build 1.21.1-127 I'm getting this error on startup. I updated ProtocolLib to 5.3.0 release at the same time, so that could be related. Disguises don't appear to work
https://pastebin.com/wKeG9KN0

**Comment by libraryaddict** [comment]
Use dev builds
https://ci.md-5.net/job/LibsDisguises/

**Comment by libraryaddict** [comment]
Oh wait, you probably are. But I need the full log anyways.

**Comment by Geitenijs** [comment]
Yeah I'm running build 1462

here's my full startup log https://pastebin.com/DmYHePpV

**Comment by libraryaddict** [comment]
Great. I'll have to check tomorrow if this is also an issue in spigot, before I start working on a solution.
