### ISSUE TITLE
Startup issue on 1.12.2

### ISSUE THREAD

**Issue by TheJoshue** [libraryaddict/LibsDisguises#779]
Plugin does not enable successfully using 1.12.2 server with very latest dev build from jenkins as of writing
https://mclo.gs/ShfXo2C

**Comment by TheJoshue** [comment]
Ok during the time i was posting, i somehow missed jenkins build 1486 (i really don't know how because i just checked jenkins before posting this) and it seems that build 1486 solves this

Thank you!

**Comment by libraryaddict** [comment]
Because I saw your issue, tested, found problem, commited, then forgot to close this issue :P

**Comment by TheJoshue** [comment]
> Because I saw your issue, tested, found problem, commited, then forgot to close this issue :P

ok then the jenkins server is in different timezone than mine XD i really questioned how i didn't see the build, because i checked jenkins 2 times + tested on 3 different server versions and just then decided to post

**Comment by libraryaddict** [comment]
I think its UTC, reports as 12pm for me but its 1am currently. I'm New Zealand for context
