### ISSUE TITLE
disguising and undisguising event types.

### ISSUE THREAD

**Issue by 1337caleb** [libraryaddict/LibsDisguises#78]
Hello, I'm a hired developer from a server, and ive been given the task to disable pvp when a player is disguised, is there a event type for when a player is disguising and undisguising? I can't find it anywhere, and is there a chance someone can implant an event type of disguising and undisguising?

**Comment by NavidK0** [comment]
Here you go: https://www.spigotmc.org/wiki/lib-s-disguises-disguising-the-entity/

There's two events, DisguiseEvent and UndisguiseEvent.

**Comment by 1337caleb** [comment]
Thank you!
