### ISSUE TITLE
Built in updater grabs wrong dev version

### ISSUE THREAD

**Issue by JasonHorkles** [libraryaddict/LibsDisguises#785]
When using `/ld update dev`, it downloads build 1314. This even happens on the latest dev build (1494).
![image](https://github.com/user-attachments/assets/dc862f7a-bbb2-47e1-902c-84f1d83859f7)

**Comment by libraryaddict** [comment]
Sounds like you might be on a build that was broken for updates

**Comment by JasonHorkles** [comment]
But it happens even on the latest dev lol

**Comment by libraryaddict** [comment]
1314 is the last release, not dev build.

**Comment by JasonHorkles** [comment]
Right but I'm on a dev build currently and running `/ld update dev` downloads that release build instead

**Comment by libraryaddict** [comment]
Check `libsdisguises.yml`
You have changed it to `RELEASES` instead of `SAME_BUILDS`

**Comment by JasonHorkles** [comment]
Ah I see. Wouldn't it make sense for adding 'dev' or 'stable' to the command to override that setting?
