### ISSUE TITLE
Kicking played when exiting Bed

### ISSUE THREAD

**Issue by groovyloopylou** [libraryaddict/LibsDisguises#787]
Libs is #1500 and Protocol is 5.3.0. (has happened on earlier versions too)
Running 1.21.1

Issue:
When leaving a bed while in a disguise, the sleeping player and anyone nearby is being kicked out of the game with "Network Protocol Error"

Steps to Replicate:
/dis sheep (have tried quite a few - all with same result)
get into bed
leave bed
sleeping player and anyone nearby is disconnected with the disconnect reason mentioned above.

**Comment by libraryaddict** [comment]
Libs Disguises uses packetevents now, try using `/ld update pe`
Though, need more information. Can you provide the output of /ld logs
