### ISSUE TITLE
/help libsdisguise showing null

### ISSUE THREAD

**Issue by Log1x** [libraryaddict/LibsDisguises#79]
Hi.

I'm a bit late on reporting this as I figured it'd probably get caught by someone else (or maybe it's not a sane fix?) but /help libsdisguise shows null for every value and shows every command no matter what your permissions are. It's been this way for the past 4-5 official releases.

I have attempted to block it in help.yml but it still comes through.

![LibsDisguise Help](http://log1x.com/screenshots/2015-07-14_08-15-55.png)

It is the only plugin I've ever had do this.

**Comment by NavidK0** [comment]
Ah, it's because none of the commands have any descriptions. I'll fix this immediately, thanks for bringing it up.

**Comment by NavidK0** [comment]
Fixed with https://github.com/libraryaddict/LibsDisguises/commit/1d54ba9997c47cb332df6c3cb19a96a6da94989a
