### ISSUE TITLE
Cannot compile LibsDisguises due to hard fork.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#792]
Cannot compile LibsDisguises due to hard fork.
https://pastebin.com/raw/JyntWSGZ
@libraryaddict transitive dependency issue (?)

**Comment by libraryaddict** [comment]
Oh good lord. I'll probably just pin paper at a low version

**Comment by andrewkm** [comment]
Compiled fine now. :)
