### ISSUE TITLE
disguises are invisible to disguisee after world change until changing there disguise

### ISSUE THREAD

**Issue by chillerkraft** [libraryaddict/LibsDisguises#80]
i noticed on my server during testing that if i ever change worlds, i can't see my disguise anymore until i do another disguise command, i noticed that /vsd done twice got it visible again

**Comment by NavidK0** [comment]
I'll look into it.

**Comment by chillerkraft** [comment]
let me know if you need any more info from my testing
may i also note that my player was still invisible when my disguise wasn't visible after world changing (i was using vsd during testing) so when i change worlds anytime, my disguise dissapears and my player skin still is invisible aswell. i can look into if the disguise is also invisible to other players at world change.. or do you have enough to work with already :)

**Comment by chillerkraft** [comment]
alright did some testing quick and found that disguises are visible to other players when invisible to disguiser after world change.

**Comment by NavidK0** [comment]
Alright, that's good to know. Is this bug as of the new /vsd command?

**Comment by chillerkraft** [comment]
no, i believe it's always been a problem for me when using viewselfdisguise: true
i know i've noticed it at least a few times in the past year or 2 at least... but not always, because i usually have it set at false when i'm playing

**Comment by chillerkraft** [comment]
im not sure why i didn't mention this before... i'm guessing i did. somewhere..

**Comment by NavidK0** [comment]
Fixed with https://github.com/libraryaddict/LibsDisguises/commit/41cfa8eeaa5e51c787a010813f6495288083e881

**Comment by chillerkraft** [comment]
awesome :D will test soon. ty!!
