### ISSUE TITLE
Undisguising makes players invisible. 

### ISSUE THREAD

**Issue by DahFrozen** [libraryaddict/LibsDisguises#81]
Hi,
When a player is disguised and they come out of their disguise (through the "/u" command or attacking/being attacked by another player) they completely vanish. They also vanish when they enter a new disguise they vanish as well. The only way to see them in their new form is to relog.
This server is running Lib's Disguises v.8.6.2 by libraryaddict, maintained by NavidK0.
Thanks,
Frozon.

**Comment by NavidK0** [comment]
Have they tried to toggle /vsd?

**Comment by DahFrozen** [comment]
Would using "/vsd" fix it? They haven't toggled it before.

**Comment by NavidK0** [comment]
It might, try it

**Comment by DahFrozen** [comment]
It appears to be random. Sometimes players vanish when they disguise, undisguise or change their disguise. Sometimes players have to walk around for a few seconds in order to become visible. It's very annoying.

**Comment by NavidK0** [comment]
Fixed with https://github.com/libraryaddict/LibsDisguises/commit/41cfa8eeaa5e51c787a010813f6495288083e881
