### ISSUE TITLE
Disguising as a player kicks everyone else

### ISSUE THREAD

**Issue by JackzTaEpic** [libraryaddict/LibsDisguises#82]
There is no stacktrace. Im running spigot. I am also using multiverse and was recently having problems with world corruption, but this happened before that.

If I try to disguise as another player, everyone except me gets disconnected off the server.
I've tried disguising as people on the server, and off. 

I can disguise as any other mob completely fine.

**Comment by NavidK0** [comment]
Does this happen on a bungeecord server? Is it in offline mode?

**Comment by JackzTaEpic** [comment]
Well I have a bungeecoord server, but my friends are directly connecting to the server (The bungee is not up), so the actual server is offline mode. Guessing I need it true because player server?

**Comment by NavidK0** [comment]
I just tested it on my test server, I can't reproduce the issue is why I ask.

**Comment by NavidK0** [comment]
By offline mode, I meant is the bungeecord server in offline mode?

**Comment by JackzTaEpic** [comment]
It is online mode.

**Comment by NavidK0** [comment]
Alright. Can you try these two and tell me if this fixes the problem?

https://www.spigotmc.org/resources/libs-disguises.81/download?version=37252

http://ci.dmulloy2.net/job/ProtocolLib/189/artifact/target/ProtocolLib.jar

**Comment by JackzTaEpic** [comment]
Should I start up bungeecoord, or would it be fine connecting directly
without bungee?

**Comment by NavidK0** [comment]
You should definitely use bungee

**Comment by JackzTaEpic** [comment]
​I tested with and without bungee and it kicked my other account twice.​

**Comment by NavidK0** [comment]
What is the message it shows when it kicks you?

**Comment by NavidK0** [comment]
Also, I feel like it would be more efficient to go to some other medium to solve this. You got any form of contact like Skype or etc?

**Comment by JackzTaEpic** [comment]
​​
If I use bungee, it wont tell me it just says the server went down (It
doesnt) and then moves me to the fallback server

​If I directly connect​: Internal Exception
io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsExcception: reader.Index(1) + length(1) exceeds
writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap:1 ). And in the
console looks like protocol errors.

**Comment by JackzTaEpic** [comment]
Also my skype is jackson.bixby

**Comment by NavidK0** [comment]
Solved.

**Comment by JBou** [comment]
So what was the problem?

**Comment by NavidK0** [comment]
The disguises weren't working on his corrupted world. They were working fine after he unloaded the corrupted world.
