### ISSUE TITLE
kCauldron issue with Lib's Disguises/Protocollib.

### ISSUE THREAD

**Issue by keenerb** [libraryaddict/LibsDisguises#84]
I'm using protocollib and Lib's Disguises on a kCauldron (1.7.10, build 152) server.

I have no real idea where the issue is arising, it could be a Cauldron problem or even MythicMobs or some other source.

My basic issue is that player skins do not download from Mojang servers:

```
[11:57:12] [Craft Scheduler Thread - 8/INFO]: [LibsDisguises] Error when fetching skuli_steinulf's uuid from mojang: null
```

I've also had several other errors, which you can see here:
http://pastie.org/pastes/10359559/text?key=vkplyxo2h8rnvyxh4kvsfq

Full server error log is available here:
http://modpacks.roleplayga.org/modpacks/latest.log

I've tried many different combinations of protocollib and Lib's Disguises and all have the same problem.  Currently I'm using:

```
ProtocolLib 3.6.4 (recommended build from http://ci.shadowvolt.com/job/ProtocolLib/)
LibsDisguises 8.2.6-snapshot (build 349 from http://ci.md-5.net/job/LibsDisguises/349/)
```

**Comment by NavidK0** [comment]
You need to find the correct version of ProtocolLib for 1.7.10, newer versions of ProtocolLib will not work with older versions of Minecraft servers. In any case, I can't really provide support for 8.6.2 and older, as I didn't work on those versions of LibsDisguises.
