### ISSUE TITLE
Player and disguises invisible after reload

### ISSUE THREAD

**Issue by xYourFreindx** [libraryaddict/LibsDisguises#86]
I have my minigame disable before your plugin does, and in it's disable, I stop and remove all disguises. 
After the reload is complete however, the player is now completely invisible to everyone.
Putting on a new disguise does nothing. The new disguise is invisible as well. 
Hitting the viewer, breaking a block, taking damage, none of that works...
Logging out works...
But I found that this simple line:
```java
getPlayer().setAllowFlight(getPlayer().getAllowFlight());
```
Will update the player. And they, and their disguise, if they're wearing one, will become visible again.

I'm not sure why this happens.
But I thought it was worth pointing out.

**Comment by NavidK0** [comment]
LibsDisguises doesn't support /reload, if that's what you're referring to.

**Comment by xYourFreindx** [comment]
-facepalm-
Not on my watch.
