### ISSUE TITLE
Invalid Import in PlayerDisguise class?

### ISSUE THREAD

**Issue by oliverdunk** [libraryaddict/LibsDisguises#88]
https://www.spigotmc.org/threads/libsdisguises-build.91223/#post-1001886

**Comment by NavidK0** [comment]
It exists here https://github.com/dmulloy2/ProtocolLib/blob/master/ProtocolLib/src/main/java/com/comphenix/protocol/wrappers/WrappedGameProfile.java
Make sure you use an updated version of ProtocolLib
