### ISSUE TITLE
RemoveArmor causing armor to be permanently destroyed.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#90]
```
RemoveArmor: true
```

When a player disguises, if they were previously wearing armor, their armor is permanently destroyed. Shouldn't it only hide the armor, not destroy it?

ProtocolLib dev 196
http://ci.shadowvolt.com/job/ProtocolLib/196/
LibsDisguise dev 53
http://server.psmc.ca:8080/job/LibsDisguises/53/

**Comment by termanator1128** [comment]
its still there if u shift click on it it is

**Comment by mibby** [comment]
Why was this issue closed? This is still an issue that occurs. Permanently destroys inventory items instead of removing it.

**Comment by NavidK0** [comment]
Hmm... my bad, I wasn't aware this was still an issue. I meant to post something before I closed it.

**Comment by NavidK0** [comment]
Is this still an issue with the latest dev builds in 1.9? I've completely changed the way items are handled, disguises now use entity equipment instead of armor arrays.

**Comment by NavidK0** [comment]
I believe this is fixed now. Feel free to ask me to reopen if this occurs again.
