### ISSUE TITLE
NameAboveHeadAlwaysVisible not functional on 1.8

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#91]
```
# This is only called into action when the disguise is constructed using the commands.
# And when the disguise supports that. This will not be used at all for plugins constructing the disguises for instance.
# Such as prophunt. Its also false because its kind of a retarded feature.
# This is pretty simple. It shows the players displayname (Name as it appears in chat) above their head.
# This also overrides any custom name they have set in their disguise options.
ShowNamesAboveDisguises: true
# This supports the above option.
# If this is true, then the name shown above the head appears regardless of if you are looking at the disguise directly or not.
NameAboveHeadAlwaysVisible: true
```

NameAboveHeadAlwaysVisible does not show the nametag as always visible. You can only see player nametags when hovering over their disguise. Is this a limitation with 1.8?

**Comment by NavidK0** [comment]
Yes, the name will not appear unless someone hovers over it when they are near the mob. The solution for his is to make an armorstand which is named follow the disguise, but it quickly becomes complicated with multiple disguises and tracking them, and I am limited on time.

**Comment by mibby** [comment]
Alright, no worries. It is the best of both worlds then. No nametag and nametag. :)
