### ISSUE TITLE
Latest spigot 575 causing error.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#94]
http://pastebin.com/raw/zMqb9aq3

**Comment by NavidK0** [comment]
Linkage errors are always a pain, it usually has to do with the dependency being updated and LibsDisguises not being update. Meaning you likely have a newer version of ProtocolLib than LibsDisguises depends on (or maybe older)

**Comment by NavidK0** [comment]
Okay, can you try these builds for me and see if it fixes the issue?

ProtocolLib: http://ci.dmulloy2.net/job/ProtocolLib/222/

LibsDisguises: http://server.o2gaming.com:8080/job/LibsDisguises/60/

**Comment by andrewkm** [comment]
Updated to #222 and still on #59.
Issue has been resolved.

**Comment by NavidK0** [comment]
Alright, thanks for testing.
