### ISSUE TITLE
Be able to disguise as a block (not falling_block).

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#95]
Would it be possible to be able to disguise as any block and not be mine-able? Not a falling_block since that is very buggy when flying while disguised.

**Comment by NavidK0** [comment]
I meant to comment on this before, I'm debating on whether or not I want to add this. On one hand, it's a very interesting feature to be able to disguise as blocks, but on another, blocks are not entities and have to be handled differently.

**Comment by NavidK0** [comment]
I've decided I will add this in the future.
